Fix lower triangular shear values
napari/napari pull request #1839
Opened 2020-11-05 15:58 UTC by sofroniewn

# Description
This fixes the shear decomposition for lower triangular matrices. It closes #1826 and #1830 by enabling round trips with lower triangular shear matrices. It doesn't change our API, but makes it now conform to user expectations (I hope), by detecting whether lower triangular or upper triangular matrices are being used and doing the decomposition appropriately as needed. Tests have also been added, but it could probably do with some real world testing too!!

Thanks to input from @tlambert03 @jni @zeroth @VolkerH @GenevieveBuckley. This is now ready for review.

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References
Closes #1826
Closes #1830

# How has this been tested?

- [x] Tests added

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2020-11-06 02:04 UTC, GenevieveBuckley commented on napari/utils/transforms/transform_utils.py
> +def check_shear_triangular(matrix):
```suggestion
def check_matrix_triangular(matrix):
```

I think this function isn't specific to shear, so we should give it a more general name.

2020-11-06 02:05 UTC, GenevieveBuckley commented on napari/utils/transforms/_tests/test_transforms.py
> +    """Test repeatedly settting shear lower triangular."""
```suggestion
    """Test repeatedly setting shear with a lower triangular matrix."""
```

2020-11-06 02:10 UTC, GenevieveBuckley commented on napari/utils/transforms/transform_utils.py
> +            return False
I don't like this - given the docstring "Check if a matrix is triangular" I expect the function to return `True` for either an upper triangular or lower triangular matrix, and return `False` (or raise an error) if the matrix is not any kind of triangular.

2020-11-06 02:12 UTC, GenevieveBuckley commented on napari/utils/transforms/_tests/test_transform_utils.py
> +    """Determine shear triangular of matrix."""
Suggestion:

```python
def test_check_matrix_triangular():
    """Determine if a matrix is triangular."""
   ...
```

2020-11-06 02:13 UTC, GenevieveBuckley commented on napari/utils/transforms/_tests/test_transform_utils.py
> +    assert not check_shear_triangular(lower)
I dislike this `assert not`, it's very unintuitive. I've left a comment further down discussion this in the `check_shear_triangular` function.

2020-11-06 02:43 UTC, GenevieveBuckley requested changes
Thanks Nick!

I feel strongly that `check_shear_triangular` should be more accurately renamed `check_matrix_triangular` and return True if the matrix is *either* upper or lower triangular, and False if it's not any kind of triangular. If we change that then I think this whole PR will be quite clear and easy to understand.

2020-11-06 04:06 UTC, jni reviewed
@sofroniewn I've made one suggestion, otherwise this looks good. It would be good for @zeroth to take a look here also.

I just noticed that @GenevieveBuckley had the same objection as me regarding `check_matrix_triangular`, so I think that's a good indication that that should change! :joy:

2020-11-06 04:06 UTC, jni commented on napari/utils/transforms/transform_utils.py
> +def check_shear_triangular(matrix):
@sofroniewn this needs a rename or a refactor or something. I would not expect that `check_shear_triangular(mat)` would return `False` for a lower-triangular matrix... Some options:

- `check_shear_matrix()` -> `Enum(UPPER, LOWER, DIAG, FULL)`
- Separate `is_any_triangular` and `is_upper`/`is_lower` checks, so where you say `self._upper_triangular = `, you would do:

```python
check_any_triangular(shear_mat)  # raise if not
self._upper_triangular = is_upper_triangular(shear_mat)
```

I don't mind either of these...

2020-11-06 04:06 UTC, jni commented on napari/utils/transforms/transform_utils.py
> +        return True
... And this is extremely surprising! Not better to raise here?

2020-11-06 04:17 UTC, GenevieveBuckley commented
Now that I'm thinking more about this, the renaming should be consistent with the other two functions as well.

How about this set of names, @sofroniewn
* `is_matrix_any_triangular`
* `is_matrix_upper_triangular`
* `is_matrix_lower_triangular`

2020-11-06 04:20 UTC, sofroniewn commented
> - is_matrix_any_triangular
> - is_matrix_upper_triangular
> - is_matrix_lower_triangular

I like these suggestions, will rework to include, thanks @jni @GenevieveBuckley for the review!

2020-11-15 22:44 UTC, sofroniewn commented on napari/utils/transforms/_tests/test_transforms.py
> +    """Test repeatedly settting shear lower triangular."""
changed

2020-11-15 22:44 UTC, sofroniewn commented on napari/utils/transforms/transform_utils.py
> +def check_shear_triangular(matrix):
i've made this change now, and while i appreciate how it wasn't ideal before, i now have to duplicate the error message and some other checking, which I don't love. Curious what people think of the new version

2020-11-15 22:49 UTC, GenevieveBuckley approved these changes
Looks good to me!

2020-11-15 22:50 UTC, sofroniewn commented
This is ready for re-review. I dropped `check_shear_triangular` and added `is_matrix_triangular` which I think was a good idea, but unfortunately now need to duplicate the error message. Open to suggestions @GenevieveBuckley @jni. I'm also happy to merge as is

2020-11-15 23:06 UTC, GenevieveBuckley commented
> This is ready for re-review. I dropped `check_shear_triangular` and added `is_matrix_triangular` which I think was a good idea, but unfortunately now need to duplicate the error message. Open to suggestions @GenevieveBuckley @jni. I'm also happy to merge as is

No particular suggestion here, the slight duplication doesn't bother me too much.

2020-11-16 08:25 UTC, jni approved these changes
Great! I've made a minor suggestion to the testing. Will be awesome to have this in!

2020-11-16 08:25 UTC, jni commented on napari/utils/transforms/_tests/test_transforms.py
> +    np.testing.assert_almost_equal(mat, transform.shear)
Lovely. =) One thing I would say is that there is still a failure mode here, if somehow `Affine` overwrites `mat`. So I would do above: `transform = Affine(shear=mat.copy())`, and so on in the various segments. This is unlikely to be an error arising in the future but I'd still sleep more soundly with that code. I'll suggest it now.

2020-11-16 08:25 UTC, jni commented on napari/utils/transforms/_tests/test_transforms.py
> +    transform.shear = mat
```suggestion
    transform = Affine(shear=mat.copy())
    # Check shear decomposed into lower triangular
    np.testing.assert_almost_equal(mat, transform.shear)

    # Set shear to same value
    transform.shear = mat.copy()
    # Check shear still decomposed into lower triangular
    np.testing.assert_almost_equal(mat, transform.shear)

    # Set shear to same value
    transform.shear = mat.copy()
```

2020-11-16 10:42 UTC, merged