Test for warning rather than error on flat multiscale
napari/napari pull request #2224
Opened 2021-02-06 04:24 UTC by jni

# Description

I have a moderately sized array of shape approximately (200, 50, 500, 500). I don't need actual multiscale, but I do want to use different chunking for 2D view and 3D view. It's slightly an implementation-detail based hack but I thought I would give my array as a multiscale, with the 0 scale having chunksize (1, 1, 500, 500), and the 1 scale having chunksize (50, 500, 500). This makes a significant difference when scrolling through the timepoints in both 2D and 3D.

Current behaviour is to error when given two arrays of the same shape. Here I propose to simply warn.

Other alternatives:

- check whether arrays have a `chunksize` attribute and compare on that,
  keeping current behaviour the unchanged for non-chunked arrays.
- always allow inconsistent multiscale, leaving the user to use the API
  appropriately.
- something else?

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-02-06 04:46 UTC, tlambert03 approved these changes

2021-02-06 05:00 UTC, sofroniewn commented
> It's slightly an implementation-detail based hack but I thought I would give my array as a multiscale, with the 0 scale having chunksize (1, 1, 500, 500), and the 1 scale having chunksize (50, 500, 500). This makes a significant difference when scrolling through the timepoints in both 2D and 3D.

I can't say I love this change, because it's a little funny to me that it works.

The fact that for 2D do you always get level 0 seems very much by chance. I guess there is a line in there that finds the highest resolution possible for a given zoom so you'll always get level 0 

For multiscale 3D data we go with the lowest resolution level (the 1 level here) because we havn't implemented multiscale 3D yet. Once that is implemented though it will go back to using the 0 level and this wont work again.

I'd rather not make a change that will cease to work once we get 3D multiscale working.

I wonder if we can explore

> check whether arrays have a chunksize attribute and compare on that, keeping current behaviour the unchanged for non-chunked arrays.

before we merge this

2021-02-06 16:32 UTC, sofroniewn requested changes
See comment above about concerns around what happens when we support 3D multiscale wanting to discuss alternatives before merge

2021-02-23 04:34 UTC, jni commented
Ha, [this comment](https://forum.image.sc/t/ome-ngff-combine-multiple-images-into-one-dataset/47619/9) from @joshmoore:

> For example, we’re starting to look into storing multiple different downsamplings (e.g. one for 2D and one for 3D access).

So we're gonna have to start looking into this properly. 😂 I love it when multiple people independently hit the same problem — such a strong signal that it's worth fixing.

But @sofroniewn I agree that this particular change is just a hack. I'll try to think about it more carefully.

2021-03-25 05:56 UTC, jni commented
@sofroniewn thinking about this more, I have a couple of ideas to consider:

- add an optional `data3d` kwarg that is drawn from when in 3D view, or, better/more general:
- allow a data= to be a mapping of axes->data that lets you provide alternate data sources when accessing particular axis combinations to display. For exmaple, if `viewer.dims.displayed=(1, 2, 3)`, we display the 3D chunked data. If it's (0, 2, 3), it's actually better to display the 2D chunked data.
- (my least favourite, as I think it's a research project on its own) examine datasets for `.chunks` attributes and add complex logic to define which data is optimal to access based on chunking.

Any thoughts on these?

2021-03-25 07:54 UTC, joshmoore commented
> * ... examine datasets for `.chunks` attributes and add complex logic to define which data is optimal to access based on chunking.

Speaking only for OME-NGFF data, with the ["different downsamplings"](https://forum.image.sc/t/ome-ngff-combine-multiple-images-into-one-dataset/47619/9) I could imagine having any necessary metadata to aid this detection. But looking at the what the ome-zarr plugin is currently doing, I'd assume we'd want to provide a different return type that made the choice between 2D & 3D transparent.

2021-03-26 23:08 UTC, sofroniewn commented
I sort of feel like this should be the responsibility of the array library independent of napari, we should just be able to say give me this particular piece of nD data and it should figure out the best chunks to use to give it to us. The fact that the array libraries don't do this right now means it's probably a really hard problem which means to me it's one we shouldn't try and solve alone within napari (though we should be able to work well with another library that has solved it).

2021-06-21 06:42 UTC, jni commented
> I sort of feel like this should be the responsibility of the array library independent of napari, we should just be able to say give me this particular piece of nD data and it should figure out the best chunks to use to give it to us.

Thinking about this more, I don't think this is going to be true until we have a multiscale array API/spec, see #2803. Specifically, *we, napari,* request that users give us one array per scale, and then *we* decide which array to slice into. So it's currently impossible for users to give us a "smart array" that would optimally choose the best chunked version of the data based on a slice.

I'm starting to have some ideas about using `.chunks`/`.chunksize` to measure (a) the total data size and (b) the number of individual reads, for a given slicing operation. We can then make simple assumptions about IO latency + throughput to determine the optimal chunking strategy. It looks like we can do this in about 2µs, so it wouldn't be a problem to do this each time we slice or even each time we pan/zoom:

```python
In [1]: sizes = np.ones(10)                                                                                                                                                                   
In [2]: nchunks = 2 ** np.arange(10)                                                                                                                                                          
In [3]: %timeit sizes * 0.1 + nchunks * 0.00001                                                                                                                                               
1.93 µs ± 14.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

@DragaDoncila and I found out the hard way that the per-chunk access cost differs by 2 orders of magnitude between an SSD and an HDD, and I expect at least another 2 orders of magnitude for remote data, so basically we'd want different settings for each of those. That could be a manual setting on the layer (defaulting to SSD), and eventually something we auto-detect.

2021-10-28 11:05 UTC, closed without merging

2021-11-19 12:24 UTC, joshmoore commented
I keep running across this issue. Perhaps the upcoming work between zarr+xarray on https://github.com/pydata/xarray/issues/4118 might be an opportunity.

2021-11-19 18:16 UTC, sofroniewn commented
@jni do we need to reopen?

2021-11-21 00:15 UTC, jni commented
@sofroniewn Probably not this exactly. I need to work on #3560 (which will aim to establish something like the linked xarray issues for NumPy and dask arrays), then we can revisit what do do about 2D/3D chunking in #3554.

@joshmoore can you elaborate on why you keep running into this? Does OME-NGFF support non-decreasing sizes in multiscale? (ie I thought the 3D and 2D multiscale series were different series?)

2021-11-22 12:37 UTC, joshmoore commented
My apologies for the noise, all. It's not that I can running _into_ this _problem_ but _across_ this _issue_, as in its been in my browser and I keep wondering if something can be done. I assume I should jump into #3560.

> Does OME-NGFF support non-decreasing sizes in multiscale? (ie I thought the 3D and 2D multiscale series were different series?)

Currently each series must be monotonically decreasing, though I need to check the edge case of no decrease for one or more dimensions. And yes, 3D and 2D would be separate series at least as far as we've discussed it so far.