Add data setter for `surface` layers
napari/napari pull request #2544
Opened 2021-04-12 21:08 UTC by DragaDoncila

# Description
Add data setter for `surface` layer. 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Addresses the rest of #2354

# How has this been tested?

- [x] added test for changing data

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2021-04-12 22:18 UTC, sofroniewn approved these changes
Functionality LGTM! But I think we now use a new `trans._` syntax where we can pass the data as a second  arg, see https://github.com/napari/napari/blob/96d320c82af10db0e45edcb06b11020ea322f966/docs/guides/translations.md#additional-arguments-inside-strings.

This should fix the failing localization test

2021-04-12 22:50 UTC, goanpeca commented on napari/layers/surface/surface.py
> +                )
This should be

```python
trans._(
    'Surface data tuple must be 2 or 3, specifying'
    'vertices, faces, and optionally vertex values,'
    'instead got length {length}.'
    deferred=True,
    length=len(data),
)
```

More examples are available here @DragaDoncila 

https://napari.org/guides/stable/translations.html#deferred-translations

We use now deferred translations when raising errors :)

2021-04-12 22:51 UTC, goanpeca commented on napari/layers/surface/surface.py
> +                )
This should be

```python
trans._(
    'Surface data tuple must be 2 or 3, specifying'
    'vertices, faces, and optionally vertex values,'
    'instead got length {length}.',
    deferred=True,
    length=len(data),
)
```

Same here :)

2021-04-12 22:52 UTC, goanpeca requested changes
Added some comments on how we need to make `trans` use. For raising errors or warning we now use deferred translations.

https://napari.org/guides/stable/translations.html#deferred-translations

Also, we now are able to pass the kwargs to interpolated directly in trans, so no need to use format anymore.

2021-04-12 23:08 UTC, DragaDoncila commented
@goanpeca thanks for clarifying! I was just looking at that PR - very nice!

2021-04-12 23:18 UTC, goanpeca approved these changes
🚀

2021-04-13 08:16 UTC, kevinyamauchi reviewed
Amazing! I was just wishing the `Surface` layer had a `data` setter last night. Thanks!

2021-04-13 08:16 UTC, kevinyamauchi commented on napari/layers/surface/surface.py
> +        self._update_dims()
Should we emit a data event in the data setter? I think we do this in the other layers.

2021-04-13 08:18 UTC, DragaDoncila commented
@kevinyamauchi glad you like it! I think you're right, we probably should. Good catch!

2021-04-13 23:10 UTC, merged