PR: Add a POC for side bars
napari/napari pull request #2607
Opened 2021-04-23 04:43 UTC by goanpeca

# Description

Add an initial POC for sidebar implementation. This could be used for a couple of things:
- Add the help viewer to either side
- Move the plugin install/uninstall dialog to this place.

![sidebars](https://user-images.githubusercontent.com/3627835/115819448-73ffe600-a3c4-11eb-8492-bae05cde58ef.gif)

Any feedback is appreciated @napari/core-devs 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2021-04-23 15:52 UTC, sofroniewn commented
The sidebars look nice, and I'm very open to them - but I'm curious how others feel. Particularly when would we put something in a dock widget vs in a side bar? It's great to see this initial POC, but we might want to do some initial design work with @liaprins-czi to map out where things should go before committing to anything.

For example i could imagine that the layerlist/ layer control panel are actually in the sidebar and are one option, and the preferences is another. I'm not quite sure.

VScode does a nice job with their side panel and tabs, but i don't think they also have a dock widget concept

![image](https://user-images.githubusercontent.com/6531703/115897436-455c2c80-a411-11eb-8b78-311076a35188.png)

2021-04-23 16:17 UTC, goanpeca commented
>The sidebars look nice, and I'm very open to them - but I'm curious how others feel. Particularly when would we put something in a dock widget vs in a side bar? It's great to see this initial POC, but we might want to do some initial design work with @liaprins-czi to map out where things should go before committing to anything

Absolutely, I wanted to do this for some time and it turned out to be easy to do :) 

>For example i could imagine that the layerlist/ layer control panel are actually in the sidebar and are one option, and the preferences is another. I'm not quite sure.

Indeed I think those make sense there, except for the preferences (I think that deserves its own dialog space). I am particularly worried about the explosion of dockwidgets in the napari UI.

>VScode does a nice job with their side panel and tabs, but i don't think they also have a dock widget concept

Correct. I think we could have a brainstorming session on how we image this could be moving forward. There could also be the concept of layouts. 

This POC does not allow to move a dock into side panels, but it should be doable so we can play around with ideas also. Also now dockwidgets require an icon, but that is another thing.

2021-04-23 16:18 UTC, goanpeca commented
>Particularly when would we put something in a dock widget vs in a side bar?

This is a very important question that should have a clear and simple answer (if we have a clear idea on where we want to go or head)

2021-04-23 18:38 UTC, justinelarsen commented
@goanpeca This is cool! Thanks for starting this POC and discussion. 

I agree that we should have some rules for when something is in the sidebar vs dock widget and keep consistent. I think it makes sense to make something a dock widget if it's going to be regularly used in the context of the canvas. So the layer controls menu would definitely be useful as a dock widget. As I'm drawing on the canvas, it's nice to have it close by so that I don't have to move my mouse all the way to the side of the screen (see screenshot). For whether something should be in the side bars, it should probably be something that needs a lot of space. I could see this being a good area for layers, plugins and notifications. 

I would love to hear others' perspectives too!
<img width="1085" alt="Screen Shot 2021-04-23 at 11 28 16 AM" src="https://user-images.githubusercontent.com/57509887/115915241-e9e96900-a427-11eb-8d99-0ed7c8812252.png">

2021-04-23 20:55 UTC, DragaDoncila commented
I like the idea of moving away from dock widgets to a 'sidebar' approach. 

I think @justinelarsen's suggestion of thinking about what's used in the canvas is the correct approach for distinguishing between dock widgets and sidebars e.g. notifications do not require interaction with the canvas, so the notification log could go in a sidebar. I'm also thinking whether this is something we'd want for the progress bars as well, since this would give one click access to them and take up no additional area of the canvas - which I think is another huge benefit of the sidebar approach. Could also be where undo/redo history goes, once we have it.

I'm curious what people think about still providing the option of splitting into two sidebars. I can see wanting to always have access to the layers list *and* something else.

2021-04-26 12:16 UTC, jni commented
tbh, I actually disagree about the VSCode sidebar. I really kinda hate it. Some specific issues I have:
- it takes up a significant amount of screen width for functions that one uses quite rarely (e.g. the account manager icon, or the preferences). I know, it's not a lot, but I find that when trying to have windows side by side it makes the difference between seeing all my code and seeing it cropped at <80c.
- the questions above (what is a dock widget vs a panel vs in the sidebar) have not been suitably answered for VSCode. I really can see no logic to it.
- I *often* want to use two of the things in the sidebar together, specifically, use the file browser and the live share panel. The live share panel in particular is pretty small and it's just *so annoying* that it's tucked away in a sidebar panel that is incompatible with the debugging panel or the file browser.
- trying to guide novices around the sidebar is never easy, which points to some fundamental design issues imho.

I *am* excited about where we can go with this. Specifically, I've mentioned before (though I never created a dedicated issue, sorry about that! :bow:) that I think we should have a right sidebar-like thing for plugins that is an *endlessly scrollable space*, kind of like the main workflow view in Automator:

![automator](https://cdn.osxdaily.com/wp-content/uploads/2011/12/batch-resize-images-mac.jpg)

or the right sidebar in Pages:

![image](https://user-images.githubusercontent.com/492549/116080681-fd324980-a65e-11eb-8b4f-3e2c2892957e.png)

This means we can protect the dockable space of the viewer from plugin overload. We could maybe add functionality to *promote* plugins from the "plugin drawer" to the dockable space, for users who *always* want to launch napari with a specific plugin view.

I guess this is a long-winded way of saying I agree with @sofroniewn that we should have some major design discussion before jumping in with both feet here!

2021-04-26 12:46 UTC, goanpeca commented
>I guess this is a long-winded way of saying I agree with @sofroniewn that we should have some major design discussion before jumping in with both feet here!

Indeed that was precisely the point of the PR 😄 , to spark the conversation and hopefully land into a place where users will benefit form this.

2021-06-15 19:08 UTC, ppwadhwa requested changes
Testing, testing, 1,2,3

2021-06-15 19:09 UTC, ppwadhwa approved these changes
:)

2021-06-15 19:13 UTC, ppwadhwa reviewed
testing again.  :)

2021-11-16 05:03 UTC, sofroniewn commented
@goanpeca this was a very nice POC see, but I don't think we have any immediate plans to implementing something like this right away. Maybe the best thing to do now is to convert this PR into an issue, maybe include your first gif and any key points you want to capture and add a link to this PR. We can then close the PR and always reopen it or start a new one in the future. How does that sound?

2021-11-18 20:42 UTC, goanpeca commented
>How does that sound?

Sounds good!

2021-11-18 20:44 UTC, closed without merging