display file format options when saving layers
napari/napari pull request #2650
Opened 2021-05-03 21:30 UTC by ppwadhwa

# Description

Previously, there was no indication of what kind of file formats were available for saving layers.  This PR will add a drop down menu at the bottom of the QFileDialog that displays file format options.   Currently, I have just included image options and a points layer option (this one only includes csv and *).

If there are multiple layers, I just defaulted to *, because it saves it as a folder.  I need to decide how to handle each individual file type for multiple layers being saved.  

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2021-05-03 22:28 UTC, goanpeca commented on napari/_qt/qt_viewer.py
> +                ext_str = "All Files (*);; Image file types:;;" + ext_str
```suggestion
                ext_str = trans._("All Files (*);; Image file types:;;{ext_str}", ext_str=ext_str) 
```

2021-05-03 22:28 UTC, goanpeca commented on napari/_qt/qt_viewer.py
> +                ext_str = "All Files (*);; *.csv;;"
```suggestion
                ext_str = trans._("All Files (*);; *.csv;;")
```

2021-05-03 22:28 UTC, goanpeca commented on napari/_qt/qt_viewer.py
> +                ext_str = "All Files(*);;"
```suggestion
                ext_str = trans._("All Files(*);;")
```

2021-05-03 22:29 UTC, goanpeca commented on napari/_qt/qt_viewer.py
> +            ext_str = "All Files(*);;"
```suggestion
            ext_str = trans._("All Files(*);;")
```

2021-05-03 22:29 UTC, goanpeca requested changes
Thanks for working on this @ppwadhwa. Looks good. Needs internationalization :)

2021-05-04 01:07 UTC, ppwadhwa commented
thanks @goanpeca!  I committed all the suggested changes.  :)

2021-05-04 01:30 UTC, goanpeca commented
Need to run the pre-commit hooks now :)

2021-05-04 02:37 UTC, ppwadhwa commented
> Need to run the pre-commit hooks now :)

@goanpeca done.  thanks!

2021-05-06 21:42 UTC, goanpeca approved these changes
Thanks for working on this @ppwadhwa.

LGTM 🚀

2021-05-06 22:34 UTC, sofroniewn approved these changes
LGTM! I'd like to merge now so I can make the first `0.4.8rc0`, but we can make additional changes during the release process if necessary. Thanks!!

2021-05-06 22:34 UTC, merged