Emit data event when moving, adding or removing shapes or points
napari/napari pull request #2992
Opened 2021-07-07 23:28 UTC by DragaDoncila

# Description
This PR addresses the first part of the discussion in #2809 - emitting `data` events when a shape or point is added, removed or moved.

Points addition and removal is already handled by emitting in the `data` setter, as each of these methods assign the new data. I've added an event emitted on mouse release after a dragging event that involved moving, to ensure we only emit once per move. This required adding an `_is_moving` attribute (already present in the `Shapes` layer) to exclude emission on non-point-moving dragging events.  

`Shapes` layers only emitted `data` in the `data` setter. We now emit in the `add` and `remove_selected` methods, as well as on mouse release after a dragging event that involved moving. This is identical to the emissions in `Points`.

I was not able to find any tests checking events are emitted as expected, so I haven't added any. Is there a best approach for this? My only thought was simulating the events with `qtbot` and having implicit tests using `qtbot.waitSignal` with a timeout. @sofroniewn @jni does that seem useful?

I still think we should emit more information alongside the `data` event e.g. the type of event (add, remove or move) and the affected indices.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# References
Partially addresses #2809. 
Supersedes #2720.

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2021-07-12 00:00 UTC, jni requested changes
Summarising a private conversation with @DragaDoncila on Zulip:

- I really don't like that `layer._is_moving` is so completely non-local. It's set in the method but used in the mouse binding, and *reset* in the mouse binding. If one uses `layer._move` manually with the API, it won't get reset.
- @DragaDoncila pointed out that it's hard to throttle the events to only happen after mouse drag, rather than while dragging, which would be too many in most situations. Which is a good point!
- I proposed instead that events get emitted in the `._move` method, and then in the mouse binding we do `with layer.events.data.blocking():` while moving points while dragging, and then do a final, unblocked `layer._move()` call after dragging is finished.

At any rate, I'd prefer unthrottled events to having such non-local effects.

2021-07-12 00:18 UTC, DragaDoncila commented
@jni  I've made those changes for `Points` layer now. Want to have a look and see if you prefer that? It still feels kinda wrong to have that `_move` call with an empty list and coordinates...

2021-07-12 00:59 UTC, DragaDoncila commented
Just wanted to leave this code sample here as well in case someone wants to play with this:

```python
import napari
import numpy as np

PTS_COUNT = 0
SHAPES_COUNT = 0

def pts_event_handler(event):
    global PTS_COUNT 
    PTS_COUNT += 1
    print(f"POINTS EVENT EMITTED {PTS_COUNT}")


def shapes_event_handler(event):
    global SHAPES_COUNT
    SHAPES_COUNT += 1
    print(f"SHAPES EVENT EMITTED {SHAPES_COUNT}")

viewer = napari.Viewer()

points = np.array([[100, 100], [200, 200], [333, 111]])
size = np.array([10, 20, 20])
pts_layer = viewer.add_points(points, size=size, name='points')

# create a list of polygons
polygons = [
    np.array([[11, 13], [111, 113], [22, 246]]),
    np.array(
        [
            [505, 60],
            [402, 71],
            [383, 42],
            [251, 95],
            [212, 59],
            [131, 137],
            [126, 187],
            [191, 204],
            [171, 248],
            [211, 260],
            [273, 243],
            [264, 225],
            [430, 173],
            [512, 160],
        ]
    ),
    np.array(
        [
            [310, 382],
            [229, 381],
            [209, 401],
            [221, 411],
            [258, 411],
            [300, 412],
            [306, 435],
            [268, 434],
            [265, 454],
            [298, 461],
            [307, 461],
            [307, 507],
            [349, 510],
            [352, 369],
            [330, 366],
            [330, 366],
        ]
    ),
]

# add polygons
shapes_layer = viewer.add_shapes(
    polygons,
    shape_type='polygon',
    edge_width=1,
    edge_color='coral',
    face_color='royalblue',
    name='shapes',
)

pts_layer.events.data.connect(pts_event_handler)
shapes_layer.events.data.connect(shapes_event_handler)


napari.run()
```

2021-07-12 05:19 UTC, sofroniewn commented
> I do think not having the self._is_moving is a bit cleaner, since it keeps that separation between the mouse dragging and the actual moving code.

yup agreed! I like the diff much more as it is now. I think we use this in shapes, but maybe we can get rid of it there too. I much prefer things being local too.

I have not tried example yet, but code looks good to go for me!

2021-07-12 05:20 UTC, sofroniewn approved these changes

2021-07-14 05:13 UTC, jni approved these changes

2021-07-14 05:16 UTC, merged