Fix #3278
napari/napari pull request #3293
Opened 2021-08-30 22:20 UTC by lukasz-migas

This PR fixes #3278 where the canvas color was incorrectly being set during startup.

2021-08-30 22:31 UTC, Czaki commented
There is an option to add a test?

2021-08-30 22:32 UTC, lukasz-migas commented
Sure, will do.

2021-08-30 23:25 UTC, Czaki requested changes
Maybe a more generic version?

2021-08-30 23:25 UTC, Czaki commented on napari/_qt/_tests/test_qt_viewer.py
> +@pytest.mark.parametrize("theme", ("light", "dark"))
```suggestion
@pytest.mark.parametrize("theme", available_themes())
```

2021-08-30 23:25 UTC, Czaki commented on napari/_qt/_tests/test_qt_viewer.py
>  from napari.utils.io import imread
```suggestion
from napari.utils.io import imread
from napari.utils.theme import available_themes
```

2021-08-31 16:52 UTC, sofroniewn approved these changes
LGTM!

2021-08-31 16:53 UTC, merged