Convert tooltip text to rich text
napari/napari pull request #3417
Opened 2021-09-25 05:47 UTC by ppwadhwa

# Description

Tooltips text is not wrapped automatically.  It will be wrapped if converted to rich text first.  This PR will create an event filter that will globally convert any tooltip text to rich text.  The code was borrowed from this comment here:  https://stackoverflow.com/a/46212292

Closes #3096

2021-09-27 17:44 UTC, goanpeca approved these changes
Thanks @ppwadhwa ! LGTM 🚀

2021-09-27 17:45 UTC, goanpeca commented on napari/_qt/qt_event_filter.py
> +                raise ValueError(f'QObject "{widget}" not a widget.')
I missed this @ppwadhwa, need to add translation to this :) 

Example

```python
                raise LookupError(
                    trans._(
                        "Could not find a dock widget containing: {widget}",
                        deferred=True,
                        widget=widget,
                    )
                )
```

2021-09-27 17:45 UTC, goanpeca requested changes
Minor translation fix

2021-09-27 19:15 UTC, goanpeca approved these changes

2021-09-27 22:46 UTC, Carreau commented
Warning,  using code from Stackoverflow is not BSD compliant, I recently had to redo some code in IPython as it was from borrowed from stackoverflow (`https://github.com/ipython/ipython/issues/13039` in backticks to not cross links).

This can make companies using BSD code + SO snippets to fail audits

At least if you borrow it, don't say it in the docstring or the commit message.

If you want to really be safe, you can look at the SO code, write a human description of the critical steps to take, or API to use, and ask someone else to write the code reading only your description.

I'm not going to oppose to this being merged, or us using some. But I am not a lawyer, and I would prefer that this is approved by someone from CZI.

2021-09-27 22:48 UTC, Carreau requested changes
I think someone on the project management should +1 if it's ok to use code from SO and saying so.

Feel free to dismiss my review asking for change if you believe that's ok.

2021-09-28 03:15 UTC, sofroniewn commented on napari/_qt/qt_event_filter.py
> +        https://stackoverflow.com/a/46212292
```suggestion
        This code is used from https://stackoverflow.com/a/46212292 under CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
```

2021-09-28 03:24 UTC, ppwadhwa commented
@Carreau thanks for bring that up!  I certainly don't want to do anything wrong.  And thanks @sofroniewn for updating the reference for the code.  I committed the change.  :)

2021-09-28 03:34 UTC, sofroniewn reviewed
@Carreau thanks for the tips around the SO code. It looks like they are CC BY-SA 4.0 (see [SO license info](https://stackoverflow.com/help/licensing)), which leaves some ambiguities, see this [blog post for some discussion](https://empirical-software.engineering/blog/so-snippets-in-gh-projects). I think at least we should update the attribution text as I mentioned above (thanks for already merging @ppwadhwa).

Since writing above, I've been doing some more reading now around BSD + CC BY-SA 4.0, it definitely seems the SA clause leads to additional complexity here, I could ask around for some more opinions, but your first hand experience means that regardless at least some people the situation is messy enough that they don't want to use it.

Maybe @ppwadhwa can rewrite, the used functionality isn't so long - most of what is copied is comments. As long as it is rewritten you can still add the SO link under "for more information see SO", but I might just do that in a comment rather than doc string.

What does @jni think here?

2021-09-28 05:00 UTC, Carreau commented
I agree that it's a bit of a gray area, I don't believe it is of too much importance in this specific case as the spirit of CC-BY-SA and BSD are not that far from each other. Two things:

1) I would avoid an actual link, automatic scanners will find it and report false positive, I would phrase it as something along "Stack Overflow answer 46212292"
2) If we ever have to do the same for more contagious licenses (e.g. GPL), we may need the person writing the code to not have laid eyes on the original one. At least that the gold standard in many legal reverse engineering (think linux driver for nvidia, one person does reverse engineering write spec, and another write from the spec).

I actually was in an internship defence less than a month ago where the student was asked to justify that his work was BSD when he compared it to the R implementation (GPL), and how he could not be influenced by looking at the R code, so from my POV it seem like the consideration for the legal ramification of licenses are becoming more frequent.

2021-09-28 06:06 UTC, jni commented
Wow. I'm actually shocked that SO code is CC-BY-SA. I 100% had assumed it's BSD/MIT-like/public-domain.

By my reading we should follow @Carreau's advice here. And this certainly increases my threshold for looking at SO if I'm stuck on something. Which is a shame.

btw I haven't looked at any of the code here so if someone wants to write that english description I can volunteer to implement.

2021-09-28 06:13 UTC, jni commented
Another idea: I think CC-BY-SA is closest to MPL in terms of spirit: you should share code and derivative code under a similar license, but *using* such code does not infect the rest of your code base the same way that GPL does. Therefore, I wonder whether projects could "save" themselves by distributing all their SO code snippets in a single CC-BY-SA-licensed file in the repo. Thoughts @Carreau?

2021-09-28 16:16 UTC, Carreau commented
> And this certainly increases my threshold for looking at SO if I'm stuck on something. Which is a shame.

Yeah, it is tough,  This is one of the reason I also changed my way of writing stackoverflow answers, with a more verbose human readable explanation and minimal code.

> Therefore, I wonder whether projects could "save" themselves by distributing all their SO code snippets in a single CC-BY-SA-licensed file in the repo. Thoughts @Carreau?

Yeah, that's one possibility, with one gotcha which is that depending on the date on the answer it might be a different CC-BY-SA version; so we might need separate files.

But something like the `vendor` directory sounds good.

2021-09-28 20:27 UTC, ppwadhwa commented
are we putting this in the vendor directory then?  

I also wrote up some directions if you want to implement @jni .  Either way.  

1. create evenfilter class that inherits from QObject
2. Overwrite eventFilter function that accepts widget and event.  returns a bool
3. check that the event type is a QEvent.ToolTipChange
4. If value for widget is not a QWidget, raise a ValueError
5. check that the tooltip on the widget is not empty and is not already rich text (Qt.mightBeRichText(tooltip))
         a . convert the plain text tooltip--  escape all HTML syntax in tooltip, then add qt specific tags around text. <qt>
         b.  set the new tooltip 
6. if the if statement is not entered---make sure to return super().eventFilter(widget, event)

2021-09-29 03:40 UTC, sofroniewn commented
> I also wrote up some directions if you want to implement @jni . Either way.

Thanks for writing that up

> Yeah, that's one possibility, with one gotcha which is that depending on the date on the answer it might be a different CC-BY-SA version; so we might need separate files.

Yeah we could do that. I'd be fine with this approach

> are we putting this in the vendor directory then?

I think so, seems like a fine thing to do for now, and then we can revisit if needed

2021-09-30 23:16 UTC, ppwadhwa commented
I moved `event_loop_filter.py` to `_vendor/events/` directory.  Let me know if this works.  thanks!

2021-10-01 00:14 UTC, sofroniewn commented on napari/_vendor/events/qt_event_filter.py
> +        https://stackoverflow.com/a/46212292
```suggestion
        This code is used from https://stackoverflow.com/a/46212292 under CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
```

2021-10-01 00:21 UTC, sofroniewn approved these changes
@tlambert03 if you did want to read the english language description and do a quick re-write it might be nice, the more i look at the CC-BY-SA the larger headache merging this feels like, see posts like https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code.

I'd probably say just make a new PR with our own implementation and then we'd close this one.

Sorry for being on the fence about this one. But might as well fix this now rather than kick the can down the road.

2021-10-01 17:45 UTC, goanpeca commented
I followed Pam's instructions simplify it a bit and this came out https://github.com/napari/napari/pull/3442

Thanks @ppwadhwa for working on this! 🚀 

Closing

2021-10-01 17:45 UTC, closed without merging