adds citation file
napari/napari pull request #3470
Opened 2021-10-13 04:21 UTC by neuromusic

# Description

adds a `CITATION.cff`-formatted citation file to the napari repo. 

this standard format will enable

- Github to render "How to cite" on the sidebar
- Zenodo will read this file to populate authors, etc in the "official" archived version of each release

citation generated from current zenodo metadata, using the [doi2cff](https://doi2cff.readthedocs.io/en/latest/) command line utility

## Type of change

housekeeping/documentation

# References

closes #1004

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2021-10-13 04:28 UTC, neuromusic commented on CITATION.cff
> +- given-names: Nicholas
@sofroniewn can you review your name & affiliation?

2021-10-13 04:28 UTC, neuromusic commented on CITATION.cff
> +- given-names: Talley
@tlambert03 can you review your name & affiliation?

2021-10-13 04:28 UTC, neuromusic commented on CITATION.cff
> +- given-names: Kira
@kne42 can you review your name & affiliation?

2021-10-13 04:28 UTC, neuromusic commented on CITATION.cff
> +- given-names: Juan
@jni can you review your name & affiliation?

2021-10-13 04:29 UTC, neuromusic commented on CITATION.cff
> +- given-names: Grzegorz
@Czaki can you review your name & affiliation?

2021-10-13 04:29 UTC, neuromusic commented on CITATION.cff
> +- given-names: Philip
@pwinston can you review your name & affiliation?

2021-10-13 04:29 UTC, neuromusic commented on CITATION.cff
> +- given-names: Gonzalo
@goanpeca can you review your name & affiliation?

2021-10-13 04:29 UTC, neuromusic commented on CITATION.cff
> +- given-names: Kevin
@kevinyamauchi can you review your name & affiliation?

2021-10-13 04:29 UTC, neuromusic commented on CITATION.cff
> +- given-names: Matthias
@Carreau can you review your name & affiliation?

2021-10-13 04:30 UTC, neuromusic commented on CITATION.cff
> +- given-names: Draga
@DragaDoncila can you review your name & affiliation?

2021-10-13 04:33 UTC, neuromusic commented on CITATION.cff
> +- given-names: ACS
@AhmetCanSolak can you review your name & affiliation?

2021-10-13 04:33 UTC, neuromusic commented on CITATION.cff
> +- given-names: ziyangczi
@potating-potato can you review your name & affiliation?

2021-10-13 04:34 UTC, neuromusic commented on CITATION.cff
> +- given-names: Pam
@ppwadhwa can you review your name & affiliation?

2021-10-13 04:34 UTC, neuromusic commented on CITATION.cff
> +- given-names: alisterburt
@alisterburt can you review your name & affiliation?

2021-10-13 04:34 UTC, neuromusic commented on CITATION.cff
> +- given-names: Genevieve
@GenevieveBuckley can you review your name & affiliation?

2021-10-13 04:34 UTC, neuromusic commented on CITATION.cff
> +- given-names: Andy
@andy-sweet can you review your name & affiliation?

2021-10-13 04:34 UTC, neuromusic commented on CITATION.cff
> +- given-names: Lukasz
@lukasz-migas can you review your name & affiliation?

2021-10-13 04:47 UTC, sofroniewn commented on CITATION.cff
> +  affiliation: CZI
```suggestion
  affiliation: Chan Zuckerberg Initiative
```

2021-10-13 04:48 UTC, sofroniewn commented on CITATION.cff
> +- given-names: Nicholas
Name looks good, I suggested expanding CZI to Chan Zuckerberg Initiative

2021-10-13 04:56 UTC, DragaDoncila commented on CITATION.cff
> +  name-particle: Doncila
```suggestion
- given-names: Draga
  family-names: Doncila Pop
```

2021-10-13 04:57 UTC, DragaDoncila commented on CITATION.cff
> +- given-names: Draga
@neuromusic looks fine, just tweaked the family names - had to look up what a `name-particle` was so TIL!

2021-10-13 06:42 UTC, lukasz-migas commented on CITATION.cff
> +- given-names: Lukasz
That looks good to me! 👍

2021-10-13 07:16 UTC, Czaki requested changes

2021-10-13 07:16 UTC, Czaki commented on CITATION.cff
> +  affiliation: University of Warszaw, CeNT
```suggestion
  affiliation: University of Warsaw, Faculty of Mathematics, Informatics, and Mechanics
```

2021-10-13 09:55 UTC, jni commented on CITATION.cff
> +- given-names: Juan
It's good!

2021-10-13 10:06 UTC, alisterburt commented on CITATION.cff
> +  family-names: ''
```suggestion
- given-names: Alister
  family-names: Burt
  affiliation: MRC-LMB
```

2021-10-13 10:06 UTC, alisterburt commented on CITATION.cff
> +  family-names: ''
thanks @neuromusic - hope this looks right!

2021-10-13 10:21 UTC, kevinyamauchi commented on CITATION.cff
> +- given-names: Kevin
Looks good to me! Thanks, @neuromusic !

2021-10-13 13:54 UTC, neuromusic commented on CITATION.cff
> +- given-names: Kevin
thank you!

2021-10-13 13:59 UTC, tlambert03 commented on CITATION.cff
> +  affiliation: Harvard University
```suggestion
  affiliation: Harvard Medical School
```

2021-10-13 14:05 UTC, neuromusic commented on CITATION.cff
> +- given-names: Draga
oh wow, fascinating! yeah, this was what the `doi2cff` tool generated from the zenodo entry

2021-10-13 14:05 UTC, neuromusic commented on CITATION.cff
> +- given-names: Lukasz
awesome! thanks!

2021-10-13 14:07 UTC, neuromusic commented on CITATION.cff
> +- given-names: alisterburt
thanks!

2021-10-13 14:07 UTC, neuromusic commented on CITATION.cff
> +- given-names: Grzegorz
thanks!

2021-10-13 14:07 UTC, neuromusic commented on CITATION.cff
> +- given-names: Talley
thanks!

2021-10-13 15:03 UTC, andy-sweet commented on CITATION.cff
> +  family-names: Sweet
```suggestion
- given-names: Andrew
  family-names: Sweet
  affiliation: Chan Zuckerberg Initiative
```

Probably makes sense to be consistent about the CZI affiliation across all contributors. Probably Chan Zuckerberg Initiative like @sofroniewn suggested, or maybe CZI or @chanzuckerberg.

2021-10-13 15:41 UTC, goanpeca commented on CITATION.cff
> +- given-names: Gonzalo
Yes sir!

2021-10-13 15:41 UTC, goanpeca approved these changes

2021-10-13 15:54 UTC, sofroniewn approved these changes

2021-10-13 15:59 UTC, pwinston commented on CITATION.cff
> +- given-names: Philip
- given-names: Philip
  family-names: Winston
  affiliation: Tobeva Software

2021-10-13 16:08 UTC, sofroniewn commented
> adds a CITATION.cff-formatted citation file to the napari repo.

@neuromusic are there recommendations on best practices to keep this file up to date over time? Also did you use a tool to autogenerate this initial one. Apologies if I missed link, but would be great to have, at least for historical record.

Awesome to get this going though. There's a lot of momentum in the community to make software citation easier and it's great to see napari joining in too!!

2021-10-13 17:52 UTC, liu-ziyang commented on CITATION.cff
> +- given-names: ziyangczi
Given name: Ziyang
Family name: Liu
Affiliation: Chan Zuckerberg Initiative Foundation

2021-10-13 18:42 UTC, liu-ziyang commented on CITATION.cff
> +  affiliation: '@chanzuckerberg'
```suggestion
- given-names: Ziyang
  family-names: Liu
  affiliation: Chan Zuckerberg Initiative Foundation
```

2021-10-13 18:59 UTC, Czaki requested changes

2021-10-13 18:59 UTC, Czaki commented on CITATION.cff
> +  affiliation: University of Warsaw, Faculty of Mathematics, Informatics, and Mechanics
```suggestion
- given-names: Grzegorz
  family-names: Bokota
  affiliation: University of Warsaw, Faculty of Mathematics, Informatics, and Mechanics
  orcid: https://orcid.org/0000-0002-5470-1676
```

2021-10-13 19:00 UTC, Czaki commented
I think that it may be worth adding also orcid https://citation-file-format.github.io/

2021-10-13 22:35 UTC, neuromusic commented
> @sofroniewn: did you use a tool to autogenerate this initial one.

yes: https://doi2cff.readthedocs.io/en/latest/ to generate the CFF file from the Zenodo DOI

> are there recommendations on best practices to keep this file up to date over time? 

I'm not sure... this author list was automatically generated by Zenodo... apparently with metadata from Github re: contributors to the git history (which does not include contributors to documentation or other repos like the plugin engine).

Once this PR lands, zenodo will begin to rely on this file instead of generating the citation (and author list) automagically... so you are exactly right that there will need to be some additional work to ensure that new contributors are included in the author list. This will probably mean more process and possibly a mechanism to include contributors who aren't represented in the author list b/c their contributions have been non-code, like @liaprins-czi  #3420 might be relevant here.

2021-10-14 03:10 UTC, sofroniewn commented
> yes: https://doi2cff.readthedocs.io/en/latest/ to generate the CFF file from the Zenodo DOI

thanks!!

> there will need to be some additional work to ensure that new contributors are included in the author list. 

we could try and update/ regenerate before every release if easy/ automated

> This will probably mean more process and possibly a mechanism to include contributors who aren't represented in the author list b/c their contributions have been non-code, like @liaprins-czi #3420 might be relevant here.

agreed, thanks for including link here too

2021-10-24 00:45 UTC, sofroniewn commented
Looks like this is coming together nicely. Maybe @neuromusic you and I can do a final clean up pass through this and get this in. I don't think it's urgent, but might as well keep it moving along. Would be nice to get a few more approvals from @napari/core-devs just to make sure everyone is on board with this approach before merge too!! Certainly i'd like an approval from @jni

2021-10-24 02:51 UTC, tlambert03 approved these changes

2021-10-24 02:51 UTC, tlambert03 commented on CITATION.cff
> +version: 0.4.11
i assume this is something we need to manually bump?

2021-10-24 15:11 UTC, neuromusic commented on CITATION.cff
> +version: 0.4.11
yes. 

looks like it could be dropped? https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md

or is there other tooling the project is using to keep version info sync'd?

2021-10-24 15:14 UTC, neuromusic commented on CITATION.cff
> +- given-names: Volker
@VolkerH can you review your name & affiliation?

2021-10-24 15:15 UTC, neuromusic commented on CITATION.cff
> +- given-names: Lorenzo
@brisvag can you review your name & affiliation?

2021-10-24 15:15 UTC, neuromusic commented on CITATION.cff
> +- given-names: Jordão
@JoOkuma can you review your name & affiliation?

2021-10-24 15:15 UTC, neuromusic commented on CITATION.cff
> +- given-names: Jaime
@jaimergp can you review your name & affiliation?

2021-10-24 15:15 UTC, neuromusic commented on CITATION.cff
> +- given-names: Hector
@hectormz

2021-10-24 15:15 UTC, neuromusic commented on CITATION.cff
> +- given-names: Jeremy
@freeman-lab can you review your name & affiliation?

2021-10-24 15:15 UTC, neuromusic commented on CITATION.cff
> +- given-names: Peter
@boonepeter can you review your name & affiliation?

2021-10-24 15:16 UTC, neuromusic commented on CITATION.cff
> +- given-names: Alan
@quantumjot can you review your name & affiliation?

2021-10-24 15:16 UTC, neuromusic commented on CITATION.cff
> +- given-names: Christoph
@cgohlke can you review your name & affiliation?

2021-10-24 15:16 UTC, neuromusic commented on CITATION.cff
> +- given-names: Loic
@royerloic can you review your name & affiliation?

2021-10-24 15:16 UTC, neuromusic commented on CITATION.cff
> +- given-names: Andrea
@kir0ul can you review your name & affiliation?

2021-10-24 15:16 UTC, neuromusic commented on CITATION.cff
> +- given-names: Hagai
@HagaiHargil can you review your name & affiliation?

2021-10-24 15:16 UTC, neuromusic commented on CITATION.cff
> +- given-names: Abigail
@AbigailMcGovern can you review your name & affiliation?

2021-10-24 15:20 UTC, brisvag commented on CITATION.cff
> +  affiliation: '@gutsche-lab'
Your comment was a bit off-line, so I'm making a new one:
```suggestion
- given-names: Lorenzo
  family-names: Gaifas
  affiliation: Gutsche Lab - University of Grenoble
```

2021-10-24 17:55 UTC, VolkerH commented on CITATION.cff
> +- given-names: Volker
The name "Volker Hilsenstein" is correct.
Current affiliation: 
EMBL Heidelberg, Germany

Thanks Justin!

2021-10-24 18:45 UTC, hectormz commented on CITATION.cff
> +  affiliation: AMDI
```suggestion
- given-names: Hector
  family-names: Muñoz
  affiliation: University of California, Los Angeles
```

2021-10-24 18:45 UTC, hectormz commented on CITATION.cff
> +- given-names: Hector
added a new comment for suggested change!

2021-10-24 18:50 UTC, HagaiHargil commented on CITATION.cff
> +  family-names: Har-Gil
```suggestion
  family-names: Har-Gil
  affiliation: Tel Aviv University, Israel
```

2021-10-24 19:26 UTC, kir0ul commented on CITATION.cff
> +- given-names: Andrea
It would be:
```yaml
- given-names: Andrea
  family-names: Pierré
  affiliation: Brown University
```
Thanks @neuromusic!

2021-10-24 23:15 UTC, boonepeter commented on CITATION.cff
> +- given-names: Peter
Looks good thanks!

2021-10-24 23:23 UTC, GenevieveBuckley commented on CITATION.cff
> +- given-names: Genevieve
Looks good to me! 
While technically Dask is my affiliation for 11 months in 2021, I was at Monash before and after that, and for longer periods of time - so I think this is fine.

2021-10-24 23:46 UTC, Czaki commented
Why there is not attached orcid to persons?

2021-10-25 00:14 UTC, JoOkuma commented on CITATION.cff
> +- given-names: Jordão
It's correct.

2021-10-25 07:16 UTC, quantumjot commented on CITATION.cff
> +- given-names: Alan
Looks good.

2021-10-25 22:19 UTC, jaimergp commented on CITATION.cff
> +- given-names: Jaime
LGTM! Thanks!

2021-10-26 08:44 UTC, brisvag commented on CITATION.cff
> +- given-names: Lorenzo
Done in a separate comment.

2021-10-28 23:49 UTC, neuromusic commented
> Why there is not attached orcid to persons?

It's not automated, so individuals will need to add them

2021-10-29 01:11 UTC, tlambert03 commented on CITATION.cff
> +  affiliation: Harvard Medical School
```suggestion
  affiliation: Harvard Medical School
  orcid: "https://orcid.org/0000-0002-2409-0181"
```

😛

2021-10-29 02:11 UTC, GenevieveBuckley commented on CITATION.cff
> +  affiliation: Monash University
```suggestion
  affiliation: Monash University
  orcid:  https://orcid.org/0000-0003-2763-492X 
```

2021-10-29 02:12 UTC, GenevieveBuckley commented on CITATION.cff
> +  affiliation: Monash University
Turns out I have an ORCID and used it exactly once in my life

2021-10-29 03:51 UTC, sofroniewn commented on CITATION.cff
> +  affiliation: Chan Zuckerberg Initiative
```suggestion
  affiliation: Chan Zuckerberg Initiative
  orcid: "https://orcid.org/0000-0002-3426-0914"
```

2021-11-01 04:59 UTC, hectormz commented on CITATION.cff
> +  affiliation: University of California, Los Angeles
```suggestion
- given-names: Hector
  family-names: Muñoz
  affiliation: University of California, Los Angeles
  orcid: https://orcid.org/0000-0001-7851-2549
```

2021-11-02 08:52 UTC, brisvag commented on CITATION.cff
> +  affiliation: Gutsche Lab - University of Grenoble
```suggestion
- given-names: Lorenzo
  family-names: Gaifas
  affiliation: Gutsche Lab - University of Grenoble
  orcid: https://orcid.org/0000-0003-4875-9422
```

2021-12-23 01:20 UTC, sofroniewn commented
This is looking great @neuromusic - it would be great to push it over the finish line. Is there stuff that I or @andy-sweet could do to help, either with cleaning up affiliations or the zenodo integration? Is this also something where we could merge the affiliations and then do the zenodo integration in a follow up PR. Thanks!!

2021-12-23 01:27 UTC, jni commented
Another Q @neuromusic: do we have a plan for keeping this up to date? Perhaps we need to add this to the reviewer checklist, so that any first-time contributor is prompted to add themselves to the list?

2021-12-23 10:00 UTC, Carreau commented on CITATION.cff
> +  affiliation: '@Quansight-Labs'
```suggestion
  affiliation: '@Quansight-Labs'
  orcid: "http://orcid.org/0000-0002-7636-8632"
```

2021-12-23 12:55 UTC, brisvag commented
> Another Q @neuromusic: do we have a plan for keeping this up to date? Perhaps we need to add this to the reviewer checklist, so that any first-time contributor is prompted to add themselves to the list?

We could even have a CI workflow on PRs that fails a new contributor is not in there...

2021-12-23 15:10 UTC, neuromusic commented on CITATION.cff
> +version: 0.4.11
dropped the version info & switched to zenodo's "concept" DOI so that this doesn't need to be kept up to date

2021-12-23 15:25 UTC, neuromusic commented
OK, a couple of updates...

- I believe affiliations are up to date & accurate

once this PR is merged, Zenodo will refer to this file as the "source of truth" for everything in the file. anticipating this, I've made a couple of changes:

- I changed the DOI to reference Zenodo's "Concept" DOI instead of a DOI associated with a specific release
- I dropped references to "release date"

as for maintaining this going forward, yes, @jni, this will require some additional process to make sure that new contributors are added to this list, either as part of the PR review process or release process. a CI workflow sounds awesome @brisvag , however, this file doesn't maintain either emails or Github handles, so it may be hard to reconcile whether a contributor is in this list or not.

2021-12-23 15:31 UTC, neuromusic commented
related to forward maintenance, the author ordering here is what zenodo automatically generated which I think corresponds to volume of contributions in some way (either lines of code or commits? idk.)

curious @jni @sofroniewn what the right author ordering is for the napari community...
- how should the current list be ordered?
- where in the list would a new author be placed?

also, this author list is based on contributions to this repository, which would include documentation, examples, etc.

do contributions to related repositories warrant inclusion as authors here? thinking `napari.github.io`, `npe2`, `magicgui`, etc?

2022-03-27 04:41 UTC, sofroniewn commented
Great questions here @neuromusic and my apologies for missing that the ball here was in @jni and my court

> the author ordering here is what zenodo automatically generated which I think corresponds to volume of contributions in some way (either lines of code or commits? idk.)
>
> curious @jni @sofroniewn what the right author ordering is for the napari community...
>
> how should the current list be ordered?
> where in the list would a new author be placed?

i'd be fine sticking with zenodo's default for now to get this merged, but i'm not sure about maintenance 

> also, this author list is based on contributions to this repository, which would include documentation, examples, etc.
>
> do contributions to related repositories warrant inclusion as authors here? thinking napari.github.io, npe2, magicgui, etc?

these are also great questions.

I suggest we merge now and then adopt some process for adding people and reordering based around major releases

2022-03-27 04:43 UTC, sofroniewn commented on CITATION.cff
> +message: If you use this software, please cite it using these metadata.
```suggestion
message: If you use this software, please cite it using these metadata.
```

2022-03-27 04:43 UTC, sofroniewn reviewed
Trying to trigger a re-run of the manifest check

2022-03-27 04:44 UTC, sofroniewn commented on CITATION.cff
> +message: If you use this software, please cite it using these metadata
```suggestion
message: If you use this software, please cite it using these metadata.
```

2022-04-20 00:21 UTC, sofroniewn commented
@jni is this good to go from your perspective? Can we merge? Test fails are unrelated. I think it would be great to get this in as a start and then press on from there!!

2022-04-21 00:43 UTC, jni commented
I agree, let's iterate as we go. Thanks @sofroniewn!

2022-04-21 01:25 UTC, sofroniewn commented
Thanks @jni 

@neuromusic I'll merge this tomorrow morning unless I hear otherwise from you or someone else 🚀

2022-04-21 07:59 UTC, brisvag commented
For a future PR: would it make sense to add a step to the CI to check if all git authors in history are added in some form? I guess this only works if at least emails are the same though.

2022-04-22 04:20 UTC, sofroniewn commented
> For a future PR: would it make sense to add a step to the CI to check if all git authors in history are added in some form? I guess this only works if at least emails are the same though.

yeah i think we need to think about how we keep this list up to date and maybe how we verify it every release. we should probably create a follow up issue to track that discussion. i will merge now though as this is still a great start!!

2022-04-22 04:20 UTC, merged