Ignore precision loss warnings from thumbnails
napari/napari pull request #355
Opened 2019-06-20 17:51 UTC by kevinyamauchi

# Description
This PR ignores the precision loss warnings from skimage when converting the thumbnail image to uint8.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References
This is a temporary fix for #349 until skimage 0.16 is released.

# How has this been tested?
- [ ] `/examples/add_image.py`
- [ ] `/examples/labels-2d.py`

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2019-06-20 18:02 UTC, sofroniewn requested changes
I think I'd rather do this when we import the `Viewer` but just catch this specific warning as otherwise we'll need to do this in all the individual layers.

See how we catch the vispy warning in the main init right now https://github.com/napari/napari/blob/764b7473a05c8545fb28b233df48938d256b489b/napari/__init__.py#L5

does @kne42 have thoughts?

2019-06-20 18:56 UTC, kevinyamauchi commented
I am totally fine to do it that way @sofroniewn as long as there aren't going to be cases where we want to let the warning through.  I can't think of any at the moment, so I am happy to catch the warning at `Viewer` import unless anybody has other suggestions.

2019-06-21 00:31 UTC, jni commented
> as long as there aren't going to be cases where we want to let the warning through

those warnings are going to go away altogether very soon, so I don't think any such cases are relevant. =)

2019-06-27 18:40 UTC, kevinyamauchi commented
I looked into this a bit more and I don't think we can suppress the warning on import as we do with the vispy error in `Viewer` because the warning is generated when the thumbnail is generated. Thus, I propose the following:

1. Move the `img_as_ubyte()` conversion present in each individual layer's thumbnail into the setter method of the `thumbnail` property in the base `Layer`. 
2. Catch the warning in the `Layer.thumbnail` setter.

I think this satisfies your intent @sofroniewn, as we don't have to chase down the warnings in each layer. Thoughts?

2019-06-27 18:43 UTC, sofroniewn commented
That's a great suggestion @kevinyamauchi - much cleaner to have all the conversions in the base class anyway. I say go ahead and implement

2019-06-27 20:19 UTC, kevinyamauchi commented
Sounds good. I think I'll make a clean branch then implement.

2019-06-27 23:13 UTC, kevinyamauchi commented
Implemented the above suggestion in #370.

2019-06-27 23:13 UTC, closed without merging