Add menubar to napari main window
napari/napari pull request #356
Opened 2019-06-21 07:13 UTC by jni

# Description
Eventually, this menu will contain all the options we want out of napari, including file opening, adding plugins, and running plugins. For now, I leave it turned off for the programmatically-launched viewer, so this shouldn't affect functionality in any way, except adding the ability to toggle it on.

This is motivated by parallel work on https://github.com/napari/napari-app, where I'd like napari to behave like a native app, with a proper menubar.

As you'll see in the code, when the menubar is hidden, none of its shortcuts are active, which is annoying, but I didn't find a workaround. Suggestions most welcome!

I also don't know what this does on macOS (menubars shouldn't be hidden on mac, since the main menubar is always visible), so testing would also be appreciated! If the menubar items disappear when setting the menubar to invisible, I might favour adding a check to keep it always on on mac.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2019-06-21 16:51 UTC, sofroniewn commented
Nice explorations @jni

I'm going to create an issue where we can discuss what belongs in the napari-app repo vs what belongs in the main napari repo and on the programaticly created Viewer. I know we've gone back and forth on some this stuff (like CLI) etc, and I was recently talking about this with @kne42, so having one central place to discuss it will probably be worth it, and while I see this as firmly `0.2` and after SciPy, it could become a high priority after the conference, so developing a plan now is probably worth it too

2019-06-24 01:04 UTC, jni commented
@sofroniewn would you be able to test what happens on mac with this branch when the menubar is hidden?

2019-06-25 14:37 UTC, sofroniewn requested changes
Somethings not quite working right on the mac. I can't tell the difference between toggling `hide_menubar` and I'm not quite sure what the expected behavior there is / why we'd ever need / want to hide the menubar. When I launch the viewer now I get the screen bellow

![image](https://user-images.githubusercontent.com/6531703/60107270-7ab36880-971b-11e9-9063-ece0fa09ad77.png)

The worst problem though is right now I'm unable to open any of the drop downs after I launch napari, my clicks are just ignored on the menubar. However if I toggle focus to another application, like chrome, and then come back to napari the menubar works. This was true for the very limited menubar that appeared before this PR as well (though it was less important then). I havn't looked into debugging yet, but can poke around

2019-06-26 05:13 UTC, jni commented
Thanks for testing, @sofroniewn!

> I can't tell the difference between toggling hide_menubar 

That is kinda sorta what I expected on Mac. The point is that macOS has a permanent menubar that changes based on application focus. (Side note: macOS is the only OS that does this right, based on sound UI theory. Specifically, the borders of the screen are effectively "infinite-size" targets for moving the mouse, because you can move the mouse "past" the border and it just sits there; This makes it the most useful real estate on your screen, so something useful should live there. On Windows and Linux, most of it is wasted on window chrome.) On Windows and Linux, though, the menubar sits *inside* the application, so toggling it makes sense. Here's what this looks like on Linux:

![napari-menubar](https://user-images.githubusercontent.com/492549/60152596-6a3ae500-9824-11e9-90e8-9ac04ba17685.png)

> The worst problem though is right now I'm unable to open any of the drop downs after I launch napari

That sounds unrelated to this PR since it happened earlier. A quick search turned up e.g. [this](https://github.com/robotology/yarp/issues/457) among many other hits. I haven't yet read through the related threads to figure out the solution.

Of course we also want to set the menubar application menu on mac to say "napari" instead of "python".

Side note: did you fix your double titlebar, @sofroniewn???

2019-06-26 05:38 UTC, jni commented
Also, incidentally, given the above look (which will be mimicked by Windows), what do people think about having it there by default? I think it makes sense when napari is launched as a standalone, but less so when it's launched in a script, which is why I've designed it the way I have (default hidden, but shown when launched in `main()`), but am totally open to different views.

2019-06-26 14:48 UTC, sofroniewn commented on napari/main.py
> +from skimage import io
do we want to use `imageio` here instead? we currently depend on both libraries so could go either way

2019-06-26 14:50 UTC, sofroniewn commented on napari/main.py
> +        images = io.ImageCollection(args.images, conserve_memory=False)
if someone passes no images can you launch the empty viewer? Fine if you want to wait on this till future PRs (say when we add drag / drop capability), but also maybe nice just to get it in now

2019-06-26 14:54 UTC, sofroniewn commented
@jni - we got rid of the double titlebar with this line which is ignored if not on mac https://github.com/napari/napari/blob/db969b976ec34b18915ee49081aa2a8440cf225d/napari/components/_window/view.py#L26

If you can set the menubar application menu on mac to say "napari" instead of "python" can you do that in this PR?

I feel like the menubar should always be there by default - even on windows / linux regardless of how the app is launched. I'd rather people see it so they know the functionality is there and then hide it if they don't want to see it anymore vs. maybe missing it entirely and not knowing about it. I also think its a little strange to see in the code something this `hide_menu = True` on the mac but then still see the menubar at the top of my screen - though your explanation made sense. Finally I don't really like the idea of people seeing different "versions" of napari depending on how napari gets launched, even if it's just what the default settings are.

CLI works great - I'm looking forward to adding drag-drop!!!

2019-06-30 07:45 UTC, jni commented
@sofroniewn 

> we got rid of the double titlebar with this line which is ignored if not on mac 

Great! But did you ever figure out why you suffered from this and no one else did? Some default setting in your Qt was different for some reason? I wonder if some other qt software you installed modified some global config variable somewhere?

2019-06-30 18:00 UTC, sofroniewn commented
@jni - no didn't figure it out. as discussed in #239 the furthest progress i was able to make was figuring out that creating a new user got rid of that problem.

For this PR am I right in thinking the remaining things to do are
- [ ]  remove the `hide_menu = True` keyword arg and make the menubar shown by default
- [ ] make sure `napari` can be launched from the CLI with no keyword args
- [ ] add file open to the menubar that opens an image / collection of images the same way that the CLI does

2019-06-30 22:20 UTC, sofroniewn commented
In parallel, I can work on exploring the drag and drop functionality so that after this PR is merged it will be quick to make a followup exposing drag and drop, only support the same file types that can be read with file open & the CLI

2019-07-01 03:25 UTC, jni commented
@sofroniewn the other thing that I'm wanting help with is that the standard keyboard shortcut for hiding/showing the menubar, on Linux at least, is just tapping "alt" by itself, but I haven't found a way to make this work. If you or @kne42 have any ideas, let me know. For now we can go with Ctrl-M, or maybe Ctrl-B since Ctrl-M is usually maximise or minimise (I forget which LOL) on macOS.

2019-07-01 07:58 UTC, jni commented
@sofroniewn I've finished the items on your to-do list! =)

2019-07-01 15:00 UTC, sofroniewn approved these changes
Amazing work @jni - I love this so much. Works great, it's so much fun just to browse around opening images!! Choice of `ctrl-M` is fine with me. I'm approving and will merge today

2019-07-01 15:26 UTC, merged