Add test for new large labels when in contour mode
napari/napari pull request #3768
Opened 2021-12-08 05:16 UTC by jni

# Description

I went through the trouble of creating a reproducible test case for [this imagesc post](https://forum.image.sc/t/data-specific-reason-for-indexerror-in-raw-to-displayed/60808) before realising that @Czaki had already fixed the issue in #3697 :joy: so I figured why waste a nice test case. :blush:

2021-12-10 02:59 UTC, sofroniewn approved these changes
LGTM!

2021-12-10 03:01 UTC, sofroniewn requested changes
Too fast! @jni can you move this test inside `napari/_tests` if you need to use `make_napari_viewer` or can you just make a labels layer if you want it to live here. Our headless tests are failing because of this one

2021-12-10 23:17 UTC, jni commented
Iiinteresting! I saw the failure but didn't know how to interpret it. We should probably add this info (and a bunch of other stuff) to https://napari.org/developers/testing.html

Anyway, will update, thanks for the review! 😊

2021-12-10 23:37 UTC, tlambert03 commented
> Too fast! @jni can you move this test inside napari/_tests if you need to use make_napari_viewer or can you just make a labels layer if you want it to live here.

even better, just test `ViewerModel` if you don't need the Qt part of it

2021-12-10 23:51 UTC, goanpeca commented on napari/layers/labels/_tests/test_labels.py
> +    [2]: https://github.com/napari/napari/pull/3697
So lovely to put nicely formatted references @jni 😍

2021-12-10 23:52 UTC, goanpeca commented on napari/layers/labels/_tests/test_labels.py
> +    viewer.dims.set_point(axis=0, value=4)
Do we need to assert something, or just that no error is raised?

In that case a comment could help :)

2021-12-10 23:55 UTC, goanpeca reviewed
🚀

2021-12-14 03:11 UTC, jni commented
@sofroniewn I think my latest update will fix things... 🤞

2021-12-14 03:45 UTC, sofroniewn approved these changes
LGTM! All tests passing now, thanks!!

2021-12-14 03:45 UTC, merged