Rename app_context gui_qt
napari/napari pull request #392
Opened 2019-07-05 06:53 UTC by jni

# Description

Fixes #369 

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2019-07-05 16:55 UTC, sofroniewn requested changes
Nice @jni, one minor fix and then one request.

- [x] The minor fix is for some reason `app_context` didn't get replaced inside `examples/set_colormaps.py` and so that test is failing

- [x] The request is to expose `gui_qt` at the `napari` level and not just `napari.util` level and make all the usage in our examples either
```python
from napari import Viewer, gui_qt
with gui_qt():
    Viewer()
```
 or 
```python
import napari
with napari.gui_qt():
    napari.Viewer()
```
I think a mix of those two is fine, or you can just pick one, but regardless I think this is cleaner and simpler than having to go into `napari.util` every single time

2019-07-06 15:50 UTC, sofroniewn commented
If I remember correctly @jni you are on the airplane today (and tomorrow ?!) so I took the liberty of making the changes I requested above and moving the `event_loop.py` into our `_qt` folder. I also updated the readme.md. I think it's quite nice now and will merge after the tests pass, if there's anything you don't like we can easily revisit it this week

2019-07-06 15:51 UTC, sofroniewn approved these changes

2019-07-06 15:58 UTC, merged

2019-07-06 16:59 UTC, jni commented
Thanks for finishing this up @sofroniewn! Indeed I'm currently in the air between LAX and AUS! See you when you get in! =) I'm +/-1 about putting gui_qt in there (it is definitely a utility rather than core functionality), but I can live with it. =)