Contrast limits popup fix
napari/napari pull request #4122
Opened 2022-02-18 15:48 UTC by grlee77

# Description
Updates a few things related to the contrast slider pop
1.) Hides "full range" button for signed integers (it does nothing in this case)
2.) Increase button size slightly to avoid truncated text as in the screenshot [here](https://github.com/napari/napari/issues/4112#issue-1142147690)

needs discussion as possibly more controversial:
3.) Change "reset" button behavior to reset to the user-provided contrast limits
e.g. with a layer added via `layer.add_image(image_uint8, contrast_limits=(64, 128))`, reset would restore the range to [64, 128] rather than [0, 255].

## Type of change
mostly bug fix, but item 3 above is a behavior change

# References
closes #4112

# How has this been tested?

- [ ] TODO: add test case for item 3 if we want to go that route

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2022-02-18 15:49 UTC, grlee77 commented
Picture of the slider for signed integer dtype after this PR:
![contrast_slider_signed_fixed](https://user-images.githubusercontent.com/6528957/154715594-61aec4ab-7916-4b49-9ffa-ebe11909583d.png)


And for the unsigned case:
![contrast_slider_unsigned_fixed](https://user-images.githubusercontent.com/6528957/154715613-14885530-e189-4011-8fd7-2508061e746e.png)

2022-02-18 15:51 UTC, grlee77 commented
On a related note, I did also take a look at adding an option to `superqt` to switch to scientific notation on the labels past a certain maximal integer or float range. It works now, but still needs a little more polishing in terms of size/spacing

2022-02-18 15:54 UTC, grlee77 commented
The bundle failure here is due to #4117

2022-02-19 00:17 UTC, sofroniewn approved these changes
I like these changes - make sense to me - but maybe @tlambert03 wants to weigh in too before merge. Agreed - test fails are unrelated

2022-02-20 22:08 UTC, tlambert03 commented
generally looks good, but as mentioned over in https://github.com/napari/napari/issues/4112#issuecomment-1046041853

I don't think we want the "reset" button to always go back to whatever it received in the `__init__`.   One of the primary usages for that button was the case where the image wasn't loaded properly to begin with, and you'd like to restore it to the min/max of the image.  The current behavior mimics the "reset" button in Fiji's brightness and contrast (which is essentially an autoscale button).  This new behavior would be very confusing to a lot of GUI users

2022-02-20 22:09 UTC, tlambert03 requested changes
requesting reversion on the initial contrast limits  as described in comments

2022-02-20 22:11 UTC, tlambert03 commented
@grlee77, if you found the word "reset" to be confusing.  There I'd definitely agree with you.  The word was originally chosen for parity with the button of the same name in Fiji... but I never really liked it.  So, if you think "auto-contrast" (like the label in the image controls) would have been clearer, I'd certainly be ok with that

2022-02-20 23:32 UTC, sofroniewn commented
> The current behavior mimics the "reset" button in Fiji's brightness and contrast (which is essentially an autoscale button). This new behavior would be very confusing to a lot of GUI users

Ok yeah, good point

2022-02-21 00:32 UTC, jni commented
@tlambert03 @sofroniewn following the discussion, but since @tlambert03 you already added auto-contrast buttons outside of the sliders popup, perhaps this new reset behaviour is a nice thing to have? To me it certainly makes sense to have a button to undo whatever mess I've made with the contrast limits :joy:

2022-02-21 14:56 UTC, tlambert03 commented
> perhaps this new reset behaviour is a nice thing to have? To me it certainly makes sense to have a button to undo whatever mess I've made with the contrast limits 😂

I can imagine the concept potentially being useful.  but I think it has a high degree of possibility for confusion.
1. it kind of conflates programatic usage with GUI usage i.e. it's a GUI button that resets something to something a programatic user did which will, in many cases, be hidden from the gui user ... such as a plugin that sets contrast limits.  I imagine having to explain the behavior to someone: "It will reset to whatever the reader plugin set it to." ... "how do I know what that was?" ... "check `layer.source` and potentially the private `layer._initial_contrast_limits` attribute" ... "how do I check that?" ... oh, you have to use code.  Whereas currently we just say "it will set to the min/max of the data".  Which is very easy to explain, deterministic regardless of plugin, and similarly undoes your mess.
2. There's not much of a "prior" for that behavior in other programs such that a user would immediately understand what it was doing.  So I think the button would need to be labeled something much more self-explanatory than "reset".

Anyway, I'm not opposed to the general idea.  but I think it's a whole new concept that we can't just introduce like this without some more discussion

2022-02-21 15:12 UTC, grlee77 commented
> 1. it kind of conflates programatic usage with GUI usage

Yeah, that is a pretty solid reason. IIRC, the main issue with the current behavior when I was testing was that it works well for `uint8`/`uint16` but for general `int` will give you an extremely large range so that the image appears all black. Larger ints are probably a more niche use case, though. I would guess uint8, uint16 or floating point types are by far the most common.

2022-02-21 15:15 UTC, tlambert03 commented
> uint8/uint16 but for general int will give you an extremely large range so that the image appears all black

the "full range" button should do that, but the "reset" button shouldn't do that.  It should always scale to the data itself.  Are you certain it wasn't the full-range button?

The reset button will do that in a dataset-dependent way if there is one or two super-bright pixels, but the rest of the data is in the low end of the dynamic range).  For that though, we should implement percentile scaling (where calc_data_range ignores the top/bottom N% of the histogram)

2022-02-21 18:35 UTC, grlee77 commented
> the "full range" button should do that, but the "reset" button shouldn't do that. It should always scale to the data itself. Are you certain it wasn't the full-range button?

Yes, that was incorrect. I remember now that the problem I had with "reset" was in a case where the array was sufficiently large that the range was determined from a small subset of the data rather than the full thing. That is a desirable feature in general for large datasets, it just happened that the artificial data I was using wasn't well sampled by the current choice of subset used to determine the range. That is a separate issue from this PR though!

I agree that in general a percentile-based range is helpful. I often used to display datasets with something like ``range =  np.percentile(data, q=[0.5, 99.5])``. And then optionally expanding that slightly (e.g. ``range = [0.9*range[0] - 1.1 * range[1]]``). It was pretty common in MRI data to have something like a blood vessel show up multiple times brighter than the other tissues, so it was helpful to automatically exclude this from the range calculation.

2022-02-21 18:46 UTC, grlee77 commented
So should we close this PR or modify to do something else for items 1, 3 at top?

The issues seem to be:

- item 1: rather than remove the button for signed integers, have it do something else for them instead?
      what would you suggest this be? There is already "reset" to get the data range.

- item 2: increasing button size may make things look worse on some platforms (I can check on MacOS and compare). If so, I should revert that. (It may only look bad on my Ubuntu system because "Large Fonts" is enabled in the system settings)

- item 3: let's revert the change to "reset" behavior. As mentioned since providing those `contrast_limits` is only via code and not the GUI, we should perhaps have a function to restore initial contrast via code instead?

2022-02-21 19:23 UTC, tlambert03 commented
well the thing from #4112 that I thought was the best point was that there's no reason we can't also support signed integers in addition to unsigned.  So, rather than changing `if np.issubdtype(layer.dtype, np.integer)` to `if np.issubdtype(layer.dtype, np.unsignedinteger):` in image_controls_base... why don't we just improve the `reset_contrast_limits_range` method in `intensity_mixin` to also accept signed integers.

(I'm also fine with the slight bump to the button width

2022-02-22 00:17 UTC, grlee77 commented
Okay, I reverted the "reset" button behavior change and updated "full range" to work for signed integer dtypes. The button size increase has been left as-is.

2022-02-22 00:26 UTC, grlee77 commented
One remaining issue is that for int32 or larger the editable edge labels on the slider in the popup are [capped at range +/- 9999999](https://github.com/napari/superqt/blob/96de1a261a6eeac4319eb27302c4a62975ef8f6e/src/superqt/sliders/_labeled.py#L540-L541). So one can set "full range" for those large integers and the slider works fine over the full range as returned by `np.iinfo`, but you cannot manually type in values outside of the +/- 9999999.

2022-02-25 13:47 UTC, tlambert03 approved these changes
thanks!

2022-02-25 13:47 UTC, merged