Update napari pin for conda/mamba install in constructor bundle
napari/napari pull request #4220
Opened 2022-03-08 16:43 UTC by goanpeca

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2022-03-08 17:06 UTC, potating-potato approved these changes

2022-03-08 23:20 UTC, jni commented
@goanpeca I'd love better description here, including why this improves/fixes #4214... The beautiful description from that PR is now gone!

2022-03-08 23:32 UTC, jni requested changes
@goanpeca I'd love better description here, including why this improves/fixes https://github.com/napari/napari/pull/4214... The beautiful description from that PR is now gone!

2022-03-08 23:36 UTC, goanpeca commented
@jni I updated the [description](https://github.com/napari/napari/pull/4220#issue-1162880675) and a comment in code.

Thanks!

2022-03-09 00:09 UTC, jni approved these changes

2022-03-09 00:36 UTC, merged