Minor copy update: Usage page
napari/napari pull request #4278
Opened 2022-03-17 17:23 UTC by tdimino

# Description
Simply clarifying that _in-depth explanations_ will be geared more toward advanced users. Also omitted the mention that tutorials and guides can be found below, as they're now only accessible from the side nav. 

## Type of change
- [ ] This change requires a documentation update

2022-03-18 04:54 UTC, jni approved these changes
Thank you!

2022-03-18 09:56 UTC, tlambert03 requested changes
I don't really love "advanced users" over "those".  "Those" lets the reader decide if it's right for them based on content, "advanced users"  excludes potential readers.

2022-03-20 02:42 UTC, DragaDoncila approved these changes
LGTM!

2022-03-20 04:28 UTC, tlambert03 approved these changes

2022-03-20 04:28 UTC, merged