Recenter 0-axis when adding a new image layer
napari/napari pull request #4361
Opened 2022-04-06 12:08 UTC by psobolewskiPhD

# Description
I've added a check if a new layer is an ImageLayer and if so, set the 0-axis to the mid-point of the 0-axis of the new layer. For RGB or 2D image layers the 0-axis is set to 0.
This is a fix for https://github.com/napari/napari/issues/4350
Importantly, this makes the right-click Projections JustWork and if the underlying 3D layer is deleted the 2D image is visible.

(I think an argument can be made for doing a `reset_view()` as well, but this isn't *always* desired, so I didn't implement that.)

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
- Related to: https://github.com/napari/napari/pull/3859
Here the recentering was disabled after the first layer, but for images I think it makes sense to add it.
- Closes #4350 

# How has this been tested?
- [x] added a test based on https://github.com/napari/napari/pull/3859
- [x] all `test_viewer_model` tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2022-04-07 23:45 UTC, jni requested changes
@psobolewskiPhD Thanks for the proposed fix, but to be honest, I don't like it. Although this makes projections work, it will be very annoying behaviour in most other contexts. For example:

- add an image layer
- navigate around to an area of interest
- run a processing function such as a gaussian filter
- now the view snaps back to the middle and you have lost the place you were browsing

I ran into this many times when we first added reset to middle, and it's extremely frustrating. Therefore, I suggest we close this and we move forward with the behaviour fixes I proposed in #4350.

2022-04-08 05:58 UTC, psobolewskiPhD commented
I'm fine with any solution 😄 

> For example:
> 
> * add an image layer
> * navigate around to an area of interest
> * run a processing function such as a gaussian filter
> * now the view snaps back to the middle and you have lost the place you were browsing

This shouldn't happen with the PR?
It doesn't happen for me using pyclesperanto anyways. If the new, processed image is the same dims it shouldn't move the slider.
Unless of course you are adding a single 2D image with the blur of your single slice...but then in the live napari you will keep your place, but you won't see the new image—if you're adding a new image doesn't that imply you want to view it? 🤣 

I've been tripped up so many times by the behavior, but only recently realized what was happening: there was nothing wrong with my images, they simply were not displayed because all images/stacks share the same slider—and it's linked—even if different lengths. This is super when say two layers share z/t-axis info, but pretty annoying otherwise, which happens to be common for me:
Typically a control has 60 images from the same well, while a sample is a subset of the well area, so it may just have 5-12 images. So if I open the 60-stack first, then the smaller stack, it appears like nothing was loaded—even the thumbnail is empty.

2022-04-08 07:35 UTC, jni commented
>  Typically a control has 60 images from the same well, while a sample is a subset of the well area, so it may just have 5-12 images. So if I open the 60-stack first, then the smaller stack, it appears like nothing was loaded—even the thumbnail is empty.

Do the images share the same space at all? ie should they even be layers in the same viewer? To me it sounds like you should be using two viewers here.

Here's a minimap-like idea: if you add a new dataset that only lives in part of the slider, *flash* that part of the slider when the layer gets added. What do you think?

2022-04-08 07:36 UTC, jni commented
We could also add a "recenter" button. I just don't want to be moved around without being asked. :joy:

2022-04-08 07:55 UTC, psobolewskiPhD commented
> Do the images share the same space at all? ie should they even be layers in the same viewer? To me it sounds like you should be using two viewers here.

Being able to quickly compare density and morphology by toggling the vis of the top layer is not something I'd want to give up.

>We could also add a "recenter" button. I just don't want to be moved around without being asked.

A button to `reset_view()` is not a terrible idea...

2022-04-08 08:05 UTC, jni commented
> Being able to quickly compare cell density and morphology by toggling the vis of the top layer is not something I'd want to give up.

I find this [very amusing](https://xkcd.com/1172/) :joy: But fair enough! I think between the slider flashing and the button (probably I would just make `reset_view()` also reset the sliders, thoughts?) we can satisfy your use case...!

2022-04-08 09:11 UTC, psobolewskiPhD commented
Maybe I'm not getting proper use of napari? 🤷 
But for me the one-window many-layer model is much more intuitive than many scattered open windows—it's one of the main things that drove me to using napari in the first place! 
If I want side by side I can use grid view? 
I'm a simpleton: many-viewers to me duplicates too much UI elements and just confuses me. 
Part of it is that I have a 13" monitor, so many windows can get overwhelming.
Anyhow, feel free to close this. Just for the sake of learning, I fixed your gaussian blur example 😄 Recenter only when 0-axis is smaller... I'll probably just use my branch locally for the time being...

Flashing the slider is fine.
In the end I guess it comes down to preference: when I add an image I want to see it!

2022-04-08 12:10 UTC, brisvag commented
> If I want side by side I can use grid view?

I think this is tghe real answer. However, grid view is kinda broken right now for anything above 2D. The generated ransforms do not account for axis order, so things get messed up if you roll axes. Should be fixable, but needs some work.

2022-04-08 13:00 UTC, jni commented
> Maybe I'm not getting proper use of napari? :shrug: 
> But for me the one-window many-layer model is much more intuitive than many scattered open windows—it's one of the main things that drove me to using napari in the first place!

Sorry, I didn't mean to disparage your use case, I just thought it was funny because I don't think I'd ever considered it! :sweat_smile: Indeed avoiding window proliferation was definitely one of the early design constraints of napari! I just always viewed all the layers as implicitly sharing the same physical space.

> If I want side by side I can use grid view?

Grid view is indeed for side by side, but @sofroniewn and I have often had conversations where we discussed a "real" grid *of canvases* for datasets that aren't really meant to be "on top" of each other. In this case each element of the grid would have its own set of sliders and you would not be able to go outside the bounds any of the individual datasets. What would you think of this?

But anyway, one of the cool things about napari is that it's hackable, and you've hacked it to suit your use case, and that's awesome. :tada: 

@psobolewskiPhD how do you normally launch napari? One clean/non-branchy way to do this is to add a callback to `viewer.layers.events.inserted` that does the view resetting you're after.

I wonder whether we could support an "event callbacks" hook for plugins... :thinking: @tlambert03 any thoughts on this?

2022-04-08 13:19 UTC, psobolewskiPhD commented
> @psobolewskiPhD how do you normally launch napari?

It depends? I'd say a mix of using VS Code notebooks/interactive windows, so launching from there—this would be to visualize some analysis output.
But often—and as I'm getting more comfortable with the Napari Console—I launch from the terminal and primarily interact with the GUI plus console. The `aicsimageio-napari` scene selector is something I use a lot to open my LIF and screen different images—with different shapes—for further analysis. Sometimes to make mosaics, sometimes to pick frames/locations for analysis (substacks), etc. So I run into this issue a lot in my normal use.
I also use this mode for a lot of show-and-tell, to quickly show someone some image or to show how cool napari is—I've embarrassed myself once with the black screen and confusion.

2022-04-08 23:34 UTC, sofroniewn commented
I'm also inclined not to change the slice location like this when adding an image but to look for other solutions to #4350.

As to the other stuff about grid mode - it does sounds like what is desired is true multicanvas support

2022-04-10 00:45 UTC, jni commented
Ok, I've made a few issues to track some of the ideas we've raised here (see links above). In the meantime I'll close this one. Hopefully we can support your use case well soon @psobolewskiPhD!

2022-04-10 00:45 UTC, closed without merging