honor confirm close settings when quitting
napari/napari pull request #4700
Opened 2022-06-15 17:09 UTC by tlambert03

# Description
We need to have a way to quit napari without having to confirm every time (particularly when there's nothing to save anyway, but in general: if I have selected in the settings not to confirm on close, it shouldn't confirm on close).  If a follow up PR is desired that adds a separate setting to differentiate between command W and command Q, that's fine.  But there needs to be a preference.

2022-06-15 17:18 UTC, goanpeca reviewed
Is there a way to know napari is running inside a notebook or as a standalone app or from terminal so that this does not apply when inside a notebook?

Would that solve the use cases?

---

I agree the setting should work for Quit as well!

2022-06-15 17:21 UTC, tlambert03 commented
> Would that solve the use cases?

regardless of the environment, there needs to be a preference. 
I just ran 
```
import napari
viewer=  napari.Viewer()
```
in a notebook, hit command Q, then reran the code cell multiple times without a problem.
Is this the more general issue of command-Q in a browser fighting with browser command Q?  If so, I don't think that's a napari issue

2022-06-15 17:22 UTC, tlambert03 commented
> Is there a way to know napari is running inside a notebook

btw, this is at `napari.utils.misc.in_jupyter`

2022-06-15 17:30 UTC, Czaki commented
I strongly prefer to have this as separate settings or have option to select one of three options:

1. Always ask,
2. Ask on application to close
3. Newer ask. 

It is possible to add one of these options to this PR? If no then string in settings needs to be updated to informal that it will also not also on application close.

2022-06-15 17:30 UTC, alisterburt approved these changes
no debate IMO - if there's a pref this should be respected and configurable!

edit: separate pref is also valid, would approve that too :)

2022-06-15 17:31 UTC, tlambert03 commented
> It is possible to add one of these options to this PR? If no then string in settings needs to be updated to informal that it will also not also on application close.

I'll update the string here,  That additional stuff can go in a new PR if you want it, but I agree with @goanpeca  that it feels odd

2022-06-15 17:31 UTC, goanpeca commented
Pressing the `x` on the title of the application should also prompt or not (based on the preference) also. That seems to be broken from the previous PR.

2022-06-15 17:32 UTC, tlambert03 commented
string updated

2022-06-15 17:34 UTC, Czaki commented on napari/settings/_application.py
> +            "Ask for confirmation before closing a napari window.",
```suggestion
            "Ask for confirmation before closing a napari window or application (all napari windows).",
```

2022-06-15 17:34 UTC, Czaki commented on napari/settings/_application.py
>          title=trans._("Confirm window closing"),
```suggestion
        title=trans._("Confirm window or application closing"),
```

2022-06-15 17:36 UTC, Czaki commented
@haesleinhuepf as your issue was the reason for the first PR it will be nice if you could comment here.

2022-06-15 17:37 UTC, goanpeca requested changes
This is not working for the close button in the application title bar.

![napari](https://user-images.githubusercontent.com/3627835/173890515-9a830da0-a381-4e95-ae04-57e8d533c314.gif)

2022-06-15 17:49 UTC, tlambert03 commented
> This is not working for the close button in the application title bar.

is that specific to this PR?  or is that a problem with #4637 ?

2022-06-15 17:53 UTC, goanpeca commented
>is that specific to this PR? or is that a problem with https://github.com/napari/napari/pull/4637 or something that has generally always been there?

I don't know, but it should work 🙃

2022-06-15 17:55 UTC, goanpeca approved these changes
@tlambert03mMaybe the `x` fix can be done in a separate PR, to address the immediate needs :)

So approving (but we do need that fixed in a separate one!)

2022-06-15 18:07 UTC, Czaki commented
> This is not working for the close button in the application title bar.

for me, confirmation could be also removed when the user uses the file menu to close the window or app. But I do not know how to distinguish between shortcuts (that may be clicked accidentally) and selection from the menu.

2022-06-15 18:08 UTC, tlambert03 commented
>@tlambert03mMaybe the x fix can be done in a separate PR, to address the immediate needs :)
> So approving (but we do need that fixed in a separate one!)

yeah, just played with this a bit... I _think_ all the logic needs to move to `_QMainWindow.closeEvent` ... but I'll let @Czaki determine what is best there in a followup

2022-06-15 18:10 UTC, goanpeca commented
>yeah, just played with this a bit... I think all the logic needs to move to _QMainWindow.closeEvent .

Yes, this should not depend at all if it was triggered by a shortcut or by a menu.

2022-06-15 20:16 UTC, Carreau commented
It does seem to split the time, in https://github.com/napari/napari/runs/6905352240?check_suite_focus=true the total tox time is 11:41 in this one it's 2:18+8:28, so I do seem to see the split.

2022-06-16 04:45 UTC, jni approved these changes

2022-06-16 04:48 UTC, jni commented
I agree with @tlambert03 that the window close icon and/or the file menu not respecting the preference were existing issues, and can be fixed in a follow-up.

I also agree with @Czaki, though, that those are less critical to fix — they are much less likely to be hit accidentally. So I'm actually 50/50 on whether they should respect the preference or just do the thing. Happy to be swayed either way.

2022-06-16 10:00 UTC, merged