Add option to edit second shortcut in settings
napari/napari pull request #5018
Opened 2022-09-05 21:19 UTC by Czaki

# Description

add the option to edit the second shortcut in settings. Preserve multiple shortcuts if edit (currently delete second one)

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

closes #5016

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

This is the only draft with a known problem that shortcuts order may change after restarting napari, and sometimes a shortcut is overwritten instead of added next. 

I open it to get initial feedback. @psobolewskiPhD ?

2022-09-05 21:25 UTC, psobolewskiPhD commented
Works quite nice! 
At first I didn't notice the second column, because I was focused on the shortcut I wanted to change. But once I realized I needed to click over to the right, it worked perfectly!
It's too late now for me to think of the UI part, but even as-is this is a major QoL improvement.

2022-09-05 21:48 UTC, Czaki commented
> damn that codecov shit with all the warnings is annoying when trying to read the code...)

if I good remember, `a` is toggling showing codecov warnings. 

> BTW looks like you check the other layers for conflicts?

Do you think about this from reading code, or from app behavior? It should only validate in one layer type.

2022-09-05 21:50 UTC, psobolewskiPhD commented
> Do you think about this from reading code, or from app behavior? It should only validate in one layer type.

From trying to read the code...but with all those warnings, obviously it didn't go well. It's also too late for me I think, maybe my jetlagg is lifting?
Anyhow, I promise to play around with this more tomorrow.

2022-09-06 06:49 UTC, psobolewskiPhD commented on napari/utils/_tests/test_action_manager.py
>      assert action_manager._shortcuts['napari:test_action_1'] == set()
```suggestion
    assert action_manager._shortcuts['napari:test_action_1'] == []
```

2022-09-06 08:10 UTC, psobolewskiPhD commented
Ok, I've been playing around.
Works great!
With this PR can close this https://github.com/napari/napari/issues/3926
(return cmd/control for Fill)!

My only catch has been that the modifier keys require a double-click in the field to assign, vs. a single click sufficient for letters. 
Unrelated to this PR, I'm not sure how to clear/unassign a keybind 👀

2022-09-06 08:18 UTC, Czaki commented
> I'm not sure how to clear/unassign a keybind eyes

one of reasons why this is still draft

2022-09-06 08:22 UTC, psobolewskiPhD commented
> > I'm not sure how to clear/unassign a keybind eyes
> 
> one of reasons why this is still draft

Gotcha, I will say that on live the behavior is the same regarding clearing keybinds.

2022-09-06 13:02 UTC, Czaki commented
it looks like some bug from another part of the code was triggered, as I do not see a place where my code was touched before the segfaulted test.

2022-09-06 21:30 UTC, Czaki commented
@psobolewskiPhD did you find a time today?

2022-09-07 08:21 UTC, psobolewskiPhD commented
@Czaki 
The Plugins interface works really well!
Small visual question would be a clearer indication where the click zone is for the 2nd shortcut. Or perhaps center the shortcuts in the columns?

I did hit one glitch: I set the following, plus Viewer keybding `Viewer reset scroll.` (no idea what that does):
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/76622105/188828004-877ef43f-7c71-4d9e-9547-b1b03e448026.png">

Then I got an IndexError when making a new Labels layer in empty Viewer.
Traceback:
<details>
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~/Dev/napari/napari/_qt/widgets/qt_viewer_buttons.py:76, in QtLayerButtons.__init__.<locals>.<lambda>()
     56 self.newPointsButton = QtViewerPushButton(
     57     'new_points',
     58     trans._('New points layer'),
   (...)
     62     ),
     63 )
     65 self.newShapesButton = QtViewerPushButton(
     66     'new_shapes',
     67     trans._('New shapes layer'),
   (...)
     71     ),
     72 )
     73 self.newLabelsButton = QtViewerPushButton(
     74     'new_labels',
     75     trans._('New labels layer'),
---> 76     lambda: self.viewer._new_labels(),
        self.newLabelsButton = <napari._qt.widgets.qt_viewer_buttons.QtViewerPushButton object at 0x16526a4c0>
        self = <napari._qt.widgets.qt_viewer_buttons.QtLayerButtons object at 0x16526a040>
        QtViewerPushButton = <class 'napari._qt.widgets.qt_viewer_buttons.QtViewerPushButton'>
        trans = <napari.utils.translations.TranslationBundle object at 0x11cc457c0>
        self.viewer = Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.015, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(226.10837757094214, 247.29064387933107), scaled=True, size=10, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 2.0, 1.0), (0.0, 2.0, 1.0)), current_step=(0, 0), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Labels layer 'Labels' at 0x137630df0>], scale_bar=ScaleBar(visible=False, colored=False, color=<class 'numpy.ndarray'> (4,) float32, ticks=True, position=<Position.BOTTOM_RIGHT: 'bottom_right'>, font_size=10.0, box=False, box_color=<class 'numpy.ndarray'> (4,) float32, unit=None), text_overlay=TextOverlay(visible=False, color=<class 'numpy.ndarray'> (4,) float32, font_size=10.0, position=<TextOverlayPosition.TOP_LEFT: 'top_left'>, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=<napari.utils.transforms.transforms.Affine object at 0x137954e50>, transform_drag=<napari.utils.transforms.transforms.Affine object at 0x137954d90>, transform_final=<napari.utils.transforms.transforms.Affine object at 0x137954d60>, transform=<napari.utils.transforms.transforms.Affine object at 0x137954ca0>, allow_new_selection=True, selected_vertex=None)), help='', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='system', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_move at 0x14a4aa670>], mouse_drag_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_drag at 0x14a497670>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x1267d1ee0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Shift': <function InteractionBoxMouseBindings.initialize_key_events.<locals>.hold_to_lock_aspect_ratio at 0x14a497940>, 'Control-Shift-R': <function InteractionBoxMouseBindings._reset_active_layer_affine at 0x14a4260d0>, 'Control-Shift-A': <function InteractionBoxMouseBindings._transform_active_layer at 0x14a426160>})
     77 )
     79 layout = QHBoxLayout()
     80 layout.setContentsMargins(0, 0, 0, 0)

File ~/Dev/napari/napari/components/viewer_model.py:334, in ViewerModel._new_labels(self=Viewer(axes=Axes(visible=False, labels=True, col...indings._transform_active_layer at 0x14a426160>}))
    329 shape = [
    330     np.round(s / sc).astype('int') if s > 0 else 1
    331     for s, sc in zip(scene_size, scale)
    332 ]
    333 empty_labels = np.zeros(shape, dtype=int)
--> 334 self.add_labels(empty_labels, translate=np.array(corner), scale=scale)
        scale = <class 'numpy.ndarray'> (2,) float64
        corner = <class 'numpy.ndarray'> (2,) float64
        empty_labels = <class 'numpy.ndarray'> (512, 512) int64
        self = Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.015, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(226.10837757094214, 247.29064387933107), scaled=True, size=10, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 2.0, 1.0), (0.0, 2.0, 1.0)), current_step=(0, 0), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Labels layer 'Labels' at 0x137630df0>], scale_bar=ScaleBar(visible=False, colored=False, color=<class 'numpy.ndarray'> (4,) float32, ticks=True, position=<Position.BOTTOM_RIGHT: 'bottom_right'>, font_size=10.0, box=False, box_color=<class 'numpy.ndarray'> (4,) float32, unit=None), text_overlay=TextOverlay(visible=False, color=<class 'numpy.ndarray'> (4,) float32, font_size=10.0, position=<TextOverlayPosition.TOP_LEFT: 'top_left'>, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=<napari.utils.transforms.transforms.Affine object at 0x137954e50>, transform_drag=<napari.utils.transforms.transforms.Affine object at 0x137954d90>, transform_final=<napari.utils.transforms.transforms.Affine object at 0x137954d60>, transform=<napari.utils.transforms.transforms.Affine object at 0x137954ca0>, allow_new_selection=True, selected_vertex=None)), help='', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='system', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_move at 0x14a4aa670>], mouse_drag_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_drag at 0x14a497670>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x1267d1ee0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Shift': <function InteractionBoxMouseBindings.initialize_key_events.<locals>.hold_to_lock_aspect_ratio at 0x14a497940>, 'Control-Shift-R': <function InteractionBoxMouseBindings._reset_active_layer_affine at 0x14a4260d0>, 'Control-Shift-A': <function InteractionBoxMouseBindings._transform_active_layer at 0x14a426160>})
        np = <module 'numpy' from '/Users/piotrsobolewski/Dev/miniforge3/envs/apple-TF29/lib/python3.9/site-packages/numpy/__init__.py'>

File ~/Dev/napari/napari/components/viewer_model.py:5, in add_labels(self=Viewer(axes=Axes(visible=False, labels=True, col...indings._transform_active_layer at 0x14a426160>}), data=<class 'numpy.ndarray'> (512, 512) int64, num_colors=50, features=None, properties=None, color=None, seed=0.5, name=None, metadata=None, scale=<class 'numpy.ndarray'> (2,) float64, translate=<class 'numpy.ndarray'> (2,) float64, rotate=None, shear=None, affine=None, opacity=0.7, blending='translucent', rendering='iso_categorical', depiction='volume', visible=True, multiscale=None, cache=True, plane=None, experimental_clipping_planes=None)
      3 import inspect
      4 import itertools
----> 5 impor [...]

2022-09-07 09:42 UTC, psobolewskiPhD commented
Question:
At present there's an extra column in the ShortcutsSettings pane, on the left, titled `shortcuts` (lower case like that, which is also a bit odd).
I figured out that it's coming from here:
https://github.com/napari/napari/blob/1546f18ecc13364d5415623a9c11ed760ff043e2/napari/settings/_shortcuts.py#L10-L18
I think this extra column looks like a glitch and is spurious, but can't figure out how to drop it other than to change to `title=""`.
Alternately, if the ShortcutEditor showed up BELOW, then the title field could be used to provide info about editing: "To edit, double-click the keybinding." or something.

2022-09-07 10:00 UTC, Czaki commented
> Then I got an IndexError when making a new Labels layer in empty Viewer.

you found the next bug introduced by me in #4814. I assume that at least one shortcut for all actions is set. 

> At present there's an extra column in the ShortcutsSettings pane, on the left, titled `shortcuts` (lower case like that, which is also a bit odd).

In reality, it comes from here (`layout.addRow`): https://github.com/napari/napari/blob/a0a197f07a9f2653cb5c48c190aac7a3cbacc6d4/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py#L693-L707

The core is that we create GUI from the Settings model. So if someone adds a typical (does not require custom widget) field to settings, there is no need to update the settings dialog code.

But there may be a nice to add feature and check that if there is only one field, then do not add a column with a field name. 
But I think that it is out of the scope of this PR. But feel free to open such PR if you think that it will improve the interface.

2022-09-07 10:15 UTC, psobolewskiPhD commented
Oh, sorry I realized the empty shortcut after you already fixed it!
Ah, yeah it's making more sense. I mean mostly settings are stuff like:
Title: <entry widget>
Title2: <checkbox>
It's just Shortcuts where there's the ShortcutEditor widget, that has it's own titles, etc.
I'll take a look. It's not a big deal, just a visual.

BTW, after pulling your new commit and `napari --reset` everything is working great, whether keybind is set or not. But the tooltips for the tools are still generic. I swear they used to show the keybind and that at one point I saw the 2nd keybind there too. Am I going crazy?

2022-09-07 10:20 UTC, Czaki commented
> But the tooltips for the tools are still generic

Could you point out which tooltips? It is not clear for me.

2022-09-07 10:24 UTC, psobolewskiPhD commented
> > But the tooltips for the tools are still generic
> 
> Could you point out which tooltips? It is not clear to me.

Sorry, I mean the Labels layer tools tooltips.
If I do a `napari --reset` to start fresh, make a new Labels layer, hoover the Fill tool, the tooltip is generic: "fill"
But, if it got Preferences>Shortcuts>Restore all defaults (and accept), (make no more changes) then I get rich tooltip:
"Activate the fill bucket (3) Toggle <command>"
Of course the <command> toggle doesn't work, because it's not bound in the defaults.

2022-09-07 10:32 UTC, psobolewskiPhD commented
To make shit weirder, a new Labels layer gets the generic tool tooltips.
But if you go to Pref>Shortcuts>Restore Default Keybinds ... with the Labels layer in existence, you get the rich tooltips for that layer.

2022-09-07 10:48 UTC, Czaki commented
> Edit2: Just tested, this bizarre behavior is in effect on Live 0.4.16, so it's not related to this PR.

nah. Just changed. Currently, tooltip will be set on application start.

2022-09-07 11:03 UTC, psobolewskiPhD commented
> > Edit2: Just tested, this bizarre behavior is in effect on Live 0.4.16, so it's not related to this PR.
> 
> nah. Just changed. Currently, tooltip will be set on application start.

Awesome!
<img width="349" alt="image" src="https://user-images.githubusercontent.com/76622105/188863030-762de428-6e38-4b63-8083-5ea4b8ba3685.png">

2022-09-07 11:23 UTC, Czaki commented
information about hold is added to #5021

2022-09-08 10:23 UTC, alisterburt approved these changes
changes look good - works perfectly for me and having the tooltips set dynamically is really really nice.

Slightly longer term we should change this to 'alternative keybindings' and allow to set multiple alternatives but that is out of scope for this! I'm approving

2022-09-08 10:25 UTC, alisterburt requested changes
examples test failure looks real @Czaki - could you take a look?

2022-09-08 12:00 UTC, alisterburt approved these changes
removing block as tests are passing, thanks @Czaki !

2022-09-08 12:00 UTC, merged

2022-09-08 12:28 UTC, psobolewskiPhD reviewed
christ i'm incompetent...

2022-09-08 12:28 UTC, psobolewskiPhD commented on napari/_qt/widgets/qt_keyboard_settings.py
> +                    "To clean shortcut use Backspace or Delete. To set one of this as shortcut, first clean previous shortcut."
I don't love the verb `clean` in this context. Also added how to edit, because I'm not sure visually it's clear that the keybinds can be edited.

```suggestion
                    "To edit, double-click the keybinding. To unbind a key, use Backspace or Delete. To set Backspace or Delete, first unbind."
```

2022-09-08 12:28 UTC, psobolewskiPhD commented on napari/_qt/widgets/qt_keyboard_settings.py
> +                    "To clean shortcut use Backspace or Delete. To set one of this as shortcut, first clean previous shortcut."
@alisterburt @Czaki any input on the wording here?
Another alternative to "clean"—which I really don't like—is "clear"?

2022-09-08 12:35 UTC, Czaki commented on napari/_qt/widgets/qt_keyboard_settings.py
> +                    "To clean shortcut use Backspace or Delete. To set one of this as shortcut, first clean previous shortcut."
You need to open a separate PR (this should be fast) to apply these changes as it is merged. My only remark is maybe `To unbind a key` should be `To unbind a shortcut`