Reset contrast range when update layer data from magicgui FunctionGui
napari/napari pull request #5136
Opened 2022-09-25 11:07 UTC by Czaki

# Description

Reset contrast limits range and contrast limits when updating layer data from functions that return `ImageData` etc. 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

2022-09-25 11:08 UTC, Czaki commented
This PR solves the problem mentioned here https://github.com/napari/napari/issues/5127#issuecomment-1257167470 (and above in discussions), but I'm not sure if it solves the general problem from #5127 issue. 

cc @haesleinhuepf, @psobolewskiPhD

2022-09-25 13:33 UTC, haesleinhuepf commented
Thanks for working on this @Czaki !

I'm a little bit worried about side effects. Would it be possible that the visualization appears blinking if contrast limits are updated all the time? Also, does this cause a delay?

I must admit, I liked the idea by @psobolewskiPhD for adding a reset button more than resetting all the time...

2022-09-25 13:56 UTC, Czaki commented
> I'm a little bit worried about side effects. Would it be possible that the visualization appears blinking if contrast limits are updated all the time? Also, does this cause a delay?

But this is reset only if new data is set as the function's output. 
The delay will be same as the calculation min and max of returned data.

2022-09-26 08:33 UTC, brisvag commented
I agree that I don't love updating all the time. I understand the use case of updating a layer inplace with a *dramatically* different image (as in @haesleinhuepf's example of `image1 / image2`) but I would expect most use cases to update inplace with something *similar* to the original data. In that case, I think consistency of contrast limits and range is more important for effective comparison.

Wouldn't it be better to do this *if* the `auto` option is selected?

2022-09-26 08:38 UTC, brisvag commented
Actually, maybe only update the *range* automatically (when `auto` is selected)`.

2022-10-24 20:42 UTC, kandarpksk commented
Aside from the solutions being proposed, we might also want to consider:

(1) indicating in the UI that the contrast limit is "out of date"
Showing a warning icon with a tooltip to explain the issue (and solution) would improve visibility of the existing reset feature.

(2) providing an option to auto-reset the contrast limit
I don't have an opinion of whether the option should be enabled by default or not, but seems like there are likely to be users on both sides, and it's a way to offer flexibility.

2023-05-25 01:25 UTC, jni commented
@Czaki given concerns about possible side effects, should we close this? Or do you think we can address those concerns? I agree mostly with @brisvag's comment that auto-rescale should be opt-in.

2024-09-04 20:19 UTC, Czaki reviewed
If you have a simple widget for summing layers and three layers A, B, C. 

For the current solution, if You first execute A+B and then A+C, the effect will be different from just executing A+C, as in the first case the contrast will be calculated based on the result of A+B, in the second it will be based on A+C.  

So we have a situation where image presence depends on execution order, and it looks like a bug to me. This PR is fixing this behavior. 

At least `reset_contrast_limits_range` should be called.

2024-09-04 20:19 UTC, Czaki commented on napari/_qt/_qapp_model/injection/_qprocessors.py
> +                    layer.reset_contrast_limits()
I think that at least `reset_contrast_limits_range` should be called.

2024-09-12 16:27 UTC, brisvag requested changes
Took a look again; I stand by my point, the cost of having this run all the time is too high and not worth it.

The problem is also easily circumvented by setting the `auto-contrast` to continuous, which does exactly what we want, and is explicit.

If anything, I would suggest a PR that exposes the autocontrast programmatically somehow?

2024-09-12 20:38 UTC, Czaki commented
> Took a look again; I stand by my point, the cost of having this run all the time is too high and not worth it.

Why is too high? If the layer is created using a functional widget, the calculation of contrast limit is performed. 

> If anything, I would suggest a PR that exposes the autocontrast programmatically somehow?

Programmatically, the plugin author may just return dict with contrast limits.

2024-09-13 08:32 UTC, brisvag commented
Here's a contrived example explaining why I think it's bad:

```
import numpy as np
import napari
from magicgui import magicgui
from napari.types import ImageData

data = np.random.random((100, 100))

@magicgui(auto_call=True, x={'widget_type': 'Slider'})
def random_change(x) -> ImageData:
    data[50, 50] = np.random.rand() * 10
    return data

viewer = napari.Viewer()
viewer.window.add_dock_widget(random_change)

viewer.add_image(data)
```

Move the slider around. I think it should be explicitly requested by using auto-contrast `continuous` if one wants this behaviour. Not only that, but this PR would make the other behaviour (no flashing, just change the values maintaining contrast) simply impossible to achieve.

2024-09-13 08:45 UTC, Czaki commented
So your example is an example that updates a single pixel, where my example is when we have generated, a whole new layer each time.

I do not see an example of a plugin like yours. But see @haesleinhuepf plugins that are wrappers around `SimpleITK`, `scikit-image` and other libraries that will benefit from at least `reset_contrast_range`

2024-09-15 11:40 UTC, brisvag commented
My point was that there are cases where we make many updates to the data (such as with a slider) and calculating min/max values might be too expensive done that often, unless requested. Or are you saying that is this negligible?

2024-09-16 07:23 UTC, Czaki commented
> My point was that there are cases where we make many updates to the data (such as with a slider) and calculating min/max values might be too expensive done that often, unless requested. Or are you saying that is this negligible?

I'm saying that magic should be more correct than performant. 
The plugin/widget author has multiple way to make it performant:

1. use `Image` instead of image data and then `image.data[50,50] = something; image.refresh()`,
2. return contrast limit `return data, {'contrast_limit`: (0, 100)}`, 

and much more. 

But with the current approach, the user has no message that the black screen is because of wrong contrast limits, not because the widget returns arrays of zeros. 
So by carrying about experienced users (to reduce the number of lines to write), the new users meet behavior that they may not expect.

2024-09-16 17:22 UTC, brisvag commented
Fair enough, I'm convinced :+1: But would be nice to warn the "experienced user" about the performance issue, somehow.

2024-09-16 19:11 UTC, Czaki commented
Did update documentation will be enough for such warn?

2024-09-18 14:48 UTC, jni commented
We discussed this at the napari-eurasia meeting (me, @DragaDoncila, @brisvag, and @Czaki in attendance) and let's just say it was contentious. 😂 Overall, we all agreed that it would be good to have more eyes on this PR, and to think hard about all the possible options to address the issues that this PR means to address:

- the contrast limits of a magicgui-generated layer depend on the *first* execution of the magicgui function — if that execution was somehow wrong (e.g. the first threshold is 0 so 100% of pixels are 255 so the contrast limits can't be computed), then later executions will have those incorrect contrast limits and it will be difficult for the user to know what went wrong. (Importantly, though, it is no longer difficult to *recover*: the user can hit the "Reset" button under the contrast limits.)
- a user presented with blown-out contrast-limits would have no visual indication to know whether the data was wrong on whether the contrast limits were wrong (and users are inclined to think it was the data).

Some options that were discussed (also above), as alternatives to always updating the contrast:
- warn the user when the image is low-contrast. (This would have the same performance cost but could be done asynchronously and would be less magical, because it would require an action from the user.)
- flash or otherwise emphasise the contrast limits adjustments and reset buttons when the new data is added, to indicate to the user that they might want to adjust the contrast now
- make contrast limits *and* an image histogram more prominent in the UI in general
- stop overwriting the data when ImageData is passed — which is inconsistent with a LayerDataTuple without the layer name set. (This could be very disruptive to users though.)

We'd like to hear from @psobolewskiPhD in particular since he has done a lot of user-facing work and might have encountered this issue before. We also plan to discuss this PR at upcoming community meetings.

2024-09-19 14:15 UTC, psobolewskiPhD commented
Gah I lost my post.
So I"m of two minds about this.
First, my experience with end users is that contrast limits -- in napari and otherwise -- are a source of confusion for novices. Histograms help a lot here -- not having an easy way to show histograms makes using napari as a most basic teaching tool harder -- I know, I could use matplotlib and numpy, but then we dive deeper into python.

So, getting back to the issue at hand, there are two cases:
1. where you want the contrast limits to update, because you are doing something that you *expect to change them*, e.g. the data1+3 example in the OP.
2. where you *don't* want the contrast limits to be updated, when comparing or doing something quantitative where changing the contrast limits would mislead you into a lack of a change. I can use the same example from OP, on main if you do data1+data1 and then data1+data3 you will clearly see that the data changed. But if you use this PR, it will look similar even though the values are vastly different. Of course, if you do this in the opposite order you will get 

So I feel like this is an issue that should be resolved by ensuring the current `auto-contrast` buttons handle these behaviors.
On main, if you run the widget from the OP the first time, you get the "proper" (auto) contrast. You can then click `continuous` and you get the behavior from this PR as far as I can tell.
Otherwise you can click `once` to set the contrast limits to the data range.
But there is no `reset` to set the contrast limits to full scale.
Then, there isthe right-click contrast limits slider, which has a `reset`, but it doesn't do what I expect as it appears to match `auto-contrast: once`.

2024-09-20 09:49 UTC, Czaki commented
> where you _don't_ want the contrast limits to be updated, when comparing or doing something quantitative where changing the contrast limits would mislead you into a lack of a change. I can use the same example from OP, on main if you do data1+data1 and then then when you do data1+data3 you will clearly see that the data changed. But if you use this PR, it will look similar even though the values are vastly different. Of course, if you do this in the opposite order you will get a black box. Adding to this, if you do data1+data1 for example and then adjust the contrast limits to reflect something about the data and then run the widget you lose those contrast limits. This would be irritating.

With this case it could be simply changed by returning `data, {'contrast_limit': (0, 100)}, 'image'`, not simple data. 
The original contrast limit may be read from data.

2024-09-22 01:24 UTC, jni commented
> The original contrast limit may be read from data.

No, we are talking about the case when the user has *manually* and intentionally changed the contrast limits based on the previous output.

> With this case it could be simply changed by returning data, {'contrast_limit': (0, 100)}, 'image', not simple data.

All cases of confusion can be cleared up by the implementation using a LayerDataTuple instead of ImageData, so I don't think that's really relevant. What's important is, we are acting on limited information in this case, so we *have* to make some guesses (despite the Zen of Python), and the questions are:

- which cases are more common: I think in this case, it's unclear, we've heard arguments in both directions based on different core devs' experience.
- how easy is it for the user to tell that a potentially incorrect guess has been made: currently, it's hard in both scenarios, but we can improve that.
- how easy is it for the user to *recover* from a potentially incorrect guess: in this case, not adjusting the limits wins by a very large margin.

2024-09-25 09:34 UTC, Czaki commented on napari/_qt/_qapp_model/injection/_qprocessors.py
> +                    layer.reset_contrast_limits()
Maybe this will be a good option to not reset range when someone adjusts contrast limits manually:
```suggestion
                    if layer.contrast_limits == layer.contrast_limits_range:
                        layer.reset_contrast_limits_range()
                        layer.reset_contrast_limits()
```

2024-10-04 07:21 UTC, Czaki commented on napari/_qt/_qapp_model/injection/_qprocessors.py
> +                    layer.reset_contrast_limits()
@jni @DragaDoncila @psobolewskiPhD ?

2024-11-21 05:18 UTC, jni commented
@Czaki to be honest, I think we should just close this one. As [this imagesc thread showed](https://forum.image.sc/t/fix-axis-range-in-napari-plots/104751) (in the context of 1D plots, but the same principles apply), automatically resetting the contrast limits may in fact be undesired behaviour, because you want to actually compare the brightness of different results. (@psobolewskiPhD mentioned this use case also, and it matches my own preference too.) Faced with two possible sources of confusion (image is unexpectedly black/white, vs, brightness is unexpectedly not changing), I think we should choose the one with the less complex code. Additionally, in his comment [here](https://github.com/napari/napari/pull/5136#issuecomment-1257195409), @haesleinhuepf, who is the original author of the issue that this is trying to fix, is also worried about these issues. And none of the other core devs who have weighed in here (@brisvag, @psobolewskiPhD, and myself) like the solution.

I am going to close but of course the discussion can continue. However, I honestly don't think that would be productive because we have thoroughly examined many angles of this issue. I think the best way forward here is to improve our infrastructure for displaying image histograms and corresponding contrast limits.

2024-11-21 05:18 UTC, closed without merging