Napari debugging during plugin development documentation
napari/napari pull request #5142
Opened 2022-09-26 11:13 UTC by seankmartin

# Description
This PR adds a page to the the napari.org/plugins category about debugging plugins during development.

## Type of change
- [ ] Documentation update

# References
closes #2948 closes #3735

Forum references:
* [Tracebacks on Image.sc](https://forum.image.sc/t/do-not-see-tracebacks-when-using-magicgui-to-create-widgets-in-napari/57861/2).
* [Reloading changed code on Image.sc](https://forum.image.sc/t/debug-develop-napari-plugin-how-to-reload-changed-code/60618/4).
* [Plugging logging on zulipchat](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/logging.20for.20plugins)

[Here is the code used in the docs](https://github.com/seankmartin/napari-plugin-debug)

# How has this been tested?
* I manually checked that the code in the docs runs as expected.
* `make docs` runs successfully and builds the docs as expected.

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

2022-09-26 11:17 UTC, seankmartin commented
Hi all, please let me know what you think of this draft documentation for debugging during plugin development. I'm very open to any feedback and really appreciate it!
@DragaDoncila thank you!

2022-09-26 23:40 UTC, DragaDoncila requested changes
This is looking great @seankmartin, thank you so much for writing such a detailed doc 🎉 ! I've left a couple of small tweaky comments and a couple just requesting a few notes added.

Let me know if I can clarify anything!

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +
I would add a note here to make sure that 

1. your plugin package is visible when you run `pip list` or `conda list`
2. your entry point is configured correctly as per https://napari.org/stable/plugins/first_plugin.html#update-setup-cfg

For example if `pip list` *does* show the package is installed, and `npe2 validate` reports success, but `napari` can't see your plugin, your entry point may be ill-configured.

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +## Seeing plugin errors and warnings
I feel we may want to remove this section entirely. Afaik we generally consider the `Plugin Errors` dialog a poor decision and want to get rid of it, so probs best not to mention it in the docs. I've never had a plugin error not reported to the command line so I would just recommend users inspect that (as below).

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +You can also set napari not to catch error messages, or set napari exit on error via the following environment variables, respectively:
```suggestion
You can also configure napari not to catch error messages, or force napari to exit on error via the following environment variables, respectively:
```

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +Since napari plugins are just Python functions, it can be easiest to isolate the issues from napari in some circumstances. For example, in the case of a widget, the widget could be isolated from napa
```suggestion
To simplify the debugging process, it can be useful to isolate the execution of your plugin code from executing napari itself. For example, in the case of a widget, the widget could be isolated from napari and run separately as a PyQt widget for debugging purposes. In this way, the usual debugging tools, such as those provided by an IDE, can be applied. This method has the additional benefit of aligning with test driven development.
```

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +
I would add a note here that launching napari & your plugin from a script can often allow you to use your IDE's built in debugging tools, as long as both your plugin and napari itself are installed in editable mode in your environment.

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +To demonstrate these debugging options, we will create a small plugin that prints the text entered into a box by the user. The plugin will provide an autogenerated widget, a `magic_factory` widget, a
It would be nice if we could provide this sample project in a repo the user can clone rather than having them create each file manually?

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +Then install the package by:
```suggestion
Then install the package into an environment already containing `napari` by:
```

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +Notice how the widgets in the viewer currently have the same behaviour as before, despite the code update. This is because the code won't immediately update, as IPython does not yet know that it shou
```suggestion
To see the updated behavior in action, just type the name of your changed function into IPython, or reference it in some way:
```

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +Currently, clicking on the run button for any of these widgets in the napari viewer outputs "You entered **YOUR_ENTRY**!". However, we would like to change the behaviour such that a special message i
```suggestion
Currently, clicking on the run button for any of these widgets in the napari viewer outputs "You entered **YOUR_ENTRY**!". However, we would like to change the behaviour such that a special message is printed if nothing is entered. So let's change our `example` function in `_widget.py` to:
```

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +This solution ties in with the idea of test-driven development (see the [napari testing guidelines](./test_deploy.md#prefer-smaller-unit-tests-when-possible)). The idea is to trust that napari will p
```suggestion
This solution ties in with the idea of test-driven development (see the [napari testing guidelines](./test_deploy.md#prefer-smaller-unit-tests-when-possible)). The idea is to trust that napari will provide the information you expect it to, and test your widgets independently of the viewer. In the case above we can verify that input values work as expected like so:
```

2022-09-26 23:40 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +2. Indicate that something that was handled, but may not be the behaviour the user was expecting using `warnings.warn("some warning")`.
```suggestion
2. Indicate that something was handled, but may not be the behaviour the user was expecting using `warnings.warn("some warning")`.
```

2022-09-27 09:17 UTC, seankmartin commented on docs/plugins/debug_plugins.md
> +To demonstrate these debugging options, we will create a small plugin that prints the text entered into a box by the user. The plugin will provide an autogenerated widget, a `magic_factory` widget, a
Yes, I thought this too but I was not sure what the practices for linking napari docs to other repos, so I wrote the code in the doc.
I do have a repository [here](https://github.com/seankmartin/napari-plugin-debug) with the code that I will suggest cloning for now.

2022-09-27 09:31 UTC, seankmartin commented on docs/plugins/debug_plugins.md
> +## Seeing plugin errors and warnings
Done!

2022-09-27 10:34 UTC, seankmartin commented
Hi @DragaDoncila thank you so much for the detailed review, that's brilliant!

I have incorporated all of the changes 😄.

I guess the main things to double check I understood correctly:
1. You asked for a few "notes". I wasn't sure if that meant to add a bit more detail, or specifically add note blocks (like ```{note}```). I defaulted to just adding some extra explanatory text - but very happy to convert to note blocks if that is better.
2. I provided a [link](https://github.com/seankmartin/napari-plugin-debug) to the starting version of the code, it has all the contents of the long form code blocks I wrote out for plugin example setup. And a link to the [finished version](https://github.com/seankmartin/napari-plugin-debug/tree/full_code). Hopefully this works, but I understand this is a link to a personal repository so I'm fully open to any thoughts here!

Thank you again, and very happy to make further changes or discuss further.

2022-09-27 11:35 UTC, seankmartin commented
Just looking at my built docs, it seems that linking to the markdown docs didn't work in this case (Line 28):
Your entry point is correctly configured, see the [first steps](./first_plugin.md#update-setup-cfg) for information.
Do we need to link to the html in this case?

2022-09-28 22:59 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +2. Your entry point is correctly configured, see the [first steps](./first_plugin.md#update-setup-cfg) for information.
```suggestion
2. Your entry point is correctly configured, see the [first steps](./first_plugin#update-setup-cfg) for information.
```

2022-09-29 20:27 UTC, DragaDoncila commented
@seankmartin thank you for those updates, it's looking great!

>  I defaulted to just adding some extra explanatory text - but very happy to convert to note blocks if that is better.

Extra text is perfect! I should be more specific with my terms lol.

> Hopefully this works, but I understand this is a link to a personal repository so I'm fully open to any thoughts here!

Hmm yeah, we don't really have a standardized solution for this. I think for now it's ok if it points to your personal one, but we probably want to provide a more general mechanism in the future. I don't think that should hold up this PR though.

> Just looking at my built docs, it seems that linking to the markdown docs didn't work in this case (Line 28):

Hmm yeah I'm not sure why that anchor link isn't working, I foolishly thought it might be the `.md` suffix but that hasn't fixed it. @melissawm do you know why [this relative link](https://github.com/napari/napari/pull/5142/files#diff-20386b0f972ae427f9e3277ab8810b2f6e094115858b8d6df52d92fc8ae704abR28) isn't building?

2022-09-29 21:00 UTC, psobolewskiPhD commented
I'm not 100% sure, but I ran into something similar. Perhaps try:
`first_plugin.md#update-setup-cfg` 
So use the .md extension, but without the ./

2022-09-29 22:08 UTC, DragaDoncila commented on docs/plugins/debug_plugins.md
> +2. Your entry point is correctly configured, see the [first steps](./first_plugin#update-setup-cfg) for information.
```suggestion
2. Your entry point is correctly configured, see the [first steps](first_plugin.md#update-setup-cfg) for information.
```

2022-09-29 22:25 UTC, DragaDoncila commented
Hmm thanks for the suggestion @psobolewskiPhD, that doesn't seem to have worked either though.

2022-10-06 19:36 UTC, melissawm reviewed
I left a few comments, hope those are useful - let me know if I can help further!

2022-10-06 19:36 UTC, melissawm commented on docs/plugins/debug_plugins.md
> +Then, for `python test_print.py` you can use any of your usual debugging tools - such as the visual debugger provided by a Python IDE (e.g. PyCharm, VSCode, or Spyder). Further, an isolated test like
Whenever possible, it is better to use internal links instead of linking to the actual napari.org website.

```suggestion
Then, for `python test_print.py` you can use any of your usual debugging tools - such as the visual debugger provided by a Python IDE (e.g. PyCharm, VSCode, or Spyder). Further, an isolated test like this can be integrated into a [testing suite for your napari plugin](test_deploy).
```

2022-10-06 19:36 UTC, melissawm commented on docs/plugins/debug_plugins.md
> +In addition to these user focused methods, you can set up plugin debug logs and messages during development. You can either use [napari specific functions](https://napari.org/dev/api/napari.utils.not
Here also we can use internal links. The syntax is from [MyST](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#targets-and-cross-referencing)

```suggestion
In addition to these user focused methods, you can set up plugin debug logs and messages during development. You can either use {mod}`napari specific functions <napari.utils.notifications>`, or [built in Python logging](https://docs.python.org/3/library/logging.html).
```

2022-10-06 19:36 UTC, melissawm commented on docs/plugins/debug_plugins.md
> +2. Your entry point is correctly configured, see the [first steps](first_plugin.md#update-setup-cfg) for information.
This is an interesting one - the [autogenerated heading anchors](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-header-anchors) may behave differently with different syntax (in this case, the target section is called ``Update `setup.cfg` ``, and the dot is removed when creating the link.

Here's a tip of how to inspect those generated links:

```
(napari-dev) ~/napari (napari-debug-docs ✗) myst-anchors -l 3 docs/plugins/first_plugin.md 
<h1 id="your-first-plugin"></h1>
<h2 id="before-you-start"></h2>
<h2 id="what-is-a-plugin"></h2>
<h2 id="1-create-a-new-directory"></h2>
<h2 id="2-add-standard-python-package-metadata-files"></h2>
<h3 id="pyprojecttoml"></h3>
<h3 id="setupcfg"></h3>
<h2 id="3-implement-the-plugin"></h2>
<h3 id="add-plugin-functionality-to-napari_hello__init__py"></h3>
<h3 id="add-a-napariyaml-manifest"></h3>
<h3 id="update-setupcfg"></h3>
<h2 id="4-install-your-plugin-and-try-it-out"></h2>
<h2 id="get-going-quickly-with-cookiecutter"></h2>
<h2 id="next-steps"></h2>
```

2022-10-06 19:36 UTC, melissawm commented on docs/plugins/debug_plugins.md
> +2. Your entry point is correctly configured, see the [first steps](first_plugin.md#update-setup-cfg) for information.
```suggestion
2. Your entry point is correctly configured, see the [first steps](first_plugin.md#update-setupcfg) for information.
```

2022-10-06 19:36 UTC, melissawm commented on docs/plugins/debug_plugins.md
> +```
This code block is generating errors when compiling - I am guessing this comes from the `!` character in the code block. The following works, but I'll leave it as a suggestion, maybe there are better ones:

```suggestion
```IPython
# Run before changing the code
'You entered !'

# Run after changing the code, but before triggering an update
'You entered !'

In [10]: example # anything in IPython to reload that code

# Now the code is reloaded, run outputs as expected
Please enter something in the text box.
```
```

2022-10-06 19:36 UTC, melissawm commented on docs/plugins/debug_plugins.md
> +```txt
This is also causing errors with the MyST parser:

```suggestion
```
```

2022-10-07 11:18 UTC, seankmartin commented
> I left a few comments, hope those are useful - let me know if I can help further!

Hi @melissawm that's great, thank you so much for the help, much appreciated! 🎉 

I was wondering, how do you find errors with the MyST parser? I built the docs locally before PR, but didn't notice the errors. Are there logs somewhere that you can check, or a command to run to find errors?

2022-10-07 13:15 UTC, melissawm commented
@seankmartin the errors appear in the log of the docs build. Unfortunately we also get 300 other unrelated errors that mostly come from autosummary and the way it doesn't know how to deal with the napari codebase (this is autosummary's fault, not napari's!). Because I already know where to look, I can catch them in the sea of red messages 😅

2022-10-07 14:49 UTC, seankmartin commented
@melissawm Thanks for the explanation, no wonder I didn't spot them! 😰

2022-10-07 16:17 UTC, seankmartin commented
Just thinking about it now, I think I may have misunderstood the last suggestion regard the `txt` labelled code block that was causing issues. I'll have a look tomorrow, but I think the way I took the suggestion was not as intended.

2022-10-10 11:07 UTC, seankmartin commented
Hi @melissawm I think I have fixed the myst parser errors/warnings now, though perhaps I am still looking in the wrong place in the logs!

Is this good to go if I have correctly fixed the myst parser errors/warnings? Please let me know if further changes are desired!

2022-10-12 23:22 UTC, DragaDoncila approved these changes

2022-10-12 23:29 UTC, merged