Add correct `enablement` kwarg to `Split Stack` action, `Convert data type` submenu and `Projections` submenu
napari/napari pull request #5437
Opened 2022-12-22 17:52 UTC by dalthviz

# Description

Fix layer context menu enable/disable state for the `Split Stack` action, `Convert data type` submenu and `Projections` submenu

Before:

![ctx_menu_before](https://user-images.githubusercontent.com/16781833/209195646-852095d7-bbfb-4664-99d0-1ad19aa0b25b.gif)

After:

![ctx_menu_after](https://user-images.githubusercontent.com/16781833/209195229-d65bfb33-830f-4328-ba89-8748342e6105.gif)

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)

# References

closes #5418 

# How has this been tested?

- [ ] all tests pass with my change
- [ ] I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

2022-12-26 16:40 UTC, psobolewskiPhD commented on napari/_app_model/context/_layerlist_context.py
> +        _active_type(s) == "image" and _active_ndim(s) and _active_ndim(s) > 2
```suggestion
        _active_type(s) == "image" and _active_ndim(s) and _active_ndim(s) > 2 and not _is_rgb(s)
```

2022-12-26 16:53 UTC, psobolewskiPhD requested changes
When testing this I noticed we error with projections of RGB images:
<details>
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py:903, in CanvasBackendDesktop.paintGL(self=<vispy.app.backends._qt.CanvasBackendDesktop object>)
    901 # (0, 0, self.width(), self.height()))
    902 self._vispy_canvas.set_current()
--> 903 self._vispy_canvas.events.draw(region=None)
        self._vispy_canvas = <VispyCanvas (PyQt5) at 0x283ce5090>
        self._vispy_canvas.events.draw = <vispy.util.event.EventEmitter object at 0x283cf85e0>
        self = <vispy.app.backends._qt.CanvasBackendDesktop object at 0x283cde5f0>
        self._vispy_canvas.events = <vispy.util.event.EmitterGroup object at 0x283cf8580>
    905 # Clear the alpha channel with QOpenGLWidget (Qt >= 5.4), otherwise the
    906 # window is translucent behind non-opaque objects.
    907 # Reference:  MRtrix3/mrtrix3#266
    908 if QT5_NEW_API or PYSIDE6_API or PYQT6_API:

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:453, in EventEmitter.__call__(self=<vispy.util.event.EventEmitter object>, *args=(), **kwargs={'region': None})
    450 if self._emitting > 1:
    451     raise RuntimeError('EventEmitter loop detected!')
--> 453 self._invoke_callback(cb, event)
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
        self = <vispy.util.event.EventEmitter object at 0x283cf85e0>
        cb = <bound method QtViewer.on_draw of <napari._qt.qt_viewer.QtViewer object at 0x283caae60>>
    454 if event.blocked:
    455     break

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:471, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method QtViewer.on_draw of <napari._qt.qt_viewer.QtViewer object>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    469     cb(event)
    470 except Exception:
--> 471     _handle_exception(self.ignore_callback_errors,
        self = <vispy.util.event.EventEmitter object at 0x283cf85e0>
        cb = <bound method QtViewer.on_draw of <napari._qt.qt_viewer.QtViewer object at 0x283caae60>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
        (cb, event) = (<bound method QtViewer.on_draw of <napari._qt.qt_viewer.QtViewer object at 0x283caae60>>, <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    472                       self.print_callback_errors,
    473                       self, cb_event=(cb, event))

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:469, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method QtViewer.on_draw of <napari._qt.qt_viewer.QtViewer object>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    467 def _invoke_callback(self, cb, event):
    468     try:
--> 469         cb(event)
        cb = <bound method QtViewer.on_draw of <napari._qt.qt_viewer.QtViewer object at 0x283caae60>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    470     except Exception:
    471         _handle_exception(self.ignore_callback_errors,
    472                           self.print_callback_errors,
    473                           self, cb_event=(cb, event))

File ~/Dev/napari/napari/_qt/qt_viewer.py:1119, in QtViewer.on_draw(self=<napari._qt.qt_viewer.QtViewer object>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
   1117 else:
   1118     displayed_axes = self.viewer.dims.displayed[-nd:]
-> 1119 layer._update_draw(
        layer = <Image layer 'astronaut mean-proj' at 0x299407100>
        self = <napari._qt.qt_viewer.QtViewer object at 0x283caae60>
        self.viewer = Viewer(axes=AxesOverlay(visible=False, opacity=1.0, order=1000000, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 255.5, 255.5), zoom=1.5159179687499997, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(289.80263756167017, 25.60629333267907), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 512.0, 1.0), (0.0, 512.0, 1.0)), current_step=(256, 256), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'astronaut' at 0x16b315b70>, <Image layer 'astronaut mean-proj' at 0x299407100>], scale_bar=ScaleBarOverlay(visible=False, opacity=1.0, order=1000000, position=<CanvasPosition.BOTTOM_RIGHT: 'bottom_right'>, colored=False, color=<class 'numpy.ndarray'> (4,) float32, ticks=True, font_size=10.0, box=False, box_color=<class 'numpy.ndarray'> (4,) float32, unit=None), text_overlay=TextOverlay(visible=False, opacity=1.0, order=1000000, position=<CanvasPosition.BOTTOM_RIGHT: 'bottom_right'>, color=<class 'numpy.ndarray'> (4,) float32, font_size=10.0, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=<napari.utils.transforms.transforms.Affine object at 0x16f0fada0>, transform_drag=<napari.utils.transforms.transforms.Affine object at 0x16f0fae00>, transform_final=<napari.utils.transforms.transforms.Affine object at 0x16f0fae60>, transform=<napari.utils.transforms.transforms.Affine object at 0x16f0faec0>, allow_new_selection=True, selected_vertex=None)), help='`minimum` blending mode works best with inverted colormaps with a white background.', status='', tooltip=Tooltip(visible=False, text=''), theme='system', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_move at 0x284db8e50>], mouse_drag_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_drag at 0x284db8d30>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x16e7b8790>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={<app_model.types._keys._keybindings.KeyBinding object at 0x284d8e380>: <function InteractionBoxMouseBindings.initialize_key_events.<locals>.hold_to_lock_aspect_ratio at 0x284db9b40>, <app_model.types._keys._keybindings.KeyBinding object at 0x16d7181f0>: <function InteractionBoxMouseBindings._reset_active_layer_affine at 0x284cc6dd0>, <app_model.types._keys._keybindings.KeyBinding object at 0x16d718280>: <function InteractionBoxMouseBindings._transform_active_layer at 0x284cc7250>})
        self.viewer.camera.zoom = 1.5159179687499997
        self.viewer.camera = Camera(center=(0.0, 255.5, 255.5), zoom=1.5159179687499997, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True)
        canvas_corners_world = <class 'numpy.ndarray'> (2, 2) float64
        displayed_axes = (0, 1)
        self.canvas = <VispyCanvas (PyQt5) at 0x283ce5090>
   1120     scale_factor=1 / self.viewer.camera.zoom,
   1121     corner_pixels_displayed=canvas_corners_world[
   1122         :, displayed_axes
   1123     ],
   1124     shape_threshold=self.canvas.size,
   1125 )

File ~/Dev/napari/napari/layers/base/base.py:1508, in Layer._update_draw(self=<Image layer 'astronaut mean-proj'>, scale_factor=0.6596663016169556, corner_pixels_displayed=<class 'numpy.ndarray'> (2, 2) float64, shape_threshold=(817, 840))
   1504 all_corners = list(itertools.product(*corner_pixels_displayed.T))
   1505 # Note that we ignore the first transform which is tile2data
   1 [...]

2022-12-26 18:18 UTC, psobolewskiPhD approved these changes

2023-01-04 14:00 UTC, Carreau approved these changes

2023-01-08 14:11 UTC, merged