Back point selection with a psygnal evented set
napari/napari pull request #5691
Opened 2023-04-04 11:14 UTC by katherine-hutchings

# Description
This pull request makes the point selection model use an evented set from psygnal rather than the python set. This will close #5686 and also #4023. 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# References
https://psygnal.readthedocs.io/en/latest/API/containers/#psygnal.containers.EventedSet

# How has this been tested?
Manually tested, but have not yet added tests to the test suite.
@alisterburt helped me with this PR and will add some tests. 

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

2023-04-04 11:28 UTC, alisterburt commented
great work @katherine-hutchings - this will be really useful to have!

should also facilitate #5030 

@kevinyamauchi would you mind giving a quick review here? Is a super small change

2023-04-04 11:29 UTC, alisterburt approved these changes
approving but someone else should also approve before merge as I helped here

2023-04-04 12:09 UTC, brisvag reviewed
In principle looks good as is (and it's fine to merge this as an incremental change) but I just wanted to mention that we have the `Selection` model which might be a better fit here. There's a very old PR where @jni and I were trying to do this for the Labels layer, which might be a good starting point if you wanted to push this a bit further: https://github.com/napari/napari/pull/2978.

Even if not, it might be worth checking the name convention of `Selection` events and reflect it here, just so we don't have to deprecate stuff in the future when/if we do the swap :)

2023-04-04 12:09 UTC, brisvag approved these changes

2023-04-05 11:34 UTC, alisterburt requested changes
@brisvag thanks for the reveiw, have updated to the psygnal selection model - test failures are real so blocking merge here whilst I investigate

2023-04-06 08:03 UTC, alisterburt approved these changes

2023-04-06 08:17 UTC, alisterburt commented
The bug was an interesting one, summarising below 

As we are now maintaining an evented set as the model of the selection we no longer replace the existing set with the incoming data in the `Points.selected_data` setter, we instead clear the existing set then update it with the new contents.

The `_toggle_selected` utility modified the set in-place, so clearing the existing set in the setter also modified the incoming set. I decided that the utility function should instead return a copy, this seems to be how it was intended based on usage `layer.selected_data = _toggle_selected(selection, value)`

2023-04-06 08:18 UTC, alisterburt commented
test failures look unrelated, rerunning but I think this is good to go

2023-04-06 09:56 UTC, Czaki commented
Test failure is connected with new PySide6 release and lack of bugfix in the app model. 
As bugfix is merged then @tlambert03 maybe it is time for 0.1.3 release?

2023-04-06 10:54 UTC, jni commented
Hi @katherine-hutchings and welcome! 😊 

I'm A-ok with this change as it makes things strictly better, but @alisterburt what do you think about @brisvag's comment about our existing Selection object? I'd forgotten about it... 😅 Having said that, my main question is which API do we think is the future of the library that we will harmonise all selections to? If it's psygnal then we don't have to worry about it. But if it's Selection, or some more complex wrapper of the psygnal set, then we might want to wait a hot minute and consider it?

2023-04-06 11:33 UTC, alisterburt commented
thanks for the review @jni !

We originally had a bare `EventedSet` here which I switched over to the `Selection` from psygnal after @brisvag suggested the selection model - my vote is for harmonising around psygnal in napari generally and selections seem like a good place to start but happy to swap over to our internal vispy backed `Selection` if we're worried about mixing event systems

I was planning a followup PR which unifies layers which support selection around `Layer.selection` rather than the mishmash we have currently of `selected_data` `selected_label` - could be a good moment to also unify the object backing the selections?

2023-04-06 12:26 UTC, brisvag commented
> I was planning a followup PR which unifies layers which support selection around `Layer.selection` rather than the mishmash we have currently of `selected_data` `selected_label` - could be a good moment to also unify the object backing the selections?

Awesome :)

2023-04-06 12:32 UTC, kevinyamauchi approved these changes
This looks good to me. Thanks @katherine-hutchings ! This will definitely make my life easier.

Given that we have two approvals and confirmation from @Czaki  that the remaining test failure is unrelated, I think we should merge soon.

> I was planning a followup PR which unifies layers which support selection around Layer.selection rather than the mishmash we have currently of selected_data selected_label - could be a good moment to also unify the object backing the selections?

This would be great, @alisterburt !

2023-04-06 12:38 UTC, alisterburt commented
Thanks all - I'm going to assume the thumbs up from jni is a vote of approval, will merge tomorrow morning

2023-04-07 08:37 UTC, merged

2023-05-16 15:46 UTC, andy-sweet commented
I marked this with the 0.4.18 milestone because this is a small, non-breaking (because `Selection` is a `MutableSet`) feature addition. Whoever manages the 0.4.18 release should feel free to bump this to 0.5.0 if desired.