Fix extents of points layers
napari/napari pull request #5828
Opened 2023-05-11 20:25 UTC by dstansby

# Fixes/Closes

Closes https://github.com/napari/napari/issues/5750

# Description
This fixes the extents calculation for Points layers. Because the points are assumed to lie at the centre of voxels (ie. a point at [0, 0, 0] is rendered at [0.5, 0.5, 0.5] in the viewer). I *think* this is the right fix to apply, but I wouldn't be surprised if someone with more experience dealing with similar issues disagrees!

# References

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

I've modified existing unit tests so they pass, and added comments explaining the changes.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

2023-05-11 21:15 UTC, dstansby commented
I've fixed all the tests that this changes - am not 100% convinced this is the right change to make to fix https://github.com/napari/napari/issues/5750, but if not hopefully this PR at least starts the ball rolling towards the correct fix.

2023-05-12 07:54 UTC, brisvag commented
Hi @dstansby, thanks for the PR! There are currently some bugs with how dimensions and extents are calculated in the first place, which I introduced in #5522. I'm now in the process of fixing them in #5751.

I suggest we revisit this once that PR is merged, so we don't solve a bug with another bug :P In the meantime, however, I think that this is *not* the right solution, because it's actually images which are "offset by -0.5" (see the description in #5751 for some details on this).

2023-05-12 07:55 UTC, brisvag requested changes
Marking red so we don't accidentally merge!

2023-05-12 10:06 UTC, dstansby commented
Sounds good 👍 , and good luck with the other PR, I have had much 'fun' dealing with 0.5 pixel offsets in other projects 😄

2023-05-15 15:57 UTC, brisvag commented
I addressed this as part of #5751 (see [this comment](https://github.com/napari/napari/pull/5751#issuecomment-1547841247)). We shouldn't need extra changes after that is merged.

2023-05-15 16:02 UTC, dstansby commented
Grand, I'll close this then 👍

2023-05-15 16:02 UTC, closed without merging