Update citation cff
napari/napari pull request #5980
Opened 2023-06-21 16:49 UTC by Czaki

# Description

Update citation.cff be people who contribute to naparia 0.4.18 release. 

# References

## Type of change

- [x] Documentation (update of docstrings and deprecation information)

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/developers/translations.html).

2023-06-21 20:28 UTC, Nadalyn-CZI commented
My information is: 

- given-names: Nadalyn
  family-names: Miller
  affiliation: Apex Systems
  orcid: https://orcid.org/0009-0007-6993-1267

2023-06-22 00:01 UTC, jni approved these changes

2023-06-22 06:49 UTC, kolibril13 commented
hi @Czaki , thanks for the notification on zulipchat, my information is:

given-names: Jan-Hendrik
family-names: Müller
affiliation: Georg-August-Universität Göttingen 
orcid: https://orcid.org/0009-0007-3670-9969

While going thorugh the list, I've noted that Contantin Pape is from the same university, but there the characters "ä" and "ö" are represented by their respective Unicode code:
affiliation: "Georg-August-Universit\xE4t G\xF6ttingen"

2023-06-22 07:07 UTC, Czaki commented
> While going thorugh the list, I've noted that Contantin Pape is from the same university, but there the characters "ä" and "ö" are represented by their respective Unicode code:
> affiliation: "Georg-August-Universit\xE4t G\xF6ttingen"

I have fixed utf8 encoding problems

2023-06-22 15:57 UTC, Czaki commented
@ClementCaporal @LucaMarconato @ctr26 @davidpross @dstansby @glichtner @gselzer @hmaarrfk @jeylau @jnahlers @jwindhager @kabilar @katherine-hutchings @kcpevey @ksofiyuk @lucyleeow @melissawm @p-j-smith

I'm updating the citation file by adding people who contribute to 0.4.18 and are not present in CITATION.cff file. 

Could You provide your data to add it here? This data will be used by a person who uses Cite this repository option and to create an entry on Zenodo.

2023-06-22 16:07 UTC, gselzer commented
Thanks @Czaki!

given-names: Gabriel
family-names: Selzer
affiliation: University of Wisconsin-Madison
orcid: https://orcid.org/0009-0002-2400-1940

2023-06-22 16:11 UTC, ctr26 commented
Following above formal

given-names: Craig T.
family-names: Russell
affiliation: European Bioinformatics Institute - European Molecular Biology Laboratory
orcid: https://orcid.org/0000-0002-2447-5911

2023-06-22 16:14 UTC, jeylau commented
Thank you @Czaki!

given-names: Jessy
family-names: Lauer
affiliation: Swiss Federal Institute of Technology (EPFL), Lausanne, Switzerland
orcid: https://orcid.org/0000-0002-3656-2449

2023-06-22 16:20 UTC, dstansby commented
Thanks!

given-names: David
family-names: Stansby
affiliation: University College London
orcid: https://orcid.org/0000-0002-1365-1908

2023-06-22 16:47 UTC, p-j-smith commented
Thank you!

given-names: Paul
family-names: Smith
affiliation: University College London
orcid: https://orcid.org/0000-0002-3676-5318

2023-06-22 17:00 UTC, davidpross commented
Thanks @Czaki, here is my info:

given-names: David
family-names: Ross
affiliation: NanoString Technologies, Inc.
orcid: https://orcid.org/0000-0001-9998-3817

2023-06-22 18:03 UTC, katherine-hutchings commented
Thanks! 😊
given-names: Katherine
family-names: Hutchings
affiliation: University College London
orchid: n/a

2023-06-22 21:24 UTC, kabilar commented
Thanks!
given-names: Kabilar
family-names: Gunalan
affiliation: n/a
orchid: https://orcid.org/0000-0001-6964-4865

2023-06-22 21:52 UTC, jwindhager commented
Thanks @Czaki 
```yaml
- given-names: Jonas
  family-names: Windhager
  affiliation: ETH Zurich / University of Zurich
  orcid: https://orcid.org/0000-0002-2111-5291
```

2023-06-23 00:03 UTC, lucyleeow commented
Thanks @Czaki 

given-names: Lucy
family-names: Liu
affiliation: Quansight

2023-06-23 03:17 UTC, jnahlers commented
Thanks!

given-names: Jannis
family-names: Ahlers
affiliation: Monash University
orcid: https://orcid.org/0000-0003-0630-1819

JANNIS AHLERS (he/him)
PhD Candidate

Monash University
School of Physics & Astronomy
Level G, New Horizons, Clayton campus
20 Research Way
Clayton, VIC 3800
Australia

E: ***@***.*** ***@***.***>
LinkedIn: linkedin.com/in/jannisahlers/
<https://www.linkedin.com/in/jannisahlers/>

monash.edu/science/schools/physics

We acknowledge and pay respects to the Elders and Traditional Owners of the
land on which our Australian campuses stand. Information for Indigenous
Australians <https://www.monash.edu/indigenous-australians>

We're committed to diversity and inclusion
<https://www.monash.edu/about/diversity-inclusion>


On Fri, 23 Jun 2023 at 01:58, Grzegorz Bokota ***@***.***>
wrote:

> @ClementCaporal <https://github.com/ClementCaporal> @LucaMarconato
> <https://github.com/LucaMarconato> @ctr26 <https://github.com/ctr26>
> @davidpross <https://github.com/davidpross> @dstansby
> <https://github.com/dstansby> @glichtner <https://github.com/glichtner>
> @gselzer <https://github.com/gselzer> @hmaarrfk
> <https://github.com/hmaarrfk> @jeylau <https://github.com/jeylau>
> @jnahlers <https://github.com/jnahlers> @jwindhager
> <https://github.com/jwindhager> @kabilar <https://github.com/kabilar>
> @katherine-hutchings <https://github.com/katherine-hutchings> @kcpevey
> <https://github.com/kcpevey> @ksofiyuk <https://github.com/ksofiyuk>
> @lucyleeow <https://github.com/lucyleeow> @melissawm
> <https://github.com/melissawm> @p-j-smith <https://github.com/p-j-smith>
>
> I'm updating the citation file by adding people who contribute to 0.4.18
> and are not present in CITATION.cff file.
>
> Could You provide your data to add it here? This data will be used by a
> person who uses Cite this repository option and to create an entry on
> Zenodo.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/napari/napari/pull/5980#issuecomment-1602914037>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWZEKLSPYY3QN5U2KG3MZSTXMRTQ7ANCNFSM6AAAAAAZPA3TVE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-23 05:48 UTC, glichtner commented
Thanks @Czaki!

given-names: Gregor
family-names: Lichtner
affiliation: Universitätsmedizin Greifswald
orcid: https://orcid.org/0000-0002-5890-1958

2023-06-23 06:42 UTC, ClementCaporal commented
Thanks @Czaki

```yaml
- given-names: Clément
  family-names: Caporal
  affiliation: Laboratory for Optics and Biosciences, Ecole Polytechnique, INSERM, CNRS, Palaiseau, France
  orcid: https://orcid.org/0000-0002-9441-9173
```

2023-06-24 20:07 UTC, hmaarrfk commented
```
- given-names: Mark
  family-names: Harfouche
  affiliation: Ramona Optics Inc, Durham, North Carolina, USA
  orcid: https://orcid.org/0000-0002-4657-4603
```

2023-06-26 07:41 UTC, Czaki commented
@kcpevey @ksofiyuk I have added you base on github information


@LucaMarconato There is no enough information on github to add you to citation cff file

2023-06-26 07:46 UTC, Czaki commented
Should I try to add personal alias to an easier mapping person on GitHub nick?  https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionspersonalias

2023-06-26 08:55 UTC, Carreau commented
> Should I try to add personal alias to an easier mapping person on GitHub nick? https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionspersonalias

I think it will only make it easier to find who need to be added later on so that's a yes for me.

2023-06-26 11:21 UTC, LucaMarconato commented
@thanks Czaki, here is my info:

```
- given-names: Luca
  family-names: Marconato
  affiliation: EMBL Heidelberg
  orcid: https://orcid.org/0000-0003-3198-1326
```

2023-06-27 08:21 UTC, Czaki commented
@orena1 @Chris-N-K 
Both of You contribute to docs that are backported to 0.4.18. COuld you check your data?

2023-06-28 11:33 UTC, Chris-N-K commented
> @orena1 @Chris-N-K Both of You contribute to docs that are backported to 0.4.18. Could you check your data?

All fine thanks for your work! :)

2023-06-28 16:11 UTC, orena1 requested changes

2023-06-28 16:11 UTC, orena1 commented on CITATION.cff
> +  family-names: Amsalem
affiliation: Harvard Medical School, BIDMC
orcid:  https://orcid.org/0000-0002-8070-0378

2023-06-28 16:11 UTC, orena1 commented
Thanks a lot @Czaki , I've added my affiliation and orcid. 

Harvard Medical School, BIDMC
https://orcid.org/0000-0002-8070-0378

2023-06-28 16:14 UTC, Czaki commented on CITATION.cff
> +  family-names: Amsalem
```suggestion
- given-names: Oren
  family-names: Amsalem
  affiliation: Harvard Medical School, BIDMC
  orcid: orcid.org/0000-0002-8070-0378
```

2023-06-28 16:32 UTC, goanpeca commented
@Czaki my details :)

```
- given-names: Gonzalo
  family-names: Peña-Castellanos
  affiliation: Quansight
  orcid: https://orcid.org/my-orcid?orcid=0000-0002-1214-4680
```

2023-06-30 06:44 UTC, merged