skimage and six added to requirements.txta
napari/napari pull request #62
Opened 2018-11-15 17:56 UTC by AhmetCanSolak

# What does this PR do? Why are doing this? References?
skimage and six added to requirements.txt, those were missing.

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

## Final Checklist:
- [X] My PR is the possible minimum work for the desired functionality

2018-11-15 18:28 UTC, kne42 requested changes

2018-11-15 18:28 UTC, kne42 commented on requirements.txt
> +scikit-image>=0.14.1
This is only used in examples.

2018-11-15 18:28 UTC, kne42 commented on requirements.txt
> +six>=1.11.0
Where is this even used? We don't need it, the package is Python 3 only.

2018-11-16 05:25 UTC, jni commented
I guess now that we have a requirements folder, there should be `requirements/docs.txt` for things that are used in examples. And maybe `requirements/random.txt` for things that aren't used at all? =P

2018-11-16 05:25 UTC, closed without merging