Fix environment variable name name in docs build
napari/napari pull request #6401
Opened 2023-10-31 19:04 UTC by Czaki

# Description
Fix typo in environment variable to have working docs build in circleci

2023-10-31 19:21 UTC, melissawm approved these changes

2023-10-31 20:18 UTC, psobolewskiPhD commented
Wait, so this was never working this whole time? 
Also, one more place:
https://github.com/napari/napari/blob/467d57b3967074370b2ad6750bdfc1af8aee67d6/.github/workflows/build_docs.yml#L58

2023-10-31 20:19 UTC, psobolewskiPhD requested changes
Lets fix this too:
https://github.com/napari/napari/blob/467d57b3967074370b2ad6750bdfc1af8aee67d6/.github/workflows/build_docs.yml#L58

2023-10-31 20:24 UTC, psobolewskiPhD approved these changes

2023-11-01 20:08 UTC, psobolewskiPhD commented
Merging to get docs to build -- less red X in CI

2023-11-01 20:08 UTC, merged