Create a QApplication in QtViewer if one not present
napari/napari pull request #642
Opened 2019-10-29 11:15 UTC by jni

# Description

Currently, trying `napari.Viewer()` or `napari.view_*()` outside of a Qt loop raises a nasty error. (#634). In this PR, I try to detect whether there is a Qt loop active, and if there isn't, I make one. This results in blocking behaviour when there is no loop, ie `view_image()` will pause the console until the user is done with napari.

Problems:
- I'm not sure how to test it, since once it blocks there's nothing really for us to do. And we can't launch a QTimer before starting this since the whole point is to not have a QApplication running.
- Given this, this has not been as thoroughly tested as I would like!
- It all seems a bit clunky. However, my [other attempt](https://github.com/jni/napari/commit/716c460c463fd318cce5899560cd35a6839145b7) to improve `gui_qt` so that it can be called during viewer creation doesn't work, and ends up with an empty napari window in some circumstances.

Comments very welcome! But let's get this in ASAP! =)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2019-10-29 15:21 UTC, sofroniewn commented on napari/viewer.py
> +        if app is None:
Do we want to print a warning that this is happening?

2019-10-29 15:36 UTC, sofroniewn commented
I'm very glad we're doing something to address #634 but I'm not 100% sure yet about whether we should be creating the `QApplication` instead of just displaying a very helpful error message, or even just waiting for 2 seconds and then trying again.

I feel like if we create the `QApplication` then yes that first call to say `view_image` will work from a script, but a subsequent call to `add_points` will not happen and then people will be really confused as to why they don't see the points. For me actually the following run from a script
```python
import numpy as np
from skimage import data
import napari

astro = data.astronaut()
# add the image
viewer = napari.view_image(astro, rgb=True)
# add the points
points = np.array([[100, 100], [200, 200], [300, 100]])
viewer.add_points(points, size=30)
```
just yields a black canvas with no astronaut and no points

Similarly running 
```python
viewer = napari.view_image(np.random.random((100, 100)))
```
from a jupyter notebook yields a blank canvas, and then blocks the notebook which is super confusing. As does
```python
%gui qt5
viewer = napari.view_image(np.random.random((100, 100)))
```
all from the same cell (the %gui magic hasn't had time to take effect).

I think I'd much rather us raise a really clear Error message like -

> napari has not detected an existing Qt event loop. You must first create an event loop either using `with napari.gui_qt():` from a script or `%gui qt5` from iPython or jupyter.

We could potential add a wait in there for the usage where someone has run the `%gui qt5` from inside the same cell as the `view_image` command and we just need them to wait for it to finish making it. Basically we could test if app is None. If None we could raise a warning that we will wait, then try again, and if still None we could fail again with that error message.

What are your thoughts on this @jni?

2019-10-29 16:24 UTC, AhmetCanSolak commented on napari/viewer.py
> +        if app is None:
possibly yes

2019-10-29 16:31 UTC, AhmetCanSolak commented
@sofroniewn what you are experiencing is a similar story with trying to update UI from script at the moment. IMHO, we can take this a bit more general and refactor our contextmanager choice too. This issue strongly related to #520 . If we can come up with a different way, possibly scripting users can get advantage on updating UI. How do you guys feel about removing contextmanager usage for napari viewer? and invisibly we take care of QApplication business?

2019-10-29 16:47 UTC, sofroniewn commented
@AhmetCanSolak if we can remove the need for a context manager / gui magic, and solve #520 that would be amazing. If you have a solution that you're working on feel free to start a PR. I think in the mean time though just catching this problem and adding a better error message will make napari a lot less frustrating for a lot of people.

2019-10-29 16:51 UTC, AhmetCanSolak commented
we can remove it and make it work, but have to introduce new behavior on notebooks :) we can take this offline and discuss further.

2019-10-29 22:48 UTC, jni commented
Thanks for testing @sofroniewn! Indeed it doesn't work when you want to do anything more than launch a viewer, and indeed from a scripting perspective that's a big problem.

As a first step I'm going to replace this attempt with just a warning message, as you suggest.

Regarding the model, we could do something like matplotlib's `plt.show()` — calls to napari don't result in a visible viewer until `napari.show()` is called, and this is blocking in scripts.

@AhmetCanSolak it seems I almost completely missed the discussion in #520! I have a very vague memory of it. I guess I was very busy at that time, sorry! :grimacing: I like some of the proposed solutions there. Both an internal context and a decorator seem like good solutions. Certainly, though, users should not have to deal with QThreads or any such nonsense. =P

2019-10-29 23:08 UTC, jni commented
@sofroniewn what do you think of this? Bonus: this can actually be tested! (Test on the way, just switching trains now!)

2019-10-29 23:29 UTC, jni commented
Hmmm, the test passes locally... Investigating, but ideas most welcome!

2019-10-29 23:33 UTC, jni commented
Oh wow: so once the qtbot has been instantiated once, the QApplication is available everywhere. I can make the test fail locally by moving it the second test instead of the first test. This is why I like context managers vs global state!

So, somehow we need to make sure that this test runs before any other tests involving qtbot. Any ideas?

2019-10-29 23:36 UTC, jni commented
btw this is what the error looks like. I quite like it:

![napari-qt-error](https://user-images.githubusercontent.com/492549/67817336-fbdc8c80-fa7a-11e9-8932-2bb668843c3a.png)

2019-10-30 03:43 UTC, sofroniewn commented
This looks good, not sure how to help with the tests though, I can look into it tomorrow if you want

2019-10-30 07:12 UTC, jni commented
Woot, tests are passing! :tada:

2019-10-30 15:11 UTC, AhmetCanSolak commented
> 
> @AhmetCanSolak it seems I almost completely missed the discussion in #520! I have a very vague memory of it. I guess I was very busy at that time, sorry! 😬 I like some of the proposed solutions there. Both an internal context and a decorator seem like good solutions. Certainly, though, users should not have to deal with QThreads or any such nonsense. =P

No worries @jni :) feel free to weigh in #520 . I already played around little bit and ready to make a small PR about it.

2019-10-30 15:19 UTC, sofroniewn commented on napari/viewer.py
> +            sleep(2)
This trick with `sleep(2)` is not working for me if I have one jupyter cell with both the magic and the view_image command in it. Even if I make it `sleep(20)` it still doesn't work, so I guess it is blocking the construction of the event loop. Similarly when launching from ipython I couldn't find a condition where having two checks and the sleep actually helped anything. I think we should remove the sleep and just raise the error - which is SO much better than the kernel dying like it used to. Unless you were able to find a condition when having the sleep in there prevented an error.

2019-10-30 15:20 UTC, sofroniewn requested changes
I don't think our `sleep(2)` trick is working and so we should drop it, otherwise this is good to merge and I'll be so happy to get this in!!

2019-10-31 00:16 UTC, sofroniewn approved these changes
Ok great, looks good to me. I will merge after the tests pass

2019-10-31 00:43 UTC, merged