Add delete button for layers
napari/napari pull request #65
Opened 2018-11-18 21:25 UTC by sofroniewn

# What does this PR do? Why are doing this? References?
This PR adds a delete button above the layer list. Clicking the button will deleted the selected layers if there are any. Alternatively dragging and dropping onto the delete button will delete the dragged layers along with any others that are selected if the dragged layer is also selected.

Right now the deleting happens automatically. In the future we could add dialog box seeking confirmation before a delete that could be disabled in preferences.

One thing to note also is that if you delete all the layers and then try and add a new one you get an error. This behavior is true even if deleting layers directly from the notebook and should be fixed in some future PR.

One final note is that this PR also contains the drag and drop changes in PR #64 which have not been merged yet. The first 8 commits are in that PR and it should probably be merged first and then this one can be merged with only the changes relevant to the delete button.

## Type of change
[Please delete options that are not relevant.]
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
- [x] TestCase A Run examples.ipynb and manually interacted with the gui
![image](https://user-images.githubusercontent.com/6531703/48678225-1f8e1780-eb35-11e8-9994-c3bf31382ccd.png)

## Final Checklist:
- [x] My PR is the possible minimum work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2018-11-18 21:25 UTC, pep8speaks commented
Hello @sofroniewn! Thanks for updating the PR.

 - In the file [`gui/elements/_layer_list.py`](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/_layer_list.py), following                are the PEP8 issues :
> [Line 67:5](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/_layer_list.py#L67): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0
> [Line 68:5](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/_layer_list.py#L68): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0
> [Line 69:5](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/_layer_list.py#L69): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0
> [Line 70:5](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/_layer_list.py#L70): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0
> [Line 71:5](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/_layer_list.py#L71): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0


 - There are no PEP8 issues in the file [`gui/elements/qt/__init__.py`](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/__init__.py) !

 - In the file [`gui/elements/qt/_layer.py`](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py), following                are the PEP8 issues :
> [Line 1:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L1): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (114 > 79 characters)
> [Line 8:24](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L8): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 8:32](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L8): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 10:1](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 14:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L14): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)
> [Line 15:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 79 characters)
> [Line 21:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 38:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 47:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L47): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 97:24](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L97): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 97:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> [Line 122:5](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L122): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 130:9](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L130): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 131:9](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L131): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 132:9](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layer.py#L132): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '


 - In the file [`gui/elements/qt/_layerList.py`](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py), following                are the PEP8 issues :
> [Line 14:9](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L14): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 57:63](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L57): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 58:61](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L58): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 77:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L77): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 81:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L81): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 101:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L101): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 117:24](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L117): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 120:29](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerList.py#L120): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','


 - In the file [`gui/elements/qt/_layerPanel.py`](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerPanel.py), following                are the PEP8 issues :
> [Line 3:80](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerPanel.py#L3): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 9:28](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerPanel.py#L9): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 9:36](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerPanel.py#L9): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 11:1](https://github.com/sofroniewn/napari-gui/blob/aa03349a9125c67855a50b214cdea3e668623d8f/gui/elements/qt/_layerPanel.py#L11): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 22:1](https://github.com/sofr [...]

2018-11-18 21:27 UTC, sofroniewn commented
One extra thing to note, is that occasionally (though reproducibly) I get a warning message when deleting layers. One way to see it is to run the first 6 cells of the `examples/layers.ipynb` then in the gui unselect all the layers, select just the first one and click delete. Here is a copy of the error trace

```python
WARNING: Traceback (most recent call last):
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 295, in advance_eventloop
    eventloop(self)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/ipykernel/eventloops.py", line 137, in loop_qt5
    return loop_qt4(kernel)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/ipykernel/eventloops.py", line 130, in loop_qt4
    _loop_qt(kernel.app)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/ipykernel/eventloops.py", line 114, in _loop_qt
    app.exec_()
  File "/Users/nicholassofroniew/Github/napari-gui/napari_gui/elements/qt/_layerPanel.py", line 40, in on_click
    self.layers.remove_selected()
  File "/Users/nicholassofroniew/Github/napari-gui/napari_gui/elements/_layer_list.py", line 333, in remove_selected
    self.pop(i)
  File "/Users/nicholassofroniew/Github/napari-gui/napari_gui/elements/_layer_list.py", line 199, in pop
    self.events.remove_item(item=item)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/nicholassofroniew/Github/napari-gui/napari_gui/elements/_layer_list.py", line 310, in _remove
    layer.viewer = None
  File "/Users/nicholassofroniew/Github/napari-gui/napari_gui/layers/_base_layer.py", line 96, in viewer
    self._parent = parent
  File "/Users/nicholassofroniew/Github/napari-gui/napari_gui/layers/_visual_wrapper.py", line 44, in _parent
    self._node.parent = parent
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/scene/node.py", line 209, in parent
    self._update_trsys(None)
  File "/Users/nicholassofroniew/Github/napari-gui/napari_gui/_vispy/scene/visuals.py", line 82, in _update_trsys
    self.transforms.scene_transform = scene.node_transform(doc)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/visuals/transforms/transform_system.py", line 276, in scene_transform
    self._scene_transform.transforms = tr
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 96, in transforms
    self.update()
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/visuals/transforms/base_transform.py", line 153, in update
    self.changed(*args)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 212, in _subtr_changed
    self.update(ev)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/visuals/transforms/base_transform.py", line 153, in update
    self.changed(*args)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 281, in source_changed
    new_tr = [tr[0]]
IndexError: list index out of range
ERROR: Invoking <bound method SimplifiedChainTransform.source_changed of <ChainTransform [<STTransform scale=[1. 1. 1. 1.] translate=[0. 0. 0. 0.] at 0x4961768952>,
                 <STTransform scale=[1.0227273e+00 1.0227273e+00 1.0000000e-06 1.0000000e+00] translate=[138.18182   26.181818   0.         0.      ] at 0x4941059856>] at 0x126ca7da0>> for Event
```

2018-11-19 20:26 UTC, AhmetCanSolak requested changes

2018-11-19 20:26 UTC, AhmetCanSolak commented on gui/elements/qt/_layer.py
> +            name = name[:-2]
what is the naming convention? what is the motivation here?

2018-11-19 20:26 UTC, AhmetCanSolak commented on gui/elements/qt/_layerDivider.py
> +        self.selectedStlyeSheet = "QFrame {border: 3px solid rgb(71,143,205); background-color:rgb(71,143,205); border-radius: 3px;}"
somebody started to exploit CSS within Qt :D please keep it short like this for now, in future as we discussed possibly we will have separate styling files.

2018-11-19 20:26 UTC, AhmetCanSolak commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
Im not sure, if this line is really needed. Can somebody explain briefly?

2018-11-19 20:26 UTC, AhmetCanSolak commented on gui/elements/qt/_layerPanel.py
> +        pb = QDeleteButton(layers)
what `pb` stands for?

2018-11-19 20:26 UTC, AhmetCanSolak commented on gui/elements/qt/_layerPanel.py
> +path_delete = join(dir_path,'icons','delete.png')
is there an alternative way to this?

2018-11-19 20:27 UTC, sofroniewn commented on gui/elements/qt/_layerPanel.py
> +        pb = QDeleteButton(layers)
pushbutton - i will rename to a more understandable name

2018-11-19 20:28 UTC, sofroniewn commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
@kne42 explained to me that this was to avoid circular referencing that would prevent objects from being deleted by garbage collection, but I may be using it incorrectly

2018-11-19 20:29 UTC, sofroniewn commented on gui/elements/qt/_layerDivider.py
> +        self.selectedStlyeSheet = "QFrame {border: 3px solid rgb(71,143,205); background-color:rgb(71,143,205); border-radius: 3px;}"
agreed, separate files etc are the way to go. I think for now I'll leave it and then soon we'll do a PR where we separate all the styles out

2018-11-19 20:31 UTC, sofroniewn commented on gui/elements/qt/_layer.py
> +            name = name[:-2]
I wanted the cursor to show the names of the layers being dragged ideally as a vertical list but I could not get any form of line breaking to work inside the mimedata.text. I tried using `\n` and `<br>` and some related things but none worked, so I just settled on inserting a `;` for now, which is a little ugly but better than nothing

2018-11-19 20:33 UTC, sofroniewn commented on gui/elements/qt/_layerPanel.py
> +path_delete = join(dir_path,'icons','delete.png')
I couldn't get relative imports to work, inside the Qt sytlesheet, it was always starting the import path from the place where I was running the notebook and not the place where the file was located. If there's another way to do this happy to make changes

2018-11-19 21:55 UTC, AhmetCanSolak commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
@kne42 is right on that, but why we are letting possible circular referencing at all? :D

2018-11-19 21:58 UTC, AhmetCanSolak commented on gui/elements/qt/_layerPanel.py
> +path_delete = join(dir_path,'icons','delete.png')
okay, this is something to solve as path hacks could bring problems on various operating systems up as far as i see.  Maybe it is useful to have dummy code to demonstrate relative imports with Qt-taken CSS. Let me know if you want me to work on that. But i think this is not high priority. You can also leave an issue and we can check it later.

2018-11-20 02:25 UTC, jni commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
@AhmetCanSolak it's very useful in many contexts, for example, matplotlib figures have links to the axes they contain, while axes have links to the figure in which they're embedded. This allows everyone to coexists happily.

@sofroniewn @kne42 are we sure about the garbage collection problem? I thought the CPython garbage collector did cycle detection?

2018-11-20 02:28 UTC, jni commented
@sofroniewn that traceback looks pretty nasty, and I imagine it's a bug in vispy since you are not doing anything too fancy here... Although maybe this is weakref biting us in the butt? ;) 

What do people think about having a trashcan icon on the layers themselves?

2018-11-20 02:49 UTC, kne42 commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
I just tested this in ipython and you are absolutely right, it is handled by CPython. Thanks for pointing this out!

2018-11-20 05:41 UTC, sofroniewn commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
does this mean I should keep the weakref or drop it? The circular referencing is definitely helpful, not quite sure how I'd do some of the stuff I mentioned - very analogous to the example Juan gave.

2018-11-20 05:44 UTC, sofroniewn commented
My initial impulse was to have the trashicon on every button, but then I moved away from it as similar applications with layers have a single trash button, but I remain open to the possibility.

I can try deleting the weakref call and seeing if I get the same error

2018-11-20 18:53 UTC, kne42 commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
Yeah, I think you can drop it. As @jni pointed out, circular references appear to be very smartly handled by CPython for us :)

2018-11-20 18:58 UTC, kne42 commented
The independent trashcan icon seems most intuitive to me, but I would like to note that while other applications typically modify their layers in-place, we will typically be creating a new layer every time. In that scenario, perhaps making the deletion of individual layers as easy as possible should be a priority.

2018-11-20 19:26 UTC, sofroniewn commented
I have just created a new PR #68 that adds more properties to layers, and any discussion of including a trashIcon on a layer or not should probably look at what changes are being proposed there

2018-11-22 20:25 UTC, sofroniewn commented
The changes in this PR are also included in #68 along with some additional ones. In order to simplify things I will close this PR in favor of the other one

2018-11-22 20:25 UTC, closed without merging

2018-11-22 20:34 UTC, sofroniewn commented on gui/elements/qt/_layerList.py
> +        self.layers = weakref.proxy(layers)
I tried removing all the weakref calls, didn't seem to impact performance, but also didn't remove the warning messages referenced above.