Improve typing in layers.image.base
napari/napari pull request #6501
Opened 2023-11-26 22:41 UTC by dstansby

Adds more typing to napari.layers.image.base. I didn't quite finish all the typing, but the only mypy ignore left is for untyped defs which is down from four mypy ignores before this PR.

2023-11-28 14:10 UTC, Carreau commented
This picked up some conflicts.

2023-11-28 17:36 UTC, Carreau approved these changes
Thanks for quickly resolving conflict !

2023-11-28 23:42 UTC, Czaki commented
Do not merge this before 0.4.19 release. I do not want to have additional problems during cherry pick

2024-02-02 19:00 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +    ):
Why is this None removed? Is it to "untype" the whole method so Mypy ignores it?

2024-02-02 19:47 UTC, psobolewskiPhD requested changes
There's an issue here that prevents images from being opened!
Edit: Looks like tests caught it too.

2024-02-02 19:47 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +            shapes = self.data.shape
This change is breaking opening non-multi scale images, because later in `Image._get_level_shape` the `s in shapes` is an element of the tuple (so an int) rather than the whole tuple.
Here's the traceback that I'm getting:

<details>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/micromamba/envs/napari-dev/lib/python3.11/site-packages/app_model/backends/qt/_qaction.py:53, in QCommandAction._on_triggered(self=QMenuItemAction(MenuItem(when=None, group='navig...tle=None, toggled=None), alt=None), app='napari'), checked=False)
     49 def _on_triggered(self, checked: bool) -> None:
     50     # execute_command returns a Future, for the sake of eventually being
     51     # asynchronous without breaking the API.  For now, we call result()
     52     # to raise any exceptions.
---> 53     self._app.commands.execute_command(self._command_id).result()
        self._command_id = 'napari:astronaut'
        self = QMenuItemAction(MenuItem(when=None, group='navigation', order=None, command=CommandRule(id='napari:astronaut', title='Astronaut (RGB)', category=None, tooltip=None, status_tip=None, icon=None, icon_visible_in_menu=True, enablement=None, short_title=None, toggled=None), alt=None), app='napari')
        self._app = Application('napari')

File ~/micromamba/envs/napari-dev/lib/python3.11/site-packages/app_model/registries/_commands_reg.py:197, in CommandsRegistry.execute_command(self=<CommandsRegistry at 0x17e72b710 (108 commands)>, id='napari:astronaut', execute_asynchronously=False, *args=(), **kwargs={})
    193 except Exception as e:
    194     if self._raise_synchronous_exceptions:
    195         # note, the caller of this function can also achieve this by
    196         # calling `future.result()` on the returned future object.
--> 197         raise e
    198     future.set_exception(e)
    200 return future

File ~/micromamba/envs/napari-dev/lib/python3.11/site-packages/app_model/registries/_commands_reg.py:192, in CommandsRegistry.execute_command(self=<CommandsRegistry at 0x17e72b710 (108 commands)>, id='napari:astronaut', execute_asynchronously=False, *args=(), **kwargs={})
    190 future: Future = Future()
    191 try:
--> 192     future.set_result(cmd(*args, **kwargs))
        future = <Future at 0x16d8e8510 state=pending>
        cmd = <function Store.inject.<locals>._inner.<locals>._exec at 0x29cd107c0>
        args = ()
        kwargs = {}
    193 except Exception as e:
    194     if self._raise_synchronous_exceptions:
    195         # note, the caller of this function can also achieve this by
    196         # calling `future.result()` on the returned future object.

File ~/micromamba/envs/napari-dev/lib/python3.11/site-packages/in_n_out/_store.py:936, in Store.inject_processors.<locals>._deco.<locals>._exec(*args=(), **kwargs={})
    934 @wraps(func)
    935 def _exec(*args: P.args, **kwargs: P.kwargs) -> R:
--> 936     result = func(*args, **kwargs)
        func = <function Store.inject.<locals>._inner.<locals>._exec at 0x29cd10900>
        args = ()
        kwargs = {}
    937     if result is not None:
    938         self.process(
    939             result,
    940             type_hint=type_hint,
   (...)
    943             _funcname=getattr(func, "__qualname__", str(func)),
    944         )

File ~/micromamba/envs/napari-dev/lib/python3.11/site-packages/in_n_out/_store.py:804, in Store.inject.<locals>._inner.<locals>._exec(*args=(), **kwargs={})
    797 logger.debug(
    798     "  Calling %s with %r (injected %r)",
    799     _fname,
    800     bound.arguments,
    801     _injected_names,
    802 )
    803 try:
--> 804     result = func(**bound.arguments)
        bound = <BoundArguments (plugin='napari', sample='astronaut', qt_viewer=<napari._qt.qt_viewer.QtViewer object at 0x28586bb50>)>
        func = functools.partial(<function _add_sample at 0x17e6faa20>, plugin='napari', sample='astronaut')
        bound.arguments = {'plugin': 'napari', 'sample': 'astronaut', 'qt_viewer': <napari._qt.qt_viewer.QtViewer object at 0x28586bb50>}
    805 except TypeError as e:
    806     if "missing" not in e.args[0]:

File ~/Documents/dev/napari/napari/plugins/_npe2.py:432, in _add_sample(qt_viewer=<napari._qt.qt_viewer.QtViewer object>, plugin='napari', sample='astronaut')
    429 from napari._qt.dialogs.qt_reader_dialog import handle_gui_reading
    431 try:
--> 432     qt_viewer.viewer.open_sample(plugin, sample)
        plugin = 'napari'
        sample = 'astronaut'
        qt_viewer.viewer = Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.0, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('0', '1'), range=(RangeTuple(start=0.0, stop=2.0, step=1.0), RangeTuple(start=0.0, stop=2.0, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(0.0, 0.0), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[], help='', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='system', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x17e693e20>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
        qt_viewer = <napari._qt.qt_viewer.QtViewer object at 0x28586bb50>
    433 except MultipleReaderError as e:
    434     handle_gui_reading(
    435         [str(p) for p in e.paths],
    436         qt_viewer,
    437         stack=False,
    438     )

File ~/Documents/dev/napari/napari/components/viewer_model.py:1076, in ViewerModel.open_sample(self=Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoo...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), plugin='napari', sample='astronaut', reader_plugin=None, **kwargs={})
   1074     added = []
   1075     for datum in data(**kwargs):
-> 1076         added.extend(self._add_layer_from_data(*datum))
        added = []
        datum = (<class 'numpy.ndarray'> (512, 512, 3) uint8, {'name': 'astronaut'})
        self = Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.0, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('0', '1'), range=(RangeTuple(start=0.0, stop=2.0, step=1.0), RangeTuple(start=0.0, stop=2.0, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(0.0, 0.0), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[], help='', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='system', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x17e693e20>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
   1077     return added
   1078 if isinstance(data, (str, Path)):

File ~/Documents/dev/napari/napari/components/viewer_model.py:1497, in ViewerModel._add_layer_from_data(self=Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoo...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), data=<class 'numpy.ndarray'> (512, 512, 3) uint8, meta={'name': 'astronaut'}, layer_type='image')
   1495 try:
   1496     add_method = getattr(self, 'add_' + layer_type)
-> 1497     layer = add_method(data, **(meta or {}))
        add_method = <bound method ViewerModel.add_image of Viewer(camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.0, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=2, ndisplay [...]

2024-02-02 19:47 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +            shapes = self.data.shape
Could use `(self.data.shape, )` instead.
I checked that `np.array` yields the same for `[(int, int)]` and `((int, int), )`, but someone wiser should chime in I think.

2024-02-02 19:47 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +    ):
Same question as above, so I presume the same answer, but just in case noting it 😄

2024-02-02 19:47 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +            shapes = tuple(s[:-1] for s in shapes)
This change should be reconsidered in light of the issue above in `_ImageBase._get_level_shapes`

2024-02-02 19:47 UTC, psobolewskiPhD commented on napari/utils/_dtype.py
> +def normalize_dtype(dtype_spec: npt.DTypeLike):
Should the return also be annotated? it will return a numpy dtype, so np.dtype?

2024-02-05 16:32 UTC, dstansby commented on napari/layers/image/image.py
> +    ):
Yes, that's right

2024-02-05 16:32 UTC, dstansby commented on napari/layers/image/image.py
> +    ):
Yep, same as above 😄

2024-02-05 16:33 UTC, dstansby commented
Rebasing this has required quite a few changes - I'll fix it up, and request re-review when it's ready to go again.

2024-02-13 15:36 UTC, dstansby commented
I lost track of this a bit and the rebase is a bit tricky, so I'm going to close this PR and open a couple of new smaller ones to replace it.

2024-02-13 15:36 UTC, closed without merging