add `_coerce_contrast_limits` function and use it
napari/napari pull request #6537
Opened 2023-12-14 19:21 UTC by Czaki

# References and relevant issues

closes #5847 

# Description

Add check if image data could be visualized using vispy and if not, then rescale data.

2023-12-17 20:55 UTC, jnahlers commented
Thanks @Czaki, this method looks like it handles the toy example in the 'Steps to Reproduce' of #6533. However, I am still having trouble with my actual images. An example is [this image](https://drive.google.com/file/d/1DKs1A2f-L73lTsHOoH1w3OEPB3Z_izl2/view?usp=drive_link).

2023-12-17 21:30 UTC, Czaki commented
@jnahlers Your case is different from described in the original issue. In this case, is small contrast limits for big values. But it looks like I could easily fix the code to work with your data.

2023-12-17 22:45 UTC, jnahlers commented
It looks like there is still some kind of overflow happening? Check out [this array](https://drive.google.com/file/d/1LSuDoQDZ3kw0H__hvGIdp-Di7DGR63Ch/view?usp=drive_link), specifically  around index 50 (i.e. [50,:,:]).

2023-12-17 23:43 UTC, Czaki commented
Now It should be better. I forgot to cast infinity to float32.

2023-12-27 20:54 UTC, Czaki commented
NumPy 1.22.0 and 1.22.1 somehow overrides python logger and breaks the tests.

2024-01-23 16:38 UTC, melonora reviewed
will look further later

2024-01-23 16:38 UTC, melonora commented on napari/layers/image/image.py
>          For normal image layers, just return the actual image.
Can this be removed? I see you raise `NotImplementedError`, but you do have a function with the same name at line 1195.

2024-01-23 16:38 UTC, melonora commented on napari/_vispy/layers/image.py
> +        lim_tup = _coerce_contrast_limits(self.layer.contrast_limits)
I prefer complete variable names. I am not certain what you mean with `lim_tup`.

2024-01-23 22:44 UTC, Czaki commented on napari/layers/image/image.py
>          For normal image layers, just return the actual image.
Yes, but this functions belong to `_ImageBase` and this from line 1195 belongs to class `Image`

2024-01-23 22:47 UTC, Czaki commented on napari/_vispy/layers/image.py
> +        lim_tup = _coerce_contrast_limits(self.layer.contrast_limits)
removed

2024-01-23 22:50 UTC, melonora commented on napari/layers/image/image.py
>          For normal image layers, just return the actual image.
ah ok I see.

2024-01-23 22:58 UTC, Czaki commented on napari/layers/image/image.py
>          For normal image layers, just return the actual image.
I think that _ImageBase should be moved to separate file, but it should be separate PR. And we should Identify first all PR that touches this code.

2024-01-26 20:51 UTC, psobolewskiPhD commented on napari/utils/colormaps/colormap_utils.py
> +    # Using 8 as divisor comes from experiments.
```suggestion
    # Using 8 as divisor comes from experiments.
```
Maybe put this comment above, where the magic 8 is first used.

2024-01-26 20:56 UTC, psobolewskiPhD commented on napari/utils/colormaps/colormap_utils.py
> +        < (np.nextafter(c_min, np.float32(np.inf)) - c_min) * 64
```suggestion
        < (np.nextafter(c_min, np.float32(np.inf)) - c_min) * 64
```
Can you add comment what the 64 does?

2024-01-26 20:59 UTC, psobolewskiPhD commented on napari/utils/colormaps/colormap_utils.py
> +    vispy_min = float(np.finfo(np.float32).min / 8)
This computes to `-vispy_max`

2024-01-26 21:02 UTC, psobolewskiPhD commented on napari/utils/colormaps/_tests/test_colormap_utils.py
> +    contrast_limits = (0, 1e40)
Could we add a comment that 1e40 is larger than float32?

2024-01-26 21:05 UTC, psobolewskiPhD commented on napari/utils/colormaps/_tests/test_colormap_utils.py
> +def test_coerce_contrast_limits_with_large_values_symetric():
```suggestion
def test_coerce_contrast_limits_with_large_values_symmetric():
```

2024-01-26 21:05 UTC, psobolewskiPhD commented on napari/utils/colormaps/_tests/test_colormap_utils.py
> +    contrast_limits = (-1e40, 1e40)
Again, maybe worth a comment that both of these exceed float32

2024-01-26 21:15 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +        response = response.to_displayed(self._raw_to_displayed)
Maybe worth a comment that this is needed in analogous fashion to labels?
And update docstring of `to_displayed` in`_slice/_ImageSliceResponse`

2024-01-26 21:16 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +        lim_tup = _coerce_contrast_limits(self.contrast_limits)
Could we call `lim_tup` something like `coerced_limits` ?

2024-01-26 21:17 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +        lim_tup = _coerce_contrast_limits(self.contrast_limits)
I mean it's sort of obvious that lim_tup == limits_tuple, so maybe ignore.

2024-01-26 21:28 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +        lim_tup = _coerce_contrast_limits(self.contrast_limits)
Or I guess could unpack the tuple into the limits tuple and the other two values.

2024-01-26 21:29 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +        lim_tup = _coerce_contrast_limits(self.contrast_limits)
Or how horrible is just using:
`_coerce_contrast_limits(self.contrast_limits).contrast_limits`?
and then
`_coerce_contrast_limits(self.contrast_limits).scale`

2024-01-26 21:40 UTC, psobolewskiPhD requested changes
Grzegorz walked me through this, it works and makes sense as explained.
Based on our conversation I left a few comments to make things clearer for the next person.

2024-01-27 19:22 UTC, Czaki commented
@psobolewskiPhD I have addressed review.

@jnahlers could you check the current logic if works with your data?

2024-01-27 20:58 UTC, psobolewskiPhD commented on napari/layers/image/image.py
> +        # are outside the range of sup[ported by vispy, then data vie is
```suggestion
        # are outside the range of supported by vispy, then data view is
```

2024-01-27 21:03 UTC, psobolewskiPhD approved these changes

2024-01-27 21:18 UTC, psobolewskiPhD commented
@Czaki I think that test fail is real related to the uninitialized float64 `empty` array. Not sure if switching those arrays to zeroes would just mask something?

2024-01-28 13:51 UTC, Czaki commented
> @Czaki I think that test fail is real related to the uninitialized float64 `empty` array. Not sure if switching those arrays to zeroes would just mask something?

No. The error was the result of mistaking scale and offset. For testability, I move logic to `CoercedContrastLimits`.

2024-01-29 00:46 UTC, jnahlers commented
@Czaki I am still having trouble with the examples I [gave](https://github.com/napari/napari/pull/6537#issuecomment-1859281941) [above ](https://github.com/napari/napari/pull/6537#issuecomment-1859310100). Is this the issue of small contrast limits for big values you mentioned above?

2024-01-29 13:34 UTC, Czaki commented
@jnahlers It looks like I have made a bug when merging main into this PR. I have fixed it now.

2024-01-29 16:33 UTC, Czaki commented
As far as I could check, the tests are failing now because of `NaN`. So it looks like using `np.empty on float` is a bad idea. So it should be either a predefined array or int data. 

Random is bad because its slowdown test suite. 

cc @psobolewskiPhD

2024-01-29 17:31 UTC, psobolewskiPhD commented
Even with int could we get something strange, given that fact that it's `uninitialized`?
Maybe best to use zeros?

Going forward, could we make a set of arrays of different size/shapes using random.random and then reuse them everywhere else?

2024-01-29 17:35 UTC, Czaki commented
No. Int cannot be something strange.

We could create preset of data using fixtures.

2024-01-30 01:19 UTC, jnahlers commented
@Czaki Ping me if you want to me try the branch again, right now I'm still seeing black on the examples. Thanks for you work on this!

2024-01-30 10:34 UTC, Czaki commented
> @Czaki Ping me if you want to me try the branch again, right now I'm still seeing black on the examples. Thanks for you work on this!

I have removed an important change when removing debug print....

2024-01-30 11:03 UTC, Czaki commented
This is how it looks on my machine:

https://github.com/napari/napari/assets/3826210/dd8f9aba-e6db-42fc-8291-568bb39ccc30

I do not understand the source of vertical artifacts. But as it looks like thumbnail do not have such artifacts, maybe rescale up could be done smarter.

2024-02-01 19:47 UTC, Czaki commented
@jnahlers Is it ok now?

2024-02-01 23:16 UTC, jnahlers commented
> @jnahlers Is it ok now?

Looks good!

2024-02-03 17:34 UTC, merged