fix offset of bounding box of image
napari/napari pull request #6679
Opened 2024-02-21 12:07 UTC by Czaki

# References and relevant issues

closes ##6676

# Description

Add offset shift for bounding box to fix bounding box position

2024-02-21 12:08 UTC, Czaki commented
@psobolewskiPhD As you open Issue, could you edit the description of PR?

2024-02-22 00:40 UTC, psobolewskiPhD commented
This fixes the transform overlay, but now the bounding box one is off by 0.5 px:
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/b4ce0802-7aff-4ee2-8de3-17692d3d4ad9">

Maybe don't need the offset on the vispy side now? see:
https://github.com/napari/napari/issues/6676#issuecomment-1955726376

2024-02-22 10:41 UTC, Czaki commented
fixed

2024-02-24 02:04 UTC, psobolewskiPhD commented
Now the issue is in 3D, as that code was gated behind 2D only:
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/1c09d98d-daaa-40ad-a20a-886601965934">
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/82a71a47-3b11-415a-82f8-c7c8f5049f11">

Maybe easier to just add an offset to the interaction box?

2024-02-26 16:53 UTC, brisvag requested changes
I don't think this is the right way to fix it. Check out #6690!

2024-02-26 23:25 UTC, psobolewskiPhD commented
Based on https://github.com/napari/napari/issues/6676#issuecomment-1964634819 I think that #6690 makes more sense and is cleaner.

2024-02-27 15:46 UTC, Czaki commented on napari/_vispy/layers/base.py
> +        offset = np.ones(len(self.layer._slice_input.displayed))
```suggestion
        offset = np.zeros(len(self.layer._slice_input.displayed))
```

2024-02-29 08:24 UTC, jni approved these changes

2024-03-01 11:00 UTC, brisvag approved these changes
Ok, I think it makes sense now, and it's indeed cleaner than my version. LGTM!

2024-03-01 11:13 UTC, Czaki commented
Is the title ok?

2024-03-01 13:11 UTC, brisvag commented
Changed, this is a fix for transformbox and not boundingbox.

2024-03-02 07:37 UTC, merged