Refactor perf module for better readabiity
napari/napari pull request #6686
Opened 2024-02-23 11:58 UTC by Czaki

# References and relevant issues

Fix things pointed in #6575

# Description

Improve readability and remove obsolete code in perf module

2024-02-29 15:58 UTC, melonora requested changes
In `_timer.py`, could you please  improve the readability a bit more by adding information about the different kinds of events, either in the class docstring or as docstring of the `add` functions? Other than that, it is a lot more readable:)

2024-03-19 00:34 UTC, psobolewskiPhD reviewed
This looks good, but I agree with @melonora would be nice to have the extra info in the code, even if some of this is documented in the docs:
https://napari.org/stable/howtos/perfmon.html

2024-03-20 08:07 UTC, Czaki commented
Could you point exact places where docs should be expanded?

2024-03-20 12:41 UTC, psobolewskiPhD commented
I can't make suggestion there easily, but in `PerfTimers`:
docstring for `add_instant_event` currently `"""Add one instant event.`
- would like just few words, 1-line max, what this is/does
docstring for `add_counter_event` currently `"""Add one counter event.`
- would like just few words, 1-line max, what this is/does

I think these are then repeated in DummyTimers

2024-03-22 12:27 UTC, Czaki commented
I have updated. 
I do not feel fully familiar with perfmon code. The idea of this PR is to remove bad patterns from code.

2024-03-22 20:20 UTC, psobolewskiPhD approved these changes

2024-04-08 10:43 UTC, melonora commented on napari/utils/perf/_timers.py
> +        Comma separated categories such has "render,update".
```suggestion
        Comma separated categories such as "render, update".
```

2024-04-08 10:45 UTC, melonora approved these changes
One minor typo but I will pre-approve. Thanks @Czaki !

2024-04-09 16:09 UTC, merged