Fix transform box offset
napari/napari pull request #6690
Opened 2024-02-26 16:37 UTC by brisvag

# References and relevant issues
Fixes #6676, alternative to #6679.

# Description
As far as I know, this is all we need.

I am indeed surprised that `Layer._display_bounding_box_augmented_data_level` does not already provide the correct bounds, but this is the same for the bounding box so it should be a safe fix. Here's a reproducer for the bug on main which works here:

```py
import napari
import numpy as np
from scipy.ndimage import zoom

v = napari.Viewer()

size = 5
data = np.arange(size**3).reshape((size,) * 3)

multiscale_data = [zoom(data, 2), data]

l = v.add_image(multiscale_data)
l.mode = 'transform'
```

Changing `size` or going to non-multiscale does not affect the result, as far as I can tell.

2024-02-26 17:26 UTC, psobolewskiPhD commented
Just for the record, here is main with the snippet in the OP (plus`l.bounding_box.visible = True`):
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/f446e702-7dc7-43c7-a1b6-50d82c327094">

2024-02-27 11:51 UTC, jni commented
> Changing size or going to non-multiscale does not affect the result, as far as I can tell.

Just as a complete aside, why on earth did you make the example multiscale if it wasn't needed to demonstrate the behaviour??? 😂

2024-02-27 14:41 UTC, psobolewskiPhD commented
Probably because of https://github.com/napari/napari/issues/6320 ?

2024-02-27 15:09 UTC, Czaki commented
my main problem with this solution is that it is the same patch that is present in both places. My solution is applied in places where offset is added to the layer itself. 

If we think that this fix should be in Overlays implementation, I think it should be done in `LayerOverlayMixin`.
I also do not understand why in one implementation it interacts with `set_data` and in the second it uses `set_bounds`.

2024-02-27 15:30 UTC, brisvag commented
> my main problem with this solution is that it is the same patch that is present in both places. My solution is applied in places where offset is added to the layer itself.

Yeah but your solution assumes that the offset is the same in 2D and 3D, and that's not the case, because 2D images in vispy have the corner centered on the origin, while 3D volumes have the center of the pixel centered on the origin. So this *has* to be a vispy-side, 2D-only correction.

> If we think that this fix should be in Overlays implementation, I think it should be done in `LayerOverlayMixin`.

Sure, I thought to leave this for a later PR since this is a quick fix like this. But I can abstract it out if you think it's a good idea.

> I also do not understand why in one implementation it interacts with `set_data` and in the second it uses `set_bounds`.

This is just because `TransformBox`'s main update method is called `set_data` while for `BoundingBox` it's called `set_bounds`... We don't have a lot of consistency between overlays.

2024-02-27 15:48 UTC, Czaki commented
> Yeah but your solution assumes that the offset is the same in 2D and 3D, and that's not the case, because 2D images in vispy have the corner centered on the origin, while 3D volumes have the center of the pixel centered on the origin. So this _has_ to be a vispy-side, 2D-only correction.

Ok. There is stupid bug in my PR (I should use `np.zeros` instead of `np.ones`), but as idea I use the same offset that is used to shift data. So in 3D it should work correct (I have fixed code). 


> This is just because `TransformBox`'s main update method is called `set_data` while for `BoundingBox` it's called `set_bounds`... We don't have a lot of consistency between overlays.

So we should unify this.

> Sure, I thought to leave this for a later PR since this is a quick fix like this. But I can abstract it out if you think it's a good idea.

As we are not on "short to release" path, I think that we should fix this properly.

2024-02-29 08:27 UTC, jni requested changes
At PR party we discussed this and #6679. Your earlier comment @brisvag that #6679 assumes the same transform for 2D and 3D is now addressed, and results in simpler code that is more general. (As @Czaki points out, in his PR he just passes through the exact transform that is happening to the data, whether in 2D or 3D.) Therefore, I think we should close this one in favour of #6679.

2024-03-01 11:01 UTC, brisvag commented
Closing in favour of https://github.com/napari/napari/pull/6679.

2024-03-01 11:01 UTC, closed without merging

2024-03-02 07:36 UTC, jni commented
Closed in favour of #6679. Thanks @brisvag!