Improve typing in layers.points
napari/napari pull request #6770
Opened 2024-03-24 10:43 UTC by dstansby

More typing, this time low hanging fruit in `napari.layers.points`.

2024-03-24 15:50 UTC, psobolewskiPhD commented
Not sure why it's just in the `pip install` test, but the error does seem relevant:
```
E   ImportError: cannot import name 'Points' from partially initialized module 'napari.layers' (most likely due to a circular import) (/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/napari/layers/__init__.py)
```

2024-03-24 16:57 UTC, psobolewskiPhD requested changes
Other than the issue with the circular import this looks fine to me.

2024-03-24 16:57 UTC, psobolewskiPhD commented on napari/layers/points/points.py
> +from napari.components.dims import Dims
I think this is causing the circular import error?
Should it go under `if TYPE_CHECKING:`?

2024-03-29 13:11 UTC, psobolewskiPhD commented
Pre-commit is complaining about the changes due to dropping python 3.8 support.
Could you take care of them?

To other devs: I will be mostly out the next 4 days, so once the typing is fixed, feel free to dismiss my review and proceed.
Also feel free to ping me Tuesday if nothing happens between now and then 😄

2024-04-04 02:41 UTC, psobolewskiPhD approved these changes

2024-04-09 03:34 UTC, GenevieveBuckley approved these changes
Circular import problem is resolved, everything else looks good here.
Thanks @dstansby

2024-04-09 03:35 UTC, merged