Issue#6257
napari/napari pull request #6901
Opened 2024-05-07 18:27 UTC by MarchisLost

# References and relevant issues
 Partly closes #6257 by adding a deprecation message to the CallDefault function that seems to not be used since https://github.com/napari/napari/pull/2266

# Description

- [X] - My PR is the minimum possible work for the desired functionality
- [ ] - I have commented my code, particularly in hard-to-understand areas
- [ ] - I have made corresponding changes to docstrings and documentation (open a PR on the docs repository (https://github.com/napari/docs) if relevant!)
- [ ] - I have added tests that prove my fix is effective or that my feature works
- [X] - If I included new strings, I have used `trans._("some string")` to make them localizable.
  (For more information see our [translations guide](https://napari.org/developers/translations.html)).

2024-05-07 20:40 UTC, melissawm commented
Hi @MarchisLost  - thanks for your contribution!

Would you mind changing the title of your PR to be more descriptive of the problem you are solving? This will help your PR get more visibility and will help the maintainers understand your work better. In your case, I would suggest something like "Add deprecation message to CallDefault function" or something similar.

Welcome and let us know if you have questions 😄

2024-05-07 20:48 UTC, MarchisLost commented
Hi, thank you for the feedback.
I have changed the PR title.

2024-05-15 03:03 UTC, DragaDoncila commented
Hi @MarchisLost thanks for the PR! I'm pinging @melonora for review, because I think this is similar to #6836 that he recently looked at

2024-05-15 09:43 UTC, melonora commented on napari/utils/misc.py
> +    )
```suggestion
    warnings.warn(
        trans._(
            '`CallDefault` will be deprecated in napari v0.5.0 and will be removed in v0.6.0.',
        ),
        category=DeprecationWarning,
    )
```

2024-05-15 09:46 UTC, melonora requested changes
Thanks @MarchisLost (interesting name haha) and welcome to napari! I have checked and indeed this does not seem to be used at all. However, for good practice we have 1 release always for warning that it is deprecated and then the release after that we remove. If we slightly change the message we are good to go for merging this one. Once you have accepted the suggestion I will mark your PR ready for merge and then if nobody else has obligations we merge within a day.

2024-05-15 15:13 UTC, melonora approved these changes

2024-05-15 15:13 UTC, melonora commented
Approved! Thanks:)

2024-05-15 15:14 UTC, MarchisLost commented
Hi @melonora thank you!

2024-05-16 14:48 UTC, melonora commented
in it goes!

2024-05-16 14:48 UTC, merged