[bugfix] Adjust scale bar position based on font_size when at top
napari/napari pull request #7018
Opened 2024-06-22 15:33 UTC by psobolewskiPhD

# References and relevant issues
Closes: https://github.com/napari/napari/issues/7009

# Description
This PR aims to fix the visual issues with the scale bar text when the scale bar is positioned at the top, instead of default down.
If the size of the text is changed, the offset from the top of the canvas is increased proportionally.
(the default offset is 20 and the default font_size is 10)
Additionally, a small extra offset (1) is added for the case of the top position, so the text doesn't abut the edge of the canvas.

Default settings with this PR (just setting top_right):
<img width="747" alt="image" src="https://github.com/napari/napari/assets/76622105/d1942ed4-6c7a-455b-b98c-84fd2e786775">
Current napari main:
<img width="836" alt="image" src="https://github.com/napari/napari/assets/76622105/af6e66a6-93b0-4bba-9283-544a8476241e">

Change to font_size 30:
<img width="733" alt="image" src="https://github.com/napari/napari/assets/76622105/ff84a0dd-bb96-49bc-b66c-46c894b28619">
current napari main:
<img width="841" alt="image" src="https://github.com/napari/napari/assets/76622105/b590855d-baf6-4f78-abb3-30f18b97d226">

2024-06-22 15:35 UTC, psobolewskiPhD commented
Only thing I'm not sure of is there some pixel doubling/HiDPI thing involved between the scaling of `font_size` vs. `y_offset`. @brisvag any thoughts here?
And of course would appreciate if folks on Linux/Windows check that it looks ok! ❤️

2024-06-22 16:24 UTC, Czaki commented
> Only thing I'm not sure of is there some pixel doubling/HiDPI thing involved between the scaling of `font_size` vs. `y_offset`. @brisvag any thoughts here?

My intuitive approach is to use [`QFontrMetrics`](https://doc.qt.io/qt-6/qfontmetrics.html), but such an approach requires Qt involvement.

2024-06-23 10:47 UTC, brisvag reviewed
Any reason why you do `+ 10` in some places in the base overlay, instead of changing the value of Y offset only in the scale bar overlay subclass? Do you think this change should be true of every overlay? How does this play with the text overlay?

> My intuitive approach is to use [`QFontrMetrics`](https://doc.qt.io/qt-6/qfontmetrics.html), but such an approach requires Qt involvement.

Yeah, I'm sure there's a smarter way to do it... but not with qt hopefully :P The cool thing about the current system is that we can reuse it for things other than texts at least.

2024-06-23 10:50 UTC, Czaki commented
> Yeah, I'm sure there's a smarter way to do it... but not with qt hopefully :P The cool thing about the current system is that we can reuse it for things other than texts at least.

But without Qt we do not have access to monitor...

2024-06-23 10:52 UTC, brisvag commented
> But without Qt we do not have access to monitor...

We still plan to be able to run the canvas in other backends, no? :P

2024-06-23 10:57 UTC, Czaki commented
> We still plan to be able to run the canvas in other backends, no? :P

Yes. But it means that we should use some abstract units, and add correction in the canvas.

2024-06-23 17:52 UTC, psobolewskiPhD commented
@brisvag I couldn't think of a better way to just have the +10 while at top.
I've implemented a different approach now, using `_on_position_change`.
And I added a test for the behavior.

2024-06-23 19:01 UTC, brisvag reviewed
Good, this doesn't affect other overlays like `text`, which also depend on offset.

2024-06-24 08:29 UTC, brisvag requested changes, later dismissed
Tested on mine, and something's off:

![image](https://github.com/napari/napari/assets/23482191/aa56a63f-0fb4-4e35-85f5-e71f5634a0e8)

The spacing seems to be higher for me than for you. It might be indeed an issue with hidpi?

2024-06-25 00:49 UTC, psobolewskiPhD commented
@brisvag OK, so let's assume the 2 factor is the HiDPI factor, does it look better on your end?

2024-06-25 01:55 UTC, psobolewskiPhD commented
Needed (I think?) to use    ` viewer = make_napari_viewer()` to monkeypatch the `devicePixelRatio` but now getting the dreaded `ERROR at teardown` for the new test. 😭 
Is it because of the lambda?

2024-06-25 11:31 UTC, psobolewskiPhD commented
Huh. `devicePixelRatio` is too small a factor but 2 is too big?
What is your devicePixelRatio?
Are we running into some round-down effect?

2024-06-25 12:07 UTC, brisvag commented
I get `1.0` from this:

```py
from PyQt6.QtGui import QImage
print(QImage().devicePixelRatio())
```

maybe someone else with liux should check, I think I tinkered with scaling in the past but I can't recall what I did (I have a QHD monitor)

2024-06-25 23:27 UTC, psobolewskiPhD commented
Your font size 10 is way smaller than mine:
![image](https://github.com/napari/napari/assets/76622105/d5c4e510-50de-4d32-ac24-d1e1f027cecf)
So is your 30:
![image](https://github.com/napari/napari/assets/76622105/781d044c-21a9-4eff-83ac-d64392c8f16d)

2024-06-26 00:10 UTC, psobolewskiPhD commented
Looks like for font_size vispy multiplies by dpi (96 for non mac, 72 mac) and divides by 72:
https://github.com/vispy/vispy/blob/af2439895a13f187d840a476bd73ed480f2978f2/vispy/visuals/text/text.py#L588
So let's try the same thing for the y_offset

2024-07-02 07:49 UTC, Czaki commented
> Edit: vispy canvas has a `dpi` property, could try to use that, but not sure how best to access it here (vs. the platform check)

This DPI should not be handled here, but in vispy module. This was mentioned here:

> > We still plan to be able to run the canvas in other backends, no? :P
> 
> Yes. But it means that we should use some abstract units, and add correction in the canvas.

https://github.com/napari/napari/pull/7018#issuecomment-2184943036

2024-07-02 14:37 UTC, psobolewskiPhD commented
OK, I'll take a look.
@brisvag before I change anything, can you see if the DPI correction actually solves the problem? 🙇‍♂️

2024-07-03 10:20 UTC, brisvag commented
The spacing looks more consistent now, I don't get anything bleeding out of the screen. However, the sizes look the same as before (i.e: different from yours).

2024-07-04 14:43 UTC, psobolewskiPhD commented
Thanks! The difference in font size -- which must be preexisting -- is probably due to the same thing, the dpi difference.

2024-07-04 14:45 UTC, brisvag commented
> Thanks! The difference in font size -- which must be preexisting -- is probably due to the same thing, the dpi difference.

wanna do it here or separate PR? I think here would be best, if it's not too much work.

2024-07-04 15:05 UTC, psobolewskiPhD commented
So this is wierd:
```
viewer.window._qt_viewer.canvas._scene_canvas.dpi
Out[13]: 149.00000223775552
```
I was expecting 72 -- or a multiple there of.
```
viewer.window._qt_viewer.canvas._scene_canvas.pixel_scale
Out[16]: 2.0
```
Makes sense.
@brisvag what do those print for you?

2024-07-04 16:43 UTC, brisvag commented
```python
In [4]: viewer.window._qt_viewer.canvas._scene_canvas.dpi
Out[4]: 96.0

In [5]: viewer.window._qt_viewer.canvas._scene_canvas.pixel_scale
Out[5]: 1.0
```

2024-07-04 17:07 UTC, psobolewskiPhD commented
Yea yours makes sense. 149 makes no sense to me.

2025-01-05 23:39 UTC, psobolewskiPhD commented
Ok, i figured it out, it's indeed correct. 
vispy is computing it from the physical display dimensions (286 mm by 179 mm) and display resolution (1680 by 1050) which are returned by the OS:
https://github.com/vispy/vispy/blob/main/vispy/util/dpi/_quartz.py

And then the actual pix of the Text visual are computed:
```
        transforms = self.transforms
        n_pix = (self._font_size / 72.) * transforms.dpi  # logical pix
```
https://github.com/vispy/vispy/blob/85c4bf944d4f38acc67c215548d3701adb8d9772/vispy/visuals/text/text.py#L593-L594

So in your case it would be (10/72)*96 and in mine (10/72)*149, hence the discrepancy.
Looks like the visual should have the transforms, so hopefully we can just use that and everything will be peachy.

This difference also explains why on my mac the text clips when the box is shown:
https://github.com/napari/napari/issues/7009#issuecomment-2254822246

If I change my screen res to get something close to 96 dpi, then the text fits the box nicely.
So when changing the font_size, the box height also needs to be adjusted!

2025-01-06 04:30 UTC, psobolewskiPhD commented
@brisvag So I have an issue:
when launching napari, the overlays are created, but neither `self.node.parent` nor `self.node.text.transforms.dpi` yet exist, because the canvas doesn't yet exist?
https://github.com/napari/napari/blob/1573b119ae4595df413b1da6c0743ce243b24ee4/napari/_vispy/canvas.py#L629-L638
I thought I'd get it when `visible` is set to True, but turns out `_on_visible` is called when the overlay is created, so  I'm not sure how best to get around this.
Any advice?

2025-01-08 11:09 UTC, brisvag commented
Can't we just set some "reasonable" defaults at start?

2025-01-12 03:48 UTC, psobolewskiPhD commented
Note: this does not fix https://github.com/napari/napari/issues/7516
Using the understanding from this PR that should be doable, just requires adjusting the size of the box and positioning of the elements in response to font_size change.

2025-01-12 04:24 UTC, TimMonko commented
Definitely looks fixed to me :) 

Branch:
Default top_right:
![image](https://github.com/user-attachments/assets/143271d0-a2fb-4af6-8990-63f1778d3452)

Size 30: 
![image](https://github.com/user-attachments/assets/8c67a2aa-0d33-4f11-a193-7ef2a87020e1)

Main:
Default top_right:
![image](https://github.com/user-attachments/assets/b14025a0-3536-4781-a77a-60dfb83ed1c7)

Size 30: 
![image](https://github.com/user-attachments/assets/0ffcac7e-1e8f-4a38-abb3-59a895653f81)

2025-01-12 04:58 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +        else:
Is this doing anything? If the only time _on_position_change is called is during `on_text_change` if `top` then this will never get called. 

Would it make sense to remove the if/else? Something was throwing me off about the `if 'top'` being used twice. And I can find no other calls to `on_position_change`. Unless, L186 is the mistake and `self._on_position_change()` is always intended to be called after `_on_text_change()`

2025-01-12 04:58 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +        super()._on_position_change()
Perhaps this is the intent? 
```suggestion
        self._update_y_offset()
        super()._on_position_change()

    def _update_y_offset(self):
        """Update the y_offset based on the font size and position."""
        if 'top' in self.overlay.position:
            # convert font_size to logical pixels as vispy does
            # 96 dpi is used as the reference dpi
            font_logical_pix = self.overlay.font_size * 96 / 72
            # 7 is base value for the default 10 font size
            self.y_offset = 7 + font_logical_pix
        else:
            self.y_offset = 20
```

2025-01-12 04:58 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +        super()._on_position_change()
Well, whatever I have done different just always sets `y_offset` ... which I don't understand, because it should continue to use the same if 'top' functionality... Enjoy my musings after trying to understand why the two `if 'top'`'s lol

2025-01-12 14:02 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +        else:
Not quite, _on_position_change is part of the parent class:
https://github.com/napari/napari/blob/2df936857146c3133859345d11251e24a881c700/napari/_vispy/overlays/base.py#L82
which also has events connected to it.
You can check this by adding a print statement in this `if` and see that it will print whenever the position is changed which includes for example resizing the window.

2025-01-12 14:10 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +        super()._on_position_change()
We'd still need to implement a `_on_position_change` that would also call this `_update_y_offset`, because you want to adjust the relative positioning when the scale bar is repositioned to the top, so something like:
```
def _on_position_change(self, event=None):
        self._update_y_offset()
        super()._on_position_change()

I'm not sure this refactor is worth it? I think if `_on_position_changed` was a busy callback, then it would make it more readable, but as is, it's just adding boiler plate?
Let's see what Lorenzo has in mind as the architect of all this 😄

2025-01-12 17:46 UTC, psobolewskiPhD commented
@TimMonko I actually see from your post above that the size of the text for the scale is now smaller for you with this PR -- same for me.
Can you try:
`viewer.window._qt_viewer.canvas._scene_canvas.dpi` and let me know what that prints on your system?
I assume a value >96
So probably at default font_size this does address https://github.com/napari/napari/issues/7516
(but obviously not when increasing the font_size)

2025-01-12 19:12 UTC, TimMonko commented
@psobolewskiPhD 

```
viewer.window._qt_viewer.canvas._scene_canvas.dpi
Out[12]: 163.33129935391244

viewer.window._qt_viewer.canvas._scene_canvas.pixel_scale
Out[13]: 2.0
```

I tried to think more of how to normalize across dpi's, no luck yet. have to move on but I'll keep thinking on it

2025-01-12 19:18 UTC, psobolewskiPhD commented
@TimMonko Perfect! Your value matches what your screenshot for `main` shows: somewhat larger type than mine at 149.

> I tried to think more of how to normalize across dpi's, no luck yet. have to move on but I'll keep thinking on it

With this PR the displayed size of the type should be the same for all DPI, which also appears to be the case given your screenshot from this PR.
Should be good to go!

To fix the box issue, need to have the box adjust its size in response to font size change.

2025-01-12 19:21 UTC, TimMonko commented
Wouldn't it be desirable to have the larger expected font by default? I'll make a suggestion to adjust for pixel scale that results in what I would *expect* the default font_size to be: 

![image](https://github.com/user-attachments/assets/6232f723-20ea-4724-a1c6-bf2c6f2a2716)

To me, without adjust for pixel scale it looks too small (in proportion to the scale bar thickness)

2025-01-12 19:22 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +        else:
By the way this was very helpful. So from what you are saying, this method 'intercepts' the calls to this event and applies a bit of stuff before then sending it to the parent class.

2025-01-12 19:25 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +            dpi_scale_factor = 96 / self.node.text.transforms.dpi
adjust for canvas pixel scale

```suggestion
            dpi_scale_factor = (
                (96 / self.node.text.transforms.dpi) *
                self.viewer.window._qt_viewer.canvas._scene_canvas.pixel_scale
            )
```

2025-01-12 19:27 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
adjust for canvas pixel scale

```suggestion
            font_logical_pix = (
                self.overlay.font_size * 96 / 72 *
                self.viewer.window._qt_viewer.canvas._scene_canvas.pixel_scale
            )
```

2025-01-12 19:34 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +            dpi_scale_factor = 96 / self.node.text.transforms.dpi
I don't think this is correct? 
The pixel_scale should already be accounted for when the Visual is drawn to the canvas.
Notice that with this the text clips the box again, meaning that with this there are too many logical pixels in the text size.

2025-01-12 19:35 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
This is not correct. pixel_scale is the conversion between logical pixels and screen pixels. 
See: https://github.com/vispy/vispy/blob/469d337ae24083899e2d5a8f2fa8779de233a568/vispy/app/canvas.py#L357
So to add it here would be doubling things.

2025-01-12 19:37 UTC, psobolewskiPhD commented
@TimMonko I agree that the current size (`10`) is a bit small, but that's what @brisvag used to "design" everything.
If we want the default size larger, then we should now just increase the default `font_size`.
I'm totally open to that. Need to ensure we adjust the box properly, which needs to happen anyway. I have a plan in a followup PR.

2025-01-12 20:17 UTC, TimMonko commented
> I agree that the current size (`10`) is a bit small, but that's what @brisvag used to "design" everything.
> Notice how with this PR the text fits inside the box if you do `box = True` and everything looks like the screenshots Lorenzo posted.

Ahh, so my desire to increase it by 2x is really because my dpi shrinks what I'm used to down to effectively 0.58 of what it once was. So even though I liked it previously it was not as intended. 

I understand that this now fixes how it used to work.

This change probably needs highlighted in the release notes because this will visually effect everyone with a dpi that is not 96. Finally understanding.

BTW, this has really helped me because I eventually want to work on #7321 so this is a big head start in understanding

2025-01-13 01:47 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +        else:
Yea, all this stuff is pretty complicated and not sure you tend to run into in scripts and stuff!,
I still very much struggle with it!
And yes, that passing it up to the parent class is what `super()._on_position_change()` does.

2025-01-13 22:24 UTC, psobolewskiPhD commented
I tested this with my personal mac DPI 149 and on work mac an external display, DPI reported as 108. 
with main: 
- my personal mac with DPI 149 has much larger type size at default (font_size = 10). With `top_right` the top of the text essentially touches the top of the canvas. With `box = True` the text is clipped by the top of the box.
- the work one at DPI 108, the text is much smaller and fits quite nicely under the top of the canvas and in the box. 
with this PR:
- The rendering of the scale_bar was identical to my eyes, side by side, as compared to GUI elements and the image (detail on the shuttle). The effect is that on my personal mac (149 DPI) the text is much smaller. On the work one, it is similar (108 is close to 96). Just using `font_size = 10` the text fits under the top of the canvas and in the box on both displays.

Based on this experiment, I'm convinced that the calculations are correct.

2025-01-13 22:58 UTC, jni approved these changes
This looks ok to me. @brisvag any last words? 😜 I'd like to get this into 0.5.6!

2025-01-14 00:00 UTC, psobolewskiPhD commented
@jni do you think we should bump the default font_size?
I think I can fix the box issue https://github.com/napari/napari/issues/7516 
too, but not sure, so rather not try to cram in here. At least this fixes it for (current) default font_size.

2025-01-14 00:19 UTC, TimMonko commented
@psobolewskiPhD 
I've been thinking it might be smart to base font size on what's set in appearance. Would help someone who might need a larger base font size, like 15, because of visual impairment or a screen farther away. Though, it should maybe be a multiple of that font size, like 1.3 (so it would actually be larger, since I think default is 9 without checking). Would make sense as a separate PR and same logic could be used for future canvas overlays

2025-01-14 00:53 UTC, jni commented
@psobolewskiPhD I'm glad for default font size / pairing the default with font size preference to be done in a subsequent PR

2025-01-16 09:37 UTC, brisvag requested changes
Yes, definitely followup PR for settings and box! Great work here @TimMonko, sorry for disappearing for a while :sweat_smile:

Only one part I'm unsure about, so marking red for now!

2025-01-16 09:37 UTC, brisvag commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
Is this not resolved? what's the hardcoded 72?

2025-01-16 09:37 UTC, brisvag commented on napari/_vispy/overlays/scale_bar.py
> +        super()._on_position_change()
I think it's better to just leave the `_on_position_change` with the `super()` call for now, less messy for the PR, and we can always come back to refactor later! Sorry againf or the confusing architecture without good documentation @TimMonko, I'll have to write up something better soon :)

2025-01-16 13:29 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
@brisvag 72 is the reference vispy uses when computing logical pix for type:
https://github.com/vispy/vispy/blob/af2439895a13f187d840a476bd73ed480f2978f2/vispy/visuals/text/text.py#L588
We need to use that here to ensure the offset accounts for the pixel height of the text.
So 96 is the dpi you used when setting up everything and 72 is the vispy reference dpi.

2025-01-16 14:43 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
IMO this 96 and 72 reasoning is worth some kind of comment for future contributors! (or a more descriptive name as a constant)

2025-01-16 14:46 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
I'm open to this. I originally had the link to the vispy code after `as vispy does` but it seemed way too long.

2025-01-16 21:48 UTC, brisvag commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
yeah at least a comment would be great!

2025-01-17 02:38 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
I updated the comments. How's it now?

2025-01-17 03:08 UTC, TimMonko commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
Makes sense to me 🎉

2025-01-17 03:53 UTC, jni commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
fwiw I'm a big fan of long comments in code. I once had a look at the CPython dict code and it was like 10 lines of comments per line of code and as a result it was the easiest-to-follow code I have ever read in my life.

2025-01-17 03:56 UTC, psobolewskiPhD commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
I meant the link to vispy code is long.

2025-01-17 06:08 UTC, jni commented on napari/_vispy/overlays/scale_bar.py
> +            font_logical_pix = self.overlay.font_size * 96 / 72
That seems even less controversial? 😂

2025-01-17 09:38 UTC, brisvag commented on napari/_vispy/overlays/scale_bar.py
> +            # use 96 as the napari reference dpi for historical reasons
96 is the hardcoded logical ([it's complicated...](https://en.wikipedia.org/wiki/Dots_per_inch#Computer_monitor_DPI_standards)) dpi of the majority monitors (except macs), so it's not quite historical reasons but practical :P

2025-01-17 09:40 UTC, brisvag commented on napari/_vispy/overlays/scale_bar.py
> +            # 96 dpi is used as the napari reference dpi
so yeah, 72 is the "default" physical dpi, 96 is the "default" logical dpi (see mi comment above and https://en.wikipedia.org/wiki/Dots_per_inch#Computer_monitor_DPI_standards)

2025-01-17 09:41 UTC, brisvag approved these changes
Comments could be more precise, but I'm marking green :+1:

2025-01-17 10:33 UTC, jni commented
@brisvag do you want to push some updated comments, with a link to that wikipedia page for example? And I wouldn't mind a direct link to the vispy code:

https://github.com/vispy/vispy/blob/af2439895a13f187d840a476bd73ed480f2978f2/vispy/visuals/text/text.py#L588

despite its width 😂 

I'm also not sure about doing `*96/72` — are we matching what Vispy is doing or are we sending this to Vispy — which is then dividing by 72 — in which case we should do `*72/96`?

2025-01-17 13:01 UTC, jni commented
Merging to get the rc out. @brisvag if you want to improve the comments in a new PR they would be most welcome! 😊

2025-01-17 13:01 UTC, merged

2025-01-17 13:30 UTC, psobolewskiPhD commented
@jni in that line we're computing the offset such that the text isn't clipped by the top of the canvas. In order to account for the actual displayed height of the text, we need to get the same number of logical pixels that vispy will get when it draws the text. Hence using the same equation:
`        n_pix = (self._font_size / 72.) * transforms.dpi  # logical pix`