Accept any Mapping as output of a plugin widget
napari/napari pull request #7250
Opened 2024-09-05 07:43 UTC by Czaki

# References and relevant issues

closes #7249

# Description

2024-09-05 13:11 UTC, andy-sweet requested changes
Approving the implementation, but I think the test needs to change to reproduce the issue this should fix.

2024-09-05 13:11 UTC, andy-sweet commented on napari/_tests/test_magicgui.py
> +        meta = {'name': 'test_image'}
Given that you are creating a `dict` here, I don't think this test fails on main.

I'd assume that the return values should be initialized with `Layer.as_layer_data_tuple` to check internal consistency within napari like in the reproducer in the related issue. That's how the bug arose in practice and it seems like a natural usage.

2024-09-06 12:47 UTC, andy-sweet approved these changes
Approving because this fixes the issue reported through natural plugin usage.

I'm unsure if `Mapping` is enough for internal usage partly because we don't have type checks through the code base. But I think it's OK to try it, then expand it as needed.

Given that napari's and npe2's `types` modules both indicate they expect the second element of a layer data tuple to be a `dict`, I am considering re-implementing `_DeprecatingDict` to subclass `dict` instead of `UserDict`. But that is a separate PR that is not inconsistent with this one.

Also, I'd prefer a test with `as_layer_data_tuple` because that is the public API that others may use, but explicitly testing the implementation detail of `_DeprecatingDict` is good enough for now.

2024-09-06 12:47 UTC, andy-sweet commented on napari/_tests/test_magicgui.py
> +        data = np.random.rand(10, 10)
Nit: why use `random` here instead of `zeros`?

2024-09-06 12:47 UTC, andy-sweet commented on napari/_tests/test_magicgui.py
> +def test_from_layer_data_tuple(make_napari_viewer):
Nit: consider renaming or modifying the comment to indicate this is specifically about testing a `_DeprecatingDict`.

2024-09-06 15:16 UTC, Czaki commented
> Given that napari's and npe2's `types` modules both indicate they expect the second element of a layer data tuple to be a `dict`, I am considering re-implementing `_DeprecatingDict` to subclass `dict` instead of `UserDict`. But that is a separate PR that is not inconsistent with this one.

I strongly prefer to update types in both places to `Mapping`. Subclassing dict is not a good idea.

2024-09-11 01:53 UTC, merged