Add name to citation file
napari/napari pull request #7272
Opened 2024-09-15 13:09 UTC by beanli161514

Add @beanli161514 to CITATION.cff
```
- given-names: Rubin
  family-names: Zhao
  affiliation: Chinese Academy of Sciences - SIAT, Shenzhen, China
  orcid: https://orcid.org/0009-0005-8264-5682
  alias: BeanLi
```
Thanks for @jni, @brisvag and @Czaki 's help to get https://github.com/napari/napari/pull/7090 merged. I'd like to contribute more about 3D interactivity for this project.

2024-09-15 13:12 UTC, melonora commented
Hi @beanli161514, Thanks for your contributions and we are looking forward to your next contributions! Also if you haven't been to a community meeting already and want to meet part of the core dev team virtually, please check out our community meetings some time:)

2024-09-15 13:12 UTC, melonora approved these changes

2024-09-15 13:33 UTC, beanli161514 commented
> Hi @beanli161514, Thanks for your contributions and we are looking forward to your next contributions! Also if you haven't been to a community meeting already and want to meet part of the core dev team virtually, please check out our community meetings some time:)

Thank you! It's great working on this project, and there are still several issues with 3D interactivity. I’ll check out the meetings.

2024-09-15 17:24 UTC, Czaki commented
Any idea for more descriptive title?

2024-09-15 17:25 UTC, melonora commented
> Any idea for more descriptive title?

Add beanli161514 to citation file?

2024-09-15 19:41 UTC, Czaki commented
> > Any idea for more descriptive title?
> 
> Add beanli161514 to citation file?

Maybe. I think that your proposition will look better in changelog.

2024-09-16 01:44 UTC, jni requested changes
@beanli161514 the file is in order:

- core team, sorted by number of commits
- other contributors, sorted alphabetically by last name

The position I suggested on Zulip was based on my assumption that your last name was Li. 😅 Could you move your entry to the appropriate position for Zhao? 🙏

2024-09-16 06:56 UTC, beanli161514 commented
> @beanli161514 the file is in order:
> 
> * core team, sorted by number of commits
> * other contributors, sorted alphabetically by last name
> 
> The position I suggested on Zulip was based on my assumption that your last name was Li. 😅 Could you move your entry to the appropriate position for Zhao? 🙏

Having a last name that starts with ‘Z’ puts me at the end of most alphabetical name lists, which makes it convenient to find. 😄

2024-09-16 08:32 UTC, jni approved these changes

2024-09-16 08:35 UTC, merged